// ume-react/src/pages/checkout-success/CheckoutSuccess.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import './CheckoutSuccess.scss';

const formatPrice = (price: number) =>
  new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);

export default function CheckoutSuccess() {
  const navigate = useNavigate();
  const [order, setOrder] = useState<any>(null);

  useEffect(() => {
    const data = sessionStorage.getItem('newOrder');
    if (!data) { navigate('/'); return; }
    setOrder(JSON.parse(data));
  }, []);

  if (!order) return null;

  return (
    <div className="success-container">
      <div className="success-header">
        <div className="success-icon">✅</div>
        <h1>Đặt hàng thành công!</h1>
        <p>Cảm ơn bạn đã đặt hàng. Chúng tôi sẽ liên hệ xác nhận sớm nhất.</p>
      </div>

      <div className="success-content">
        <div className="info-section">
          <h3>🧾 Chi tiết đơn hàng</h3>
          <div className="info-grid">
            <div className="info-item">
              <label>Mã đơn hàng</label>
              <p className="order-id">{order.code}</p>
            </div>
            <div className="info-item">
              <label>Tổng thanh toán</label>
              <p className="order-total">{formatPrice(order.total)}</p>
            </div>
          </div>
        </div>

        {order.items?.length > 0 && (
          <div className="items-section">
            <h3>📦 Danh sách sản phẩm</h3>
            <div className="items-list">
              {order.items.map((item: any, i: number) => (
                <div className="item-row" key={i}>
                  <div className="item-name">
                    {item.productName || item.petName}
                    <span className="qty">SL: {item.quantity || 1}</span>
                  </div>
                  <div className="item-price">{formatPrice(item.subtotal || item.price)}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {order.shippingAddress && (
          <div className="shipping-section">
            <h3>🚚 Thông tin giao hàng</h3>
            <div className="shipping-details">
              <div className="shipping-row"><span>Người nhận</span><span>{order.shippingAddress.fullName}</span></div>
              <div className="shipping-row"><span>Số điện thoại</span><span>{order.shippingAddress.phone}</span></div>
              <div className="shipping-row">
                <span>Địa chỉ</span>
                <span>{[order.shippingAddress.address, order.shippingAddress.ward, order.shippingAddress.district, order.shippingAddress.city].filter(Boolean).join(', ')}</span>
              </div>
              {order.paymentMethod && (
                <div className="shipping-row">
                  <span>Thanh toán</span>
                  <span>{order.paymentMethod === 'COD' ? '💵 Thanh toán khi nhận hàng' : '🏦 Chuyển khoản ngân hàng'}</span>
                </div>
              )}
            </div>
          </div>
        )}

        <div className="action-buttons">
          <button className="btn-continue" onClick={() => { sessionStorage.removeItem('newOrder'); navigate('/products'); }}>
            🛍️ Tiếp tục mua sắm
          </button>
          <button className="btn-home" onClick={() => { sessionStorage.removeItem('newOrder'); navigate('/'); }}>
            🏠 Về trang chủ
          </button>
        </div>
      </div>
    </div>
  );
}

// ume-frontend/src/app/pages/checkout-success/checkout-success.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';

@Component({
  selector: 'app-checkout-success',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './checkout-success.component.html',
  styleUrl: './checkout-success.component.scss'
})
export class CheckoutSuccessComponent implements OnInit {
  order: any = null;

  constructor(private router: Router) {}

  ngOnInit(): void {
    const orderData = sessionStorage.getItem('newOrder');
    if (!orderData) {
      this.router.navigate(['/']);
      return;
    }
    this.order = JSON.parse(orderData);
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  continueShopping(): void {
    sessionStorage.removeItem('newOrder');
    this.router.navigate(['/products']);
  }

  goHome(): void {
    sessionStorage.removeItem('newOrder');
    this.router.navigate(['/']);
  }
}

<div class="success-container" *ngIf="order">
  <!-- Success Header -->
  <div class="success-header">
    <div class="success-icon">
      <i class="fas fa-check"></i>
    </div>
    <h1>Đặt hàng thành công!</h1>
    <p>Cảm ơn bạn đã đặt hàng. Chúng tôi sẽ liên hệ xác nhận đơn hàng sớm nhất.</p>
  </div>

  <!-- Success Content -->
  <div class="success-content">
    <!-- Order Info -->
    <div class="info-section">
      <h3>
        <i class="fas fa-receipt"></i> Chi tiết đơn hàng
      </h3>
      <div class="info-grid">
        <div class="info-item">
          <label>Mã đơn hàng</label>
          <p class="order-id">{{ order.code }}</p>
        </div>
        <div class="info-item">
          <label>Tổng thành toán</label>
          <p class="order-total">{{ formatPrice(order.total) }}</p>
        </div>
      </div>
    </div>

    <!-- Order Items -->
    <div class="items-section">
      <h3><i class="fas fa-box"></i> Danh sách sản phẩm</h3>
      <div class="items-list">
        <div class="item-row" *ngFor="let item of order.items">
          <div class="item-name">
            {{ item.productName || item.petName }}
            <span class="qty">SL: {{ item.quantity || 1 }}</span>
          </div>
          <div class="item-price">{{ formatPrice(item.subtotal || item.price) }}</div>
        </div>
        <div class="divider"></div>
        <div class="item-summary">
          <div class="summary-row">
            <span>Tạm tính</span>
            <span>{{ formatPrice((order.total * 0.8) || 0) }}</span>
          </div>
          <div class="summary-row">
            <span>Phí vận chuyển</span>
            <span>{{ formatPrice(30000) }}</span>
          </div>
          <div class="summary-row total">
            <span>Tổng cộng</span>
            <span>{{ formatPrice(order.total) }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Shipping Info -->
    <div class="shipping-section">
      <h3><i class="fas fa-truck"></i> Thông tin giao hàng</h3>
      <div class="shipping-details">
        <div class="shipping-row">
          <span class="label">Người nhận</span>
          <span class="value">{{ order.shippingAddress.fullName }}</span>
        </div>
        <div class="shipping-row">
          <span class="label">Số điện thoại</span>
          <span class="value">{{ order.shippingAddress.phone }}</span>
        </div>
        <div class="shipping-row">
          <span class="label">Địa chỉ</span>
          <span class="value">
            {{ order.shippingAddress.address }}, 
            {{ order.shippingAddress.ward }}, 
            {{ order.shippingAddress.district }}, 
            {{ order.shippingAddress.city }}
          </span>
        </div>
        <div class="shipping-row" *ngIf="order.paymentMethod">
          <span class="label">Phương thức thanh toán</span>
          <span class="value">
            <i class="fas fa-money-bill-wave"></i>
            {{ order.paymentMethod === 'COD' ? 'Thanh toán khi nhận hàng' : 'Chuyển khoản ngân hàng' }}
          </span>
        </div>
      </div>
    </div>

    <!-- Payment Info -->
    <div class="payment-info">
      <i class="fas fa-info-circle"></i>
      <span>Phương thức thanh toán: Thanh toán khi nhận hàng</span>
    </div>

    <!-- Action Buttons -->
    <div class="action-buttons">
      <button class="btn-continue" (click)="continueShopping()">
        <i class="fas fa-shopping-bag"></i> Tiếp tục mua sắm
      </button>
      <button class="btn-home" (click)="goHome()">
        <i class="fas fa-home"></i> Về trang chủ
      </button>
    </div>
  </div>
</div>
