// ume-react/src/pages/admin/settings/AdminSettings.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { settingsApi, uploadApi, getImageUrl } from '../../../services/api';
import '../shared/admin.scss';

const TABS = [
  { key: 'contact', icon: '📇', label: 'Liên hệ' },
  { key: 'shipping', icon: '🚚', label: 'Vận chuyển' },
  { key: 'payment', icon: '💳', label: 'Thanh toán' },
  { key: 'policy', icon: '📄', label: 'Chính sách' },
];

const defaults: any = {
  storeName: '', storeDescription: '', address: '', phone: '', email: '', workingHours: '',
  facebook: '', instagram: '', tiktok: '', youtube: '', zalo: '', mapEmbedUrl: '',
  shippingStandardPrice: 30000, shippingExpressPrice: 50000, freeShipStandardThreshold: 500000, freeShipExpressThreshold: 1000000,
  codEnabled: true, codDescription: '', bankTransferEnabled: true, bankName: '', bankAccountNumber: '', bankAccountHolder: '', bankBranch: '', bankDescription: '', bankQrImage: '',
  shippingPolicy: '', returnPolicy: '',
};

export default function AdminSettings() {
  const [activeTab, setActiveTab] = useState('contact');
  const [s, setS] = useState<any>({ ...defaults });
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [uploadingQr, setUploadingQr] = useState(false);

  useEffect(() => { loadData(); }, []);

  async function loadData() {
    setLoading(true);
    try {
      const r = await settingsApi.getSettings();
      const d = r.data?.data || r.data;
      setS({ ...defaults, ...d });
    } catch {}
    setLoading(false);
  }

  function u(field: string, value: any) { setS((prev: any) => ({ ...prev, [field]: value })); }

  async function save() {
    setSaving(true);
    try {
      await settingsApi.updateSettings(s);
      toast.success('Đã lưu cài đặt!');
    } catch { toast.error('Có lỗi xảy ra'); }
    setSaving(false);
  }

  async function onQrUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.size > 5 * 1024 * 1024) { toast.error('File không quá 5MB'); return; }
    setUploadingQr(true);
    try {
      const formData = new FormData();
      formData.append('file', file);
      formData.append('folder', 'settings');
      const r = await uploadApi.upload(formData);
      const url = r.data?.data?.url || r.data?.url || r.data;
      u('bankQrImage', url);
      toast.success('Đã upload QR!');
    } catch { toast.error('Upload thất bại'); }
    setUploadingQr(false);
  }

  if (loading) return <div className="card"><div className="card-body">Đang tải cài đặt...</div></div>;

  return (
    <div>
      <div className="page-header">
        <div><h4>⚙️ Cài đặt hệ thống</h4>
          <ol className="breadcrumb"><li><Link to="/admin">Dashboard</Link></li><li className="active">Cài đặt</li></ol>
        </div>
      </div>

      <div style={{ display: 'flex', gap: 8, marginBottom: 20, flexWrap: 'wrap' }}>
        {TABS.map(t => (
          <button key={t.key} className={`btn ${activeTab === t.key ? 'btn-gold' : 'btn-outline-gold'}`} onClick={() => setActiveTab(t.key)}>{t.icon} {t.label}</button>
        ))}
      </div>

      {/* Contact Tab */}
      {activeTab === 'contact' && (
        <div className="row">
          <div className="adm-col-6">
            <div className="card" style={{ marginBottom: 16 }}>
              <div className="card-header"><h6>🏪 Thông tin cửa hàng</h6></div>
              <div className="card-body">
                <div className="fg"><label>Tên cửa hàng</label><input className="form-control" value={s.storeName} onChange={e => u('storeName', e.target.value)} /></div>
                <div className="fg"><label>Mô tả</label><textarea className="form-control" rows={3} value={s.storeDescription} onChange={e => u('storeDescription', e.target.value)} /></div>
              </div>
            </div>
            <div className="card" style={{ marginBottom: 16 }}>
              <div className="card-header"><h6>📞 Liên hệ</h6></div>
              <div className="card-body">
                <div className="fg"><label>Địa chỉ</label><input className="form-control" value={s.address} onChange={e => u('address', e.target.value)} /></div>
                <div className="fg"><label>SĐT</label><input className="form-control" value={s.phone} onChange={e => u('phone', e.target.value)} /></div>
                <div className="fg"><label>Email</label><input className="form-control" type="email" value={s.email} onChange={e => u('email', e.target.value)} /></div>
                <div className="fg"><label>Giờ làm việc</label><input className="form-control" value={s.workingHours} onChange={e => u('workingHours', e.target.value)} /></div>
              </div>
            </div>
          </div>
          <div className="adm-col-6">
            <div className="card" style={{ marginBottom: 16 }}>
              <div className="card-header"><h6>🌐 Mạng xã hội</h6></div>
              <div className="card-body">
                {['facebook', 'instagram', 'tiktok', 'youtube', 'zalo'].map(k => (
                  <div className="fg" key={k}><label>{k.charAt(0).toUpperCase() + k.slice(1)}</label><input className="form-control" type="url" value={s[k]} onChange={e => u(k, e.target.value)} placeholder={`https://...`} /></div>
                ))}
              </div>
            </div>
            <div className="card" style={{ marginBottom: 16 }}>
              <div className="card-header"><h6>🗺️ Google Maps</h6></div>
              <div className="card-body">
                <div className="fg"><label>Embed URL</label><textarea className="form-control" rows={2} value={s.mapEmbedUrl} onChange={e => u('mapEmbedUrl', e.target.value)} placeholder="https://www.google.com/maps/embed?..." /></div>
                {s.mapEmbedUrl && <iframe src={s.mapEmbedUrl} width="100%" height="200" style={{ border: 0, borderRadius: 8, marginTop: 8 }} allowFullScreen loading="lazy" title="map" />}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Shipping Tab */}
      {activeTab === 'shipping' && (
        <div className="row">
          <div className="adm-col-6">
            <div className="card" style={{ marginBottom: 16 }}>
              <div className="card-header"><h6>💰 Phí vận chuyển</h6></div>
              <div className="card-body">
                <div className="fg"><label>Giao hàng tiêu chuẩn (VNĐ)</label><input type="number" className="form-control" value={s.shippingStandardPrice} onChange={e => u('shippingStandardPrice', +e.target.value)} /></div>
                <div className="fg"><label>Giao hàng nhanh (VNĐ)</label><input type="number" className="form-control" value={s.shippingExpressPrice} onChange={e => u('shippingExpressPrice', +e.target.value)} /></div>
              </div>
            </div>
          </div>
          <div className="adm-col-6">
            <div className="card" style={{ marginBottom: 16 }}>
              <div className="card-header"><h6>🎁 Miễn phí vận chuyển</h6></div>
              <div className="card-body">
                <div className="fg"><label>Ngưỡng miễn ship tiêu chuẩn (VNĐ)</label><input type="number" className="form-control" value={s.freeShipStandardThreshold} onChange={e => u('freeShipStandardThreshold', +e.target.value)} /></div>
                <div className="fg"><label>Ngưỡng miễn ship nhanh (VNĐ)</label><input type="number" className="form-control" value={s.freeShipExpressThreshold} onChange={e => u('freeShipExpressThreshold', +e.target.value)} /></div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Payment Tab */}
      {activeTab === 'payment' && (
        <div className="row">
          <div className="adm-col-6">
            <div className="card" style={{ marginBottom: 16 }}>
              <div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <h6>💵 Thanh toán khi nhận hàng (COD)</h6>
                <label className="toggle-switch"><input type="checkbox" checked={s.codEnabled} onChange={e => u('codEnabled', e.target.checked)} /><span className="toggle-slider"></span></label>
              </div>
              <div className="card-body">
                <div className="fg"><label>Mô tả</label><textarea className="form-control" rows={3} value={s.codDescription} onChange={e => u('codDescription', e.target.value)} /></div>
              </div>
            </div>
          </div>
          <div className="adm-col-6">
            <div className="card" style={{ marginBottom: 16 }}>
              <div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <h6>🏦 Chuyển khoản ngân hàng</h6>
                <label className="toggle-switch"><input type="checkbox" checked={s.bankTransferEnabled} onChange={e => u('bankTransferEnabled', e.target.checked)} /><span className="toggle-slider"></span></label>
              </div>
              {s.bankTransferEnabled && (
                <div className="card-body">
                  <div className="fg"><label>Tên ngân hàng</label><input className="form-control" value={s.bankName} onChange={e => u('bankName', e.target.value)} /></div>
                  <div className="fg"><label>Số tài khoản</label><input className="form-control" value={s.bankAccountNumber} onChange={e => u('bankAccountNumber', e.target.value)} /></div>
                  <div className="fg"><label>Chủ tài khoản</label><input className="form-control" value={s.bankAccountHolder} onChange={e => u('bankAccountHolder', e.target.value)} /></div>
                  <div className="fg"><label>Chi nhánh</label><input className="form-control" value={s.bankBranch} onChange={e => u('bankBranch', e.target.value)} /></div>
                  <div className="fg"><label>Mô tả</label><textarea className="form-control" rows={2} value={s.bankDescription} onChange={e => u('bankDescription', e.target.value)} /></div>
                  <div className="fg">
                    <label>Ảnh QR</label>
                    <input type="file" accept="image/*" onChange={onQrUpload} disabled={uploadingQr} />
                    {uploadingQr && <div className="sub-txt">Đang upload...</div>}
                    {s.bankQrImage && (
                      <div style={{ marginTop: 8, position: 'relative', display: 'inline-block' }}>
                        <img src={getImageUrl(s.bankQrImage)} alt="QR" style={{ maxWidth: 200, borderRadius: 8 }} />
                        <button className="btn btn-danger btn-sm" style={{ position: 'absolute', top: 4, right: 4 }} onClick={() => u('bankQrImage', '')}>✕</button>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Policy Tab */}
      {activeTab === 'policy' && (
        <div>
          <div className="card" style={{ marginBottom: 16 }}>
            <div className="card-header"><h6>🚚 Chính sách giao hàng</h6></div>
            <div className="card-body">
              <textarea className="form-control" rows={8} value={s.shippingPolicy} onChange={e => u('shippingPolicy', e.target.value)} placeholder="Nhập chính sách giao hàng..." />
            </div>
          </div>
          <div className="card" style={{ marginBottom: 16 }}>
            <div className="card-header"><h6>🔄 Chính sách đổi trả</h6></div>
            <div className="card-body">
              <textarea className="form-control" rows={5} value={s.returnPolicy} onChange={e => u('returnPolicy', e.target.value)} placeholder="Nhập chính sách đổi trả..." />
            </div>
          </div>
        </div>
      )}

      <div style={{ textAlign: 'right', marginTop: 20 }}>
        <button className="btn btn-gold" onClick={save} disabled={saving} style={{ padding: '10px 30px' }}>{saving ? 'Đang lưu...' : '💾 Lưu cài đặt'}</button>
      </div>
    </div>
  );
}

// ume-frontend/src/app/pages/admin/admin-settings/admin-settings.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api.service';
import { ToastrService } from 'ngx-toastr';
import { SafeUrlPipe } from '../../../pipes/safe-url.pipe';

@Component({
  selector: 'app-admin-settings',
  standalone: true,
  imports: [CommonModule, FormsModule, SafeUrlPipe],
  templateUrl: './admin-settings.component.html',
  styleUrl: './admin-settings.component.scss'
})
export class AdminSettingsComponent implements OnInit {
  settings: any = {
    storeName: '',
    storeDescription: '',
    address: '',
    phone: '',
    email: '',
    workingHours: '',
    facebook: '',
    instagram: '',
    tiktok: '',
    youtube: '',
    zalo: '',
    mapEmbedUrl: '',
    shippingStandardPrice: 30000,
    shippingExpressPrice: 50000,
    freeShipStandardThreshold: 500000,
    freeShipExpressThreshold: 1000000,
    shippingPolicy: '',
    returnPolicy: '',
    codEnabled: true,
    codDescription: '',
    bankTransferEnabled: true,
    bankName: '',
    bankAccountNumber: '',
    bankAccountHolder: '',
    bankBranch: '',
    bankDescription: '',
    bankQrImage: ''
  };

  loading = true;
  saving = false;
  uploadingQr = false;
  activeTab = 'contact';

  constructor(
    private api: ApiService,
    private toastr: ToastrService
  ) {}

  ngOnInit(): void {
    this.loadSettings();
  }

  loadSettings(): void {
    this.loading = true;
    this.api.getSettings().subscribe({
      next: (res: any) => {
        if (res.success) {
          this.settings = { ...this.settings, ...res.data };
        }
        this.loading = false;
      },
      error: () => {
        this.toastr.error('Không thể tải cài đặt');
        this.loading = false;
      }
    });
  }

  saveSettings(): void {
    this.saving = true;
    this.api.updateSettings(this.settings).subscribe({
      next: (res: any) => {
        if (res.success) {
          this.toastr.success('Cập nhật cài đặt thành công!');
          this.settings = { ...this.settings, ...res.data };
        }
        this.saving = false;
      },
      error: () => {
        this.toastr.error('Lỗi khi cập nhật cài đặt');
        this.saving = false;
      }
    });
  }

  onQrFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (!input.files || !input.files[0]) return;

    const file = input.files[0];
    if (file.size > 5 * 1024 * 1024) {
      this.toastr.warning('File quá lớn, tối đa 5MB');
      return;
    }

    this.uploadingQr = true;
    this.api.uploadFile(file, 'settings').subscribe({
      next: (res: any) => {
        this.uploadingQr = false;
        if (res.success) {
          this.settings.bankQrImage = res.data.url;
          this.toastr.success('Upload mã QR thành công!');
        }
      },
      error: () => {
        this.uploadingQr = false;
        this.toastr.error('Upload mã QR thất bại');
      }
    });
  }

  removeQrImage(): void {
    this.settings.bankQrImage = '';
  }

  getImg(path: string): string {
    return this.api.getImageUrl(path);
  }

  formatPrice(val: number): string {
    return new Intl.NumberFormat('vi-VN').format(val || 0);
  }
}

<div class="admin-settings-page">
  <!-- Page Header -->
  <div class="page-header">
    <h2><i class="fas fa-cog"></i> Cài đặt hệ thống</h2>
    <p class="page-desc">Quản lý thông tin liên hệ, vận chuyển, thanh toán và chính sách</p>
  </div>

  <!-- Loading -->
  <div class="loading-box" *ngIf="loading">
    <i class="fas fa-spinner fa-spin"></i> Đang tải...
  </div>

  <!-- Tabs -->
  <div class="settings-tabs" *ngIf="!loading">
    <button class="tab-btn" [class.active]="activeTab === 'contact'" (click)="activeTab = 'contact'">
      <i class="fas fa-address-card"></i> Liên hệ
    </button>
    <button class="tab-btn" [class.active]="activeTab === 'shipping'" (click)="activeTab = 'shipping'">
      <i class="fas fa-truck"></i> Vận chuyển
    </button>
    <button class="tab-btn" [class.active]="activeTab === 'payment'" (click)="activeTab = 'payment'">
      <i class="fas fa-wallet"></i> Thanh toán
    </button>
    <button class="tab-btn" [class.active]="activeTab === 'policy'" (click)="activeTab = 'policy'">
      <i class="fas fa-file-alt"></i> Chính sách
    </button>
  </div>

  <!-- TAB: Contact -->
  <div class="settings-grid" *ngIf="!loading && activeTab === 'contact'">
    <!-- Store Info -->
    <div class="settings-card">
      <div class="card-header">
        <i class="fas fa-store"></i>
        <h3>Thông tin cửa hàng</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label><i class="fas fa-signature"></i> Tên cửa hàng</label>
          <input type="text" [(ngModel)]="settings.storeName" placeholder="Nhập tên cửa hàng">
        </div>
        <div class="form-group">
          <label><i class="fas fa-align-left"></i> Mô tả</label>
          <textarea [(ngModel)]="settings.storeDescription" placeholder="Nhập mô tả cửa hàng" rows="3"></textarea>
        </div>
      </div>
    </div>

    <!-- Contact Info -->
    <div class="settings-card">
      <div class="card-header">
        <i class="fas fa-address-card"></i>
        <h3>Thông tin liên hệ</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label><i class="fas fa-map-marker-alt"></i> Địa chỉ</label>
          <input type="text" [(ngModel)]="settings.address" placeholder="Nhập địa chỉ">
        </div>
        <div class="form-group">
          <label><i class="fas fa-phone-alt"></i> Điện thoại</label>
          <input type="text" [(ngModel)]="settings.phone" placeholder="Nhập số điện thoại">
        </div>
        <div class="form-group">
          <label><i class="fas fa-envelope"></i> Email</label>
          <input type="email" [(ngModel)]="settings.email" placeholder="Nhập email">
        </div>
        <div class="form-group">
          <label><i class="fas fa-clock"></i> Giờ làm việc</label>
          <input type="text" [(ngModel)]="settings.workingHours" placeholder="VD: 8:00 - 20:00 (Thứ 2 - Chủ nhật)">
        </div>
      </div>
    </div>

    <!-- Social Media -->
    <div class="settings-card">
      <div class="card-header">
        <i class="fas fa-share-alt"></i>
        <h3>Mạng xã hội</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label><i class="fab fa-facebook-f" style="color: #1877f2;"></i> Facebook</label>
          <input type="url" [(ngModel)]="settings.facebook" placeholder="https://facebook.com/...">
        </div>
        <div class="form-group">
          <label><i class="fab fa-instagram" style="color: #e4405f;"></i> Instagram</label>
          <input type="url" [(ngModel)]="settings.instagram" placeholder="https://instagram.com/...">
        </div>
        <div class="form-group">
          <label><i class="fab fa-tiktok"></i> TikTok</label>
          <input type="url" [(ngModel)]="settings.tiktok" placeholder="https://tiktok.com/...">
        </div>
        <div class="form-group">
          <label><i class="fab fa-youtube" style="color: #ff0000;"></i> YouTube</label>
          <input type="url" [(ngModel)]="settings.youtube" placeholder="https://youtube.com/...">
        </div>
        <div class="form-group">
          <label><i class="fas fa-comment-dots" style="color: #0068ff;"></i> Zalo</label>
          <input type="url" [(ngModel)]="settings.zalo" placeholder="https://zalo.me/...">
        </div>
      </div>
    </div>

    <!-- Map -->
    <div class="settings-card">
      <div class="card-header">
        <i class="fas fa-map"></i>
        <h3>Google Maps</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label><i class="fas fa-code"></i> Google Maps Embed URL</label>
          <textarea [(ngModel)]="settings.mapEmbedUrl" placeholder="Dán URL nhúng Google Maps tại đây" rows="3"></textarea>
          <small class="form-hint">
            Vào Google Maps → Chọn địa điểm → Chia sẻ → Nhúng bản đồ → Sao chép URL trong src="..."
          </small>
        </div>
        <div class="map-preview" *ngIf="settings.mapEmbedUrl">
          <label>Xem trước bản đồ:</label>
          <iframe
            [src]="settings.mapEmbedUrl | safeUrl"
            width="100%" height="200"
            style="border:0; border-radius: 10px;" allowfullscreen="" loading="lazy">
          </iframe>
        </div>
      </div>
    </div>
  </div>

  <!-- TAB: Shipping -->
  <div class="settings-grid" *ngIf="!loading && activeTab === 'shipping'">
    <!-- Shipping Prices -->
    <div class="settings-card">
      <div class="card-header">
        <i class="fas fa-truck"></i>
        <h3>Phí vận chuyển</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label><i class="fas fa-box"></i> Phí giao hàng tiêu chuẩn (đ)</label>
          <input type="number" [(ngModel)]="settings.shippingStandardPrice" placeholder="30000">
          <small class="form-hint">Phí mặc định cho giao hàng tiêu chuẩn (3-4 ngày)</small>
        </div>
        <div class="form-group">
          <label><i class="fas fa-bolt"></i> Phí giao hàng hỏa tốc (đ)</label>
          <input type="number" [(ngModel)]="settings.shippingExpressPrice" placeholder="50000">
          <small class="form-hint">Phí mặc định cho giao hàng hỏa tốc (1-2 ngày)</small>
        </div>
      </div>
    </div>

    <!-- Free Shipping Thresholds -->
    <div class="settings-card">
      <div class="card-header">
        <i class="fas fa-gift"></i>
        <h3>Miễn phí vận chuyển</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label><i class="fas fa-tag"></i> Miễn phí ship tiêu chuẩn từ (đ)</label>
          <input type="number" [(ngModel)]="settings.freeShipStandardThreshold" placeholder="500000">
          <small class="form-hint">Đơn hàng đạt giá trị này sẽ được miễn phí ship tiêu chuẩn</small>
        </div>
        <div class="form-group">
          <label><i class="fas fa-tag"></i> Miễn phí ship hỏa tốc từ (đ)</label>
          <input type="number" [(ngModel)]="settings.freeShipExpressThreshold" placeholder="1000000">
          <small class="form-hint">Đơn hàng đạt giá trị này sẽ được miễn phí ship hỏa tốc</small>
        </div>
      </div>
    </div>
  </div>

  <!-- TAB: Payment -->
  <div class="settings-grid" *ngIf="!loading && activeTab === 'payment'">
    <!-- COD -->
    <div class="settings-card">
      <div class="card-header">
        <i class="fas fa-money-bill-wave"></i>
        <h3>Thanh toán khi nhận hàng (COD)</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label class="toggle-label">
            <span>Kích hoạt COD</span>
            <label class="switch">
              <input type="checkbox" [(ngModel)]="settings.codEnabled">
              <span class="slider round"></span>
            </label>
          </label>
        </div>
        <div class="form-group">
          <label><i class="fas fa-info-circle"></i> Mô tả phương thức COD</label>
          <textarea [(ngModel)]="settings.codDescription" placeholder="VD: Thanh toán bằng tiền mặt khi nhận hàng" rows="2"></textarea>
        </div>
      </div>
    </div>

    <!-- Bank Transfer -->
    <div class="settings-card full-width">
      <div class="card-header">
        <i class="fas fa-university"></i>
        <h3>Chuyển khoản ngân hàng</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label class="toggle-label">
            <span>Kích hoạt chuyển khoản</span>
            <label class="switch">
              <input type="checkbox" [(ngModel)]="settings.bankTransferEnabled">
              <span class="slider round"></span>
            </label>
          </label>
        </div>

        <div class="bank-form-grid" *ngIf="settings.bankTransferEnabled">
          <div class="bank-info-section">
            <div class="form-group">
              <label><i class="fas fa-university"></i> Tên ngân hàng</label>
              <input type="text" [(ngModel)]="settings.bankName" placeholder="VD: Vietcombank, MB Bank, ...">
            </div>
            <div class="form-group">
              <label><i class="fas fa-credit-card"></i> Số tài khoản</label>
              <input type="text" [(ngModel)]="settings.bankAccountNumber" placeholder="Nhập số tài khoản">
            </div>
            <div class="form-group">
              <label><i class="fas fa-user"></i> Chủ tài khoản</label>
              <input type="text" [(ngModel)]="settings.bankAccountHolder" placeholder="Nhập tên chủ tài khoản">
            </div>
            <div class="form-group">
              <label><i class="fas fa-building"></i> Chi nhánh</label>
              <input type="text" [(ngModel)]="settings.bankBranch" placeholder="Nhập chi nhánh (không bắt buộc)">
            </div>
            <div class="form-group">
              <label><i class="fas fa-info-circle"></i> Mô tả / Hướng dẫn</label>
              <textarea [(ngModel)]="settings.bankDescription" placeholder="VD: Chuyển khoản trước khi giao hàng. Nội dung: [Mã đơn hàng]" rows="3"></textarea>
            </div>
          </div>

          <div class="qr-section">
            <label><i class="fas fa-qrcode"></i> Mã QR thanh toán</label>
            <div class="qr-upload-area">
              <div class="qr-preview" *ngIf="settings.bankQrImage">
                <img [src]="getImg(settings.bankQrImage)" alt="QR Code">
                <button class="btn-remove-qr" (click)="removeQrImage()">
                  <i class="fas fa-times"></i> Xóa
                </button>
              </div>
              <div class="qr-placeholder" *ngIf="!settings.bankQrImage && !uploadingQr">
                <i class="fas fa-qrcode"></i>
                <p>Chưa có mã QR</p>
                <label class="btn-upload-qr">
                  <i class="fas fa-upload"></i> Tải lên mã QR
                  <input type="file" accept="image/*" (change)="onQrFileSelected($event)" hidden>
                </label>
              </div>
              <div class="qr-uploading" *ngIf="uploadingQr">
                <i class="fas fa-spinner fa-spin"></i>
                <p>Đang tải lên...</p>
              </div>
            </div>
            <small class="form-hint" *ngIf="settings.bankQrImage">
              <label class="btn-change-qr">
                <i class="fas fa-sync-alt"></i> Thay đổi ảnh QR
                <input type="file" accept="image/*" (change)="onQrFileSelected($event)" hidden>
              </label>
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- TAB: Policy -->
  <div class="settings-grid single-col" *ngIf="!loading && activeTab === 'policy'">
    <!-- Shipping Policy -->
    <div class="settings-card full-width">
      <div class="card-header">
        <i class="fas fa-truck"></i>
        <h3>Chính sách giao hàng</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label><i class="fas fa-file-alt"></i> Nội dung chính sách giao hàng</label>
          <textarea [(ngModel)]="settings.shippingPolicy" rows="8"
            placeholder="Nhập chính sách giao hàng (mỗi dòng là 1 mục)...&#10;VD:&#10;Giao hàng tiêu chuẩn: 3-4 ngày làm việc&#10;Giao hàng hỏa tốc: 1-2 ngày&#10;Đơn hàng có thú cưng sẽ được giao bởi nhân viên chuyên trách"></textarea>
          <small class="form-hint">Mỗi dòng sẽ hiển thị thành 1 mục trong chính sách. Để trống sẽ dùng chính sách mặc định.</small>
        </div>
      </div>
    </div>

    <!-- Return Policy -->
    <div class="settings-card full-width">
      <div class="card-header">
        <i class="fas fa-undo"></i>
        <h3>Chính sách đổi trả</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label><i class="fas fa-file-alt"></i> Nội dung chính sách đổi trả</label>
          <textarea [(ngModel)]="settings.returnPolicy" rows="5"
            placeholder="Nhập chính sách đổi trả...&#10;VD: Hỗ trợ đổi trả trong 7 ngày nếu sản phẩm lỗi từ nhà sản xuất."></textarea>
        </div>
      </div>
    </div>
  </div>

  <!-- Save Button -->
  <div class="save-bar" *ngIf="!loading">
    <button class="btn-save" (click)="saveSettings()" [disabled]="saving">
      <i class="fas" [class.fa-save]="!saving" [class.fa-spinner]="saving" [class.fa-spin]="saving"></i>
      {{ saving ? 'Đang lưu...' : 'Lưu cài đặt' }}
    </button>
  </div>
</div>
