// ume-frontend/src/app/pages/cart/cart.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { CartService, CartItem } from '../../services/cart.service';
import { ApiService } from '../../services/api.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-cart',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './cart.component.html',
  styleUrl: './cart.component.scss'
})
export class CartComponent implements OnInit, OnDestroy {
  cartItems: CartItem[] = [];
  private sub!: Subscription;

  shippingFee = 30000;

  constructor(public cartService: CartService, private apiService: ApiService) {}

  getImg(path: string): string { return this.apiService.getImageUrl(path); }

  ngOnInit(): void {
    this.sub = this.cartService.cart$.subscribe(items => {
      this.cartItems = items;
    });
  }

  ngOnDestroy(): void {
    this.sub?.unsubscribe();
  }

  get subtotal(): number {
    return this.cartService.totalAmount;
  }

  get total(): number {
    return this.cartItems.length > 0 ? this.subtotal + this.shippingFee : 0;
  }

  increaseQty(item: CartItem): void {
    this.cartService.updateQuantity(item.product._id, item.quantity + 1);
  }

  decreaseQty(item: CartItem): void {
    this.cartService.updateQuantity(item.product._id, item.quantity - 1);
  }

  removeItem(item: CartItem): void {
    this.cartService.removeItem(item.product._id);
  }

  clearCart(): void {
    this.cartService.clearCart();
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  getItemPrice(item: CartItem): number {
    return item.itemType === 'pet' ? (item.product.listingPrice || 0) : item.product.price;
  }
}

<div class="cart-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-shopping-cart"></i> Giỏ hàng</h1>
      <p>{{ cartService.totalItems }} sản phẩm trong giỏ hàng</p>
    </div>
  </div>

  <div class="container">
    <div class="cart-empty" *ngIf="cartItems.length === 0">
      <i class="fas fa-shopping-cart"></i>
      <h3>Giỏ hàng trống</h3>
      <p>Bạn chưa có sản phẩm nào trong giỏ hàng</p>
      <div class="empty-links">
        <a routerLink="/products" class="btn-shop">
          <i class="fas fa-shopping-bag"></i> Mua sản phẩm
        </a>
        <a routerLink="/pets" class="btn-shop btn-pets">
          <i class="fas fa-paw"></i> Xem thú cưng
        </a>
      </div>
    </div>

    <div class="cart-layout" *ngIf="cartItems.length > 0">
      <!-- Cart Items -->
      <div class="cart-items">
        <div class="cart-header">
          <span>Sản phẩm</span>
          <span>Đơn giá</span>
          <span>Số lượng</span>
          <span>Thành tiền</span>
          <span></span>
        </div>

        <div class="cart-item" *ngFor="let item of cartItems">
          <div class="item-product">
            <img [src]="getImg(item.product.imageUrl || item.product.mainImage)" [alt]="item.product.name"
                 onerror="this.src='assets/images/no-image.svg'">
            <div class="item-name">
              <span class="item-type-badge pet-badge" *ngIf="item.itemType === 'pet'"><i class="fas fa-paw"></i> Thú cưng</span>
              <a *ngIf="item.itemType !== 'pet'" [routerLink]="['/products', item.product._id]">{{ item.product.name }}</a>
              <a *ngIf="item.itemType === 'pet'" [routerLink]="['/pets']">{{ item.product.name }}</a>
              <small class="pet-breed" *ngIf="item.itemType === 'pet' && item.product.breed">{{ item.product.breed }}</small>
            </div>
          </div>
          <div class="item-price">{{ formatPrice(getItemPrice(item)) }}</div>
          <div class="item-quantity" *ngIf="item.itemType !== 'pet'">
            <button (click)="decreaseQty(item)">-</button>
            <span>{{ item.quantity }}</span>
            <button (click)="increaseQty(item)">+</button>
          </div>
          <div class="item-quantity pet-qty" *ngIf="item.itemType === 'pet'">
            <span>1</span>
          </div>
          <div class="item-total">{{ formatPrice(getItemPrice(item) * item.quantity) }}</div>
          <button class="btn-remove" (click)="removeItem(item)">
            <i class="fas fa-trash"></i>
          </button>
        </div>

        <div class="cart-actions">
          <a routerLink="/products" class="btn-continue">
            <i class="fas fa-arrow-left"></i> Tiếp tục mua sắm
          </a>
          <button class="btn-clear" (click)="clearCart()">
            <i class="fas fa-trash-alt"></i> Xóa giỏ hàng
          </button>
        </div>
      </div>

      <!-- Cart Summary -->
      <div class="cart-summary">
        <h3>Tóm tắt đơn hàng</h3>
        <div class="summary-row">
          <span>Tạm tính</span>
          <span>{{ formatPrice(subtotal) }}</span>
        </div>
        <div class="summary-row">
          <span>Phí vận chuyển</span>
          <span>{{ formatPrice(shippingFee) }}</span>
        </div>
        <div class="summary-divider"></div>
        <div class="summary-row total">
          <span>Tổng cộng</span>
          <span>{{ formatPrice(total) }}</span>
        </div>
        <a routerLink="/checkout" class="btn-checkout">
          <i class="fas fa-lock"></i> Thanh toán
        </a>
      </div>
    </div>
  </div>
</div>

// ume-react/src/pages/cart/Cart.tsx
import { Link } from 'react-router-dom';
import { useCart } from '../../contexts/CartContext';
import { getImageUrl } from '../../services/api';
import './Cart.scss';

const formatPrice = (price: number) =>
  new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);

export default function Cart() {
  const { items, totalItems, totalAmount, updateQuantity, removeItem, clearCart } = useCart();
  const shippingFee = 30000;

  const getItemPrice = (item: any) =>
    item.itemType === 'pet' ? (item.product.listingPrice || 0) : item.product.price;

  const total = items.length > 0 ? totalAmount + shippingFee : 0;

  return (
    <div className="cart-page">
      <div className="page-header">
        <div className="container">
          <h1>🛒 Giỏ hàng</h1>
          <p>{totalItems} sản phẩm trong giỏ hàng</p>
        </div>
      </div>

      <div className="container">
        {items.length === 0 ? (
          <div className="cart-empty">
            <span className="icon">🛒</span>
            <h3>Giỏ hàng trống</h3>
            <p>Bạn chưa có sản phẩm nào trong giỏ hàng</p>
            <div className="empty-links">
              <Link to="/products" className="btn-shop">🛍️ Mua sản phẩm</Link>
              <Link to="/pets" className="btn-shop btn-pets">🐾 Xem thú cưng</Link>
            </div>
          </div>
        ) : (
          <div className="cart-layout">
            {/* Cart Items */}
            <div className="cart-items">
              <div className="cart-header">
                <span>Sản phẩm</span>
                <span>Đơn giá</span>
                <span>Số lượng</span>
                <span>Thành tiền</span>
                <span></span>
              </div>

              {items.map(item => (
                <div className="cart-item" key={item.product._id + (item.itemType || '')}>
                  <div className="item-product">
                    <img src={getImageUrl(item.product.imageUrl || item.product.mainImage)} alt={item.product.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/no-image.svg'; }} />
                    <div className="item-name">
                      {item.itemType === 'pet' && <span className="item-type-badge pet-badge">🐾 Thú cưng</span>}
                      <Link to={item.itemType === 'pet' ? '/pets' : `/products/${item.product._id}`}>{item.product.name}</Link>
                      {item.itemType === 'pet' && item.product.breed && <small className="pet-breed">{item.product.breed}</small>}
                    </div>
                  </div>
                  <div className="item-price">{formatPrice(getItemPrice(item))}</div>
                  {item.itemType !== 'pet' ? (
                    <div className="item-quantity">
                      <button onClick={() => updateQuantity(item.product._id, item.quantity - 1)}>-</button>
                      <span>{item.quantity}</span>
                      <button onClick={() => updateQuantity(item.product._id, item.quantity + 1)}>+</button>
                    </div>
                  ) : (
                    <div className="item-quantity pet-qty"><span>1</span></div>
                  )}
                  <div className="item-total">{formatPrice(getItemPrice(item) * item.quantity)}</div>
                  <button className="btn-remove" onClick={() => removeItem(item.product._id)}>🗑️</button>
                </div>
              ))}

              <div className="cart-actions">
                <Link to="/products" className="btn-continue">← Tiếp tục mua sắm</Link>
                <button className="btn-clear" onClick={clearCart}>🗑️ Xóa giỏ hàng</button>
              </div>
            </div>

            {/* Summary */}
            <div className="cart-summary">
              <h3>Tóm tắt đơn hàng</h3>
              <div className="summary-row"><span>Tạm tính</span><span>{formatPrice(totalAmount)}</span></div>
              <div className="summary-row"><span>Phí vận chuyển</span><span>{formatPrice(shippingFee)}</span></div>
              <div className="summary-divider"></div>
              <div className="summary-row total"><span>Tổng cộng</span><span>{formatPrice(total)}</span></div>
              <Link to="/checkout" className="btn-checkout">🔒 Thanh toán</Link>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
