// ume-frontend/src/app/pages/pets/pets.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { CartService } from '../../services/cart.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-pets',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './pets.component.html',
  styleUrl: './pets.component.scss'
})
export class PetsComponent implements OnInit {
  pets: any[] = [];
  loading = false;

  selectedType = '';
  selectedListingType = '';
  petTypes = [
    { value: 'Dog', label: 'Chó' },
    { value: 'Cat', label: 'Mèo' },
    { value: 'Bird', label: 'Chim' },
    { value: 'Fish', label: 'Cá' },
    { value: 'Hamster', label: 'Hamster' },
    { value: 'Rabbit', label: 'Thỏ' },
    { value: 'Other', label: 'Khác' }
  ];
  searchText = '';
  listingTypes = [
    { value: 'Sale', label: 'Đang bán' },
    { value: 'Adoption', label: 'Nhận nuôi' }
  ];

  constructor(
    private apiService: ApiService,
    public auth: AuthService,
    private cartService: CartService,
    private toastr: ToastrService,
    private router: Router
  ) {}

  getImg(path: string): string { return this.apiService.getImageUrl(path); }

  ngOnInit(): void {
    this.loadPets();
  }

  loadPets(): void {
    this.loading = true;
    const params: any = { limit: 200 };
    if (this.selectedType) params.type = this.selectedType;
    if (this.selectedListingType) params.listingType = this.selectedListingType;
    if (this.searchText) params.search = this.searchText;

    this.apiService.getPets(params).subscribe({
      next: (res: any) => {
        this.pets = res.data?.pets || res.data || [];
        this.loading = false;
      },
      error: () => { this.loading = false; }
    });
  }

  filterByType(type: string): void {
    this.selectedType = this.selectedType === type ? '' : type;
    this.loadPets();
  }

  filterByListingType(type: string): void {
    this.selectedListingType = this.selectedListingType === type ? '' : type;
    this.loadPets();
  }

  formatPrice(price: number): string {
    if (!price) return 'Miễn phí';
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  getListingTypeLabel(type: string): string {
    const m: any = { Sale: 'Đang bán', Adoption: 'Nhận nuôi', None: '' };
    return m[type] || '';
  }

  getAgeLabel(pet: any): string {
    if (!pet.age) return '';
    const unit = pet.ageUnit === 'years' ? 'tuổi' : 'tháng';
    return `${pet.age} ${unit}`;
  }

  getTypeName(type: string): string {
    const m: any = { Dog: 'Chó', Cat: 'Mèo', Bird: 'Chim', Fish: 'Cá', Hamster: 'Hamster', Rabbit: 'Thỏ', Other: 'Khác' };
    return m[type] || type;
  }

  getGenderName(g: string): string {
    const m: any = { Male: 'Đực', Female: 'Cái', Unknown: 'Chưa rõ' };
    return m[g] || g;
  }

  addToCart(pet: any): void {
    this.cartService.addPetToCart(pet);
    this.toastr.success(`Đã thêm ${pet.name} vào giỏ hàng!`, 'Thành công');
  }

  viewPetDetail(petId: string): void {
    this.router.navigate(['/pets', petId]);
  }

  isPetInCart(pet: any): boolean {
    return this.cartService.items.some(i => i.product._id === pet._id && i.itemType === 'pet');
  }
}

<div class="pets-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-paw"></i> Tất cả thú cưng</h1>
      <p>Khám phá các bé thú cưng đáng yêu tại PetCare</p>
    </div>
  </div>

  <div class="container">
    <!-- Search -->
    <div class="search-bar">
      <input type="text" [(ngModel)]="searchText" placeholder="Tìm theo tên, giống..." (keyup.enter)="loadPets()">
      <button (click)="loadPets()"><i class="fas fa-search"></i></button>
    </div>

    <!-- Filters -->
    <div class="filter-bar">
      <div class="filter-group">
        <label>Loại thú cưng:</label>
        <div class="filter-tabs">
          <button [class.active]="selectedType === ''" (click)="filterByType('')">Tất cả</button>
          <button *ngFor="let type of petTypes"
                  [class.active]="selectedType === type.value"
                  (click)="filterByType(type.value)">
            {{ type.label }}
          </button>
        </div>
      </div>
      <div class="filter-group">
        <label>Hình thức:</label>
        <div class="filter-tabs">
          <button [class.active]="selectedListingType === ''" (click)="filterByListingType('')">Tất cả</button>
          <button [class.active]="selectedListingType === 'Adoption'" (click)="filterByListingType('Adoption')">
            <i class="fas fa-heart"></i> Nhận nuôi
          </button>
          <button [class.active]="selectedListingType === 'Sale'" (click)="filterByListingType('Sale')">
            <i class="fas fa-tag"></i> Mua bán
          </button>
        </div>
      </div>
    </div>

    <div class="loading-spinner" *ngIf="loading">
      <i class="fas fa-spinner fa-spin"></i> Đang tải...
    </div>

    <div class="pets-grid" *ngIf="!loading">
      <div class="pet-card" *ngFor="let pet of pets" (click)="viewPetDetail(pet._id)">
        <div class="pet-image">
          <img [src]="getImg(pet.imageUrl)" [alt]="pet.name"
               onerror="this.src='assets/images/default-pet.svg'">
          <span class="listing-badge" *ngIf="pet.listingType && pet.listingType !== 'None'"
                [class.adoption]="pet.listingType === 'Adoption'"
                [class.sale]="pet.listingType === 'Sale'">
            {{ getListingTypeLabel(pet.listingType) }}
          </span>
        </div>
        <div class="pet-info">
          <h3>{{ pet.name }}</h3>
          <div class="pet-details">
            <span><i class="fas fa-paw"></i> {{ getTypeName(pet.type) }}</span>
            <span *ngIf="pet.breed"><i class="fas fa-dna"></i> {{ pet.breed }}</span>
            <span *ngIf="pet.age"><i class="fas fa-birthday-cake"></i> {{ getAgeLabel(pet) }}</span>
            <span *ngIf="pet.gender"><i class="fas fa-venus-mars"></i> {{ getGenderName(pet.gender) }}</span>
          </div>
          <div class="pet-tags">
            <span class="tag" *ngIf="pet.vaccinated"><i class="fas fa-syringe"></i> Đã tiêm phòng</span>
            <span class="tag" *ngIf="pet.neutered"><i class="fas fa-cut"></i> Đã triệt sản</span>
          </div>
          <p class="pet-desc" *ngIf="pet.description">{{ pet.description }}</p>
          <div class="pet-footer">
            <span class="pet-price" *ngIf="pet.listingType === 'Sale' && pet.listingPrice">{{ formatPrice(pet.listingPrice) }}</span>
            <span class="pet-price free" *ngIf="pet.listingType === 'Adoption'">Miễn phí nhận nuôi</span>
            <div class="owner-info" *ngIf="pet.owner">
              <i class="fas fa-user"></i> {{ pet.owner.fullName || 'Ẩn danh' }}
            </div>
          </div>
          <div class="pet-buy" *ngIf="pet.listingType === 'Sale' && pet.listingPrice">
            <button class="btn-add-cart" *ngIf="!isPetInCart(pet)" (click)="addToCart(pet); $event.stopPropagation()">
              <i class="fas fa-cart-plus"></i> Thêm vào giỏ
            </button>
            <button class="btn-in-cart" *ngIf="isPetInCart(pet)" disabled (click)="$event.stopPropagation()">
              <i class="fas fa-check"></i> Đã trong giỏ
            </button>
          </div>
          <div class="pet-buy" *ngIf="pet.listingType === 'Adoption'">
            <button class="btn-adopt" (click)="addToCart(pet); $event.stopPropagation()">
              <i class="fas fa-heart"></i> Nhận nuôi
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="empty-state" *ngIf="!loading && pets.length === 0">
      <i class="fas fa-paw"></i>
      <p>Không tìm thấy thú cưng nào</p>
    </div>
  </div>
</div>

// ume-react/src/pages/pets/Pets.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { petApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import { useCart } from '../../contexts/CartContext';
import toast from 'react-hot-toast';
import './Pets.scss';

const formatPrice = (price: number) => {
  if (!price) return 'Miễn phí';
  return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
};

const petTypes = [
  { value: 'Dog', label: 'Chó' },
  { value: 'Cat', label: 'Mèo' },
  { value: 'Bird', label: 'Chim' },
  { value: 'Fish', label: 'Cá' },
  { value: 'Hamster', label: 'Hamster' },
  { value: 'Rabbit', label: 'Thỏ' },
  { value: 'Other', label: 'Khác' },
];

const typeNames: Record<string, string> = { Dog: 'Chó', Cat: 'Mèo', Bird: 'Chim', Fish: 'Cá', Hamster: 'Hamster', Rabbit: 'Thỏ', Other: 'Khác' };
const genderNames: Record<string, string> = { Male: 'Đực', Female: 'Cái', Unknown: 'Chưa rõ' };
const listingLabels: Record<string, string> = { Sale: 'Đang bán', Adoption: 'Nhận nuôi' };

export default function Pets() {
  const navigate = useNavigate();
  const { addPetToCart, items } = useCart();
  const [pets, setPets] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedType, setSelectedType] = useState('');
  const [selectedListingType, setSelectedListingType] = useState('');
  const [searchText, setSearchText] = useState('');

  useEffect(() => { loadPets(); }, []);

  const loadPets = async (type?: string, listingType?: string, search?: string) => {
    setLoading(true);
    try {
      const params: any = { limit: 200 };
      const t = type ?? selectedType;
      const lt = listingType ?? selectedListingType;
      const s = search ?? searchText;
      if (t) params.type = t;
      if (lt) params.listingType = lt;
      if (s) params.search = s;
      const res = await petApi.getAll(params);
      setPets(res.data?.data?.pets || res.data?.data || []);
    } catch {
      setPets([]);
    } finally {
      setLoading(false);
    }
  };

  const filterByType = (type: string) => {
    const newType = selectedType === type ? '' : type;
    setSelectedType(newType);
    loadPets(newType);
  };

  const filterByListingType = (type: string) => {
    const newType = selectedListingType === type ? '' : type;
    setSelectedListingType(newType);
    loadPets(undefined, newType);
  };

  const getAgeLabel = (pet: any) => {
    if (!pet.age) return '';
    const unit = pet.ageUnit === 'years' ? 'tuổi' : 'tháng';
    return `${pet.age} ${unit}`;
  };

  const isPetInCart = (pet: any) => items.some(i => i.product._id === pet._id && i.itemType === 'pet');

  const handleAddToCart = (e: React.MouseEvent, pet: any) => {
    e.stopPropagation();
    addPetToCart(pet);
    toast.success(`Đã thêm ${pet.name} vào giỏ hàng!`);
  };

  return (
    <div className="pets-page">
      <div className="page-header">
        <div className="container">
          <h1>🐾 Tất cả thú cưng</h1>
          <p>Khám phá các bé thú cưng đáng yêu tại PetCare</p>
        </div>
      </div>

      <div className="container">
        {/* Search */}
        <div className="search-bar">
          <input type="text" value={searchText} onChange={e => setSearchText(e.target.value)}
            placeholder="Tìm theo tên, giống..." onKeyDown={e => e.key === 'Enter' && loadPets()} />
          <button onClick={() => loadPets()}>🔍</button>
        </div>

        {/* Filters */}
        <div className="filter-bar">
          <div className="filter-group">
            <label>Loại thú cưng:</label>
            <div className="filter-tabs">
              <button className={!selectedType ? 'active' : ''} onClick={() => filterByType('')}>Tất cả</button>
              {petTypes.map(type => (
                <button key={type.value} className={selectedType === type.value ? 'active' : ''} onClick={() => filterByType(type.value)}>
                  {type.label}
                </button>
              ))}
            </div>
          </div>
          <div className="filter-group">
            <label>Hình thức:</label>
            <div className="filter-tabs">
              <button className={!selectedListingType ? 'active' : ''} onClick={() => filterByListingType('')}>Tất cả</button>
              <button className={selectedListingType === 'Adoption' ? 'active' : ''} onClick={() => filterByListingType('Adoption')}>
                ❤️ Nhận nuôi
              </button>
              <button className={selectedListingType === 'Sale' ? 'active' : ''} onClick={() => filterByListingType('Sale')}>
                🏷️ Mua bán
              </button>
            </div>
          </div>
        </div>

        {loading ? (
          <div className="loading-state"><div className="spinner"></div><p>Đang tải...</p></div>
        ) : pets.length === 0 ? (
          <div className="empty-state">
            <span className="icon">🐾</span>
            <p>Không tìm thấy thú cưng nào</p>
          </div>
        ) : (
          <div className="pets-grid">
            {pets.map(pet => (
              <div className="pet-card" key={pet._id} onClick={() => navigate(`/pets/${pet._id}`)}>
                <div className="pet-image">
                  <img src={getImageUrl(pet.imageUrl)} alt={pet.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/default-pet.svg'; }} />
                  {pet.listingType && pet.listingType !== 'None' && (
                    <span className={`listing-badge ${pet.listingType === 'Adoption' ? 'adoption' : 'sale'}`}>
                      {listingLabels[pet.listingType]}
                    </span>
                  )}
                </div>
                <div className="pet-info">
                  <h3>{pet.name}</h3>
                  <div className="pet-details">
                    <span>🐾 {typeNames[pet.type] || pet.type}</span>
                    {pet.breed && <span>🧬 {pet.breed}</span>}
                    {pet.age && <span>🎂 {getAgeLabel(pet)}</span>}
                    {pet.gender && <span>⚧ {genderNames[pet.gender] || pet.gender}</span>}
                  </div>
                  <div className="pet-tags">
                    {pet.vaccinated && <span className="tag">💉 Đã tiêm phòng</span>}
                    {pet.neutered && <span className="tag">✂️ Đã triệt sản</span>}
                  </div>
                  {pet.description && <p className="pet-desc">{pet.description}</p>}
                  <div className="pet-footer">
                    {pet.listingType === 'Sale' && pet.listingPrice && (
                      <span className="pet-price">{formatPrice(pet.listingPrice)}</span>
                    )}
                    {pet.listingType === 'Adoption' && (
                      <span className="pet-price free">Miễn phí nhận nuôi</span>
                    )}
                    {pet.owner && <div className="owner-info">👤 {pet.owner.fullName || 'Ẩn danh'}</div>}
                  </div>

                  {pet.listingType === 'Sale' && pet.listingPrice && (
                    <div className="pet-buy">
                      {!isPetInCart(pet) ? (
                        <button className="btn-add-cart" onClick={e => handleAddToCart(e, pet)}>🛒 Thêm vào giỏ</button>
                      ) : (
                        <button className="btn-in-cart" disabled onClick={e => e.stopPropagation()}>✓ Đã trong giỏ</button>
                      )}
                    </div>
                  )}
                  {pet.listingType === 'Adoption' && (
                    <div className="pet-buy">
                      <button className="btn-adopt" onClick={e => handleAddToCart(e, pet)}>❤️ Nhận nuôi</button>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
