// ume-frontend/src/app/pages/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { CartService } from '../../services/cart.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [CommonModule, RouterLink, FormsModule],
  templateUrl: './products.component.html',
  styleUrl: './products.component.scss'
})
export class ProductsComponent implements OnInit {
  products: any[] = [];
  categories: any[] = [];
  brands: any[] = [];
  loading = false;

  // Filters
  searchTerm = '';
  selectedCategory = '';
  selectedBrand = '';
  minPrice: number | null = null;
  maxPrice: number | null = null;
  sortBy = '-createdAt';

  // Pagination
  currentPage = 1;
  totalPages = 1;
  totalItems = 0;
  limit = 12;

  constructor(
    private apiService: ApiService,
    private cartService: CartService,
    private toastr: ToastrService
  ) {}

  getImg(path: string): string { return this.apiService.getImageUrl(path); }

  ngOnInit(): void {
    this.loadCategories();
    this.loadBrands();
    this.loadProducts();
  }

  loadCategories(): void {
    this.apiService.getCategories().subscribe({
      next: (res: any) => {
        this.categories = res.data?.categories || res.data || [];
      }
    });
  }

  loadBrands(): void {
    this.apiService.getBrands().subscribe({
      next: (res: any) => {
        this.brands = res.data?.brands || res.data || [];
      }
    });
  }

  loadProducts(): void {
    this.loading = true;
    const params: any = {
      page: this.currentPage,
      limit: this.limit,
      sort: this.sortBy
    };
    if (this.searchTerm) params.search = this.searchTerm;
    if (this.selectedCategory) params.category = this.selectedCategory;
    if (this.selectedBrand) params.brand = this.selectedBrand;
    if (this.minPrice !== null) params.minPrice = this.minPrice;
    if (this.maxPrice !== null) params.maxPrice = this.maxPrice;

    this.apiService.getProducts(params).subscribe({
      next: (res: any) => {
        this.products = res.data?.products || res.data?.items || res.data || [];
        const pagination = res.data?.pagination;
        if (pagination) {
          this.totalPages = pagination.pages || 1;
          this.totalItems = pagination.total || 0;
        } else {
          this.totalItems = this.products.length;
        }
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  onSearch(): void {
    this.currentPage = 1;
    this.loadProducts();
  }

  onCategoryFilter(categoryId: string): void {
    this.selectedCategory = categoryId;
    this.currentPage = 1;
    this.loadProducts();
  }

  onBrandFilter(brandId: string): void {
    this.selectedBrand = brandId;
    this.currentPage = 1;
    this.loadProducts();
  }

  onPriceFilter(): void {
    this.currentPage = 1;
    this.loadProducts();
  }

  onSortChange(): void {
    this.currentPage = 1;
    this.loadProducts();
  }

  goToPage(page: number): void {
    if (page >= 1 && page <= this.totalPages) {
      this.currentPage = page;
      this.loadProducts();
    }
  }

  get pages(): number[] {
    const p: number[] = [];
    const start = Math.max(1, this.currentPage - 2);
    const end = Math.min(this.totalPages, this.currentPage + 2);
    for (let i = start; i <= end; i++) p.push(i);
    return p;
  }

  addToCart(product: any): void {
    this.cartService.addToCart(product, 1);
    this.toastr.success('Đã thêm vào giỏ hàng!', 'Thành công');
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  getStars(rating: number): number[] {
    return Array(5).fill(0).map((_, i) => i < Math.round(rating) ? 1 : 0);
  }

  clearFilters(): void {
    this.searchTerm = '';
    this.selectedCategory = '';
    this.selectedBrand = '';
    this.minPrice = null;
    this.maxPrice = null;
    this.sortBy = '-createdAt';
    this.currentPage = 1;
    this.loadProducts();
  }
}

<div class="products-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-shopping-bag"></i> Sản phẩm</h1>
      <p>Sản phẩm chăm sóc thú cưng chất lượng cao</p>
    </div>
  </div>

  <div class="container">
    <div class="content-layout">
      <!-- Sidebar Filters -->
      <aside class="filter-sidebar">
        <div class="filter-section">
          <h3>Tìm kiếm</h3>
          <div class="search-box">
            <input type="text" [(ngModel)]="searchTerm" placeholder="Tìm sản phẩm..."
                   (keyup.enter)="onSearch()">
            <button (click)="onSearch()"><i class="fas fa-search"></i></button>
          </div>
        </div>

        <div class="filter-section">
          <h3>Danh mục</h3>
          <ul class="category-list">
            <li [class.active]="selectedCategory === ''" (click)="onCategoryFilter('')">
              Tất cả
            </li>
            <li *ngFor="let cat of categories"
                [class.active]="selectedCategory === cat._id"
                (click)="onCategoryFilter(cat._id)">
              {{ cat.name }}
              <span class="filter-count" *ngIf="cat.productCount">{{ cat.productCount }}</span>
            </li>
          </ul>
        </div>

        <div class="filter-section">
          <h3>Thương hiệu</h3>
          <ul class="category-list">
            <li [class.active]="selectedBrand === ''" (click)="onBrandFilter('')">
              Tất cả
            </li>
            <li *ngFor="let brand of brands"
                [class.active]="selectedBrand === brand._id"
                (click)="onBrandFilter(brand._id)">
              {{ brand.name }}
              <span class="filter-count" *ngIf="brand.productCount">{{ brand.productCount }}</span>
            </li>
          </ul>
        </div>

        <div class="filter-section">
          <h3>Khoảng giá</h3>
          <div class="price-range">
            <input type="number" [(ngModel)]="minPrice" placeholder="Từ" min="0">
            <span>-</span>
            <input type="number" [(ngModel)]="maxPrice" placeholder="Đến" min="0">
          </div>
          <button class="btn-filter" (click)="onPriceFilter()">Áp dụng</button>
        </div>

        <button class="btn-clear" (click)="clearFilters()">
          <i class="fas fa-times"></i> Xóa bộ lọc
        </button>
      </aside>

      <!-- Main Content -->
      <main class="products-main">
        <div class="toolbar">
          <span class="result-count">{{ totalItems }} sản phẩm</span>
          <select [(ngModel)]="sortBy" (change)="onSortChange()">
            <option value="-createdAt">Mới nhất</option>
            <option value="price">Giá tăng dần</option>
            <option value="-price">Giá giảm dần</option>
            <option value="-soldCount">Bán chạy</option>
            <option value="-averageRating">Đánh giá cao</option>
          </select>
        </div>

        <div class="loading-spinner" *ngIf="loading">
          <i class="fas fa-spinner fa-spin"></i> Đang tải...
        </div>

        <div class="products-grid" *ngIf="!loading">
          <div class="product-card" *ngFor="let product of products">
            <a [routerLink]="['/products', product._id]" class="product-image">
              <img [src]="getImg(product.imageUrl || product.mainImage)" [alt]="product.name"
                   onerror="this.src='assets/images/no-image.svg'">
              <span class="badge-sale" *ngIf="product.originalPrice && product.originalPrice > product.price">
                -{{ ((1 - product.price / product.originalPrice) * 100) | number:'1.0-0' }}%
              </span>
            </a>
            <div class="product-info">
              <a [routerLink]="['/products', product._id]" class="product-name">
                {{ product.name }}
              </a>
              <div class="product-category" *ngIf="product.category?.name">
                <span class="cat-tag">{{ product.category.name }}</span>
                <span class="brand-tag" *ngIf="product.brand?.name">{{ product.brand.name }}</span>
              </div>
              <div class="product-rating">
                <i *ngFor="let s of getStars(product.averageRating)"
                   class="fas fa-star" [class.filled]="s === 1"></i>
                <span>({{ product.totalReviews || 0 }})</span>
              </div>
              <div class="product-price">
                <span class="current-price">{{ formatPrice(product.price) }}</span>
                <span class="original-price" *ngIf="product.originalPrice && product.originalPrice > product.price">
                  {{ formatPrice(product.originalPrice) }}
                </span>
              </div>
              <button class="btn-add-cart" (click)="addToCart(product)"
                      [disabled]="product.stockQuantity <= 0">
                <i class="fas fa-cart-plus"></i>
                {{ product.stockQuantity > 0 ? 'Thêm vào giỏ' : 'Hết hàng' }}
              </button>
            </div>
          </div>
        </div>

        <div class="empty-state" *ngIf="!loading && products.length === 0">
          <i class="fas fa-box-open"></i>
          <p>Không tìm thấy sản phẩm nào</p>
        </div>

        <!-- Pagination -->
        <div class="pagination" *ngIf="totalPages > 1">
          <button (click)="goToPage(currentPage - 1)" [disabled]="currentPage === 1">
            <i class="fas fa-chevron-left"></i>
          </button>
          <button *ngFor="let p of pages" (click)="goToPage(p)"
                  [class.active]="p === currentPage">{{ p }}</button>
          <button (click)="goToPage(currentPage + 1)" [disabled]="currentPage === totalPages">
            <i class="fas fa-chevron-right"></i>
          </button>
        </div>
      </main>
    </div>
  </div>
</div>

// ume-react/src/pages/products/Products.tsx
import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { productApi, categoryApi, brandApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import { useCart } from '../../contexts/CartContext';
import toast from 'react-hot-toast';
import './Products.scss';

const formatPrice = (price: number) =>
  new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);

const getStars = (rating: number) =>
  Array(5).fill(0).map((_, i) => (i < Math.round(rating) ? 1 : 0));

export default function Products() {
  const { addToCart } = useCart();
  const [products, setProducts] = useState<any[]>([]);
  const [categories, setCategories] = useState<any[]>([]);
  const [brands, setBrands] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('');
  const [selectedBrand, setSelectedBrand] = useState('');
  const [minPrice, setMinPrice] = useState('');
  const [maxPrice, setMaxPrice] = useState('');
  const [sortBy, setSortBy] = useState('newest');
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const limit = 12;

  const loadProducts = useCallback(async (page = currentPage) => {
    setLoading(true);
    try {
      const params: any = { page, limit, sort: sortBy };
      if (searchTerm) params.search = searchTerm;
      if (selectedCategory) params.category = selectedCategory;
      if (selectedBrand) params.brand = selectedBrand;
      if (minPrice) params.minPrice = minPrice;
      if (maxPrice) params.maxPrice = maxPrice;
      const res = await productApi.getAll(params);
      setProducts(res.data?.data?.products || res.data?.data || []);
      setTotalPages(res.data?.data?.pagination?.pages || 1);
    } catch {
      setProducts([]);
    } finally {
      setLoading(false);
    }
  }, [currentPage, sortBy, searchTerm, selectedCategory, selectedBrand, minPrice, maxPrice]);

  useEffect(() => {
    loadProducts();
  }, [loadProducts]);

  useEffect(() => {
    categoryApi.getAll().then(res => setCategories(res.data?.data?.categories || res.data?.data || [])).catch(() => {});
    brandApi.getAll().then(res => setBrands(res.data?.data?.brands || res.data?.data || [])).catch(() => {});
  }, []);

  const handleSearch = () => {
    setCurrentPage(1);
    loadProducts(1);
  };

  const handleCategoryChange = (id: string) => {
    setSelectedCategory(id);
    setCurrentPage(1);
  };

  const handleBrandChange = (id: string) => {
    setSelectedBrand(id);
    setCurrentPage(1);
  };

  const handleSort = (val: string) => {
    setSortBy(val);
    setCurrentPage(1);
  };

  const clearFilters = () => {
    setSearchTerm('');
    setSelectedCategory('');
    setSelectedBrand('');
    setMinPrice('');
    setMaxPrice('');
    setSortBy('newest');
    setCurrentPage(1);
  };

  const handleAddToCart = (product: any) => {
    addToCart(product, 1);
    toast.success(`Đã thêm ${product.name} vào giỏ hàng!`);
  };

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <div className="products-page">
      <div className="page-header">
        <div className="container">
          <h1>🛍️ Sản phẩm</h1>
          <p>Khám phá các sản phẩm chất lượng cho thú cưng</p>
        </div>
      </div>

      <div className="container">
        <div className="products-layout">
          {/* Sidebar Filters */}
          <aside className="filters-sidebar">
            <div className="filter-section">
              <h3>🔍 Tìm kiếm</h3>
              <div className="search-box">
                <input
                  type="text"
                  placeholder="Tên sản phẩm..."
                  value={searchTerm}
                  onChange={e => setSearchTerm(e.target.value)}
                  onKeyDown={e => e.key === 'Enter' && handleSearch()}
                />
                <button onClick={handleSearch}>🔍</button>
              </div>
            </div>

            <div className="filter-section">
              <h3>📁 Danh mục</h3>
              <ul className="filter-list">
                <li className={!selectedCategory ? 'active' : ''} onClick={() => handleCategoryChange('')}>Tất cả</li>
                {categories.map(cat => (
                  <li key={cat._id} className={selectedCategory === cat._id ? 'active' : ''} onClick={() => handleCategoryChange(cat._id)}>
                    {cat.name}
                  </li>
                ))}
              </ul>
            </div>

            <div className="filter-section">
              <h3>🏷️ Thương hiệu</h3>
              <ul className="filter-list">
                <li className={!selectedBrand ? 'active' : ''} onClick={() => handleBrandChange('')}>Tất cả</li>
                {brands.map(b => (
                  <li key={b._id} className={selectedBrand === b._id ? 'active' : ''} onClick={() => handleBrandChange(b._id)}>
                    {b.name}
                  </li>
                ))}
              </ul>
            </div>

            <div className="filter-section">
              <h3>💰 Giá</h3>
              <div className="price-inputs">
                <input type="number" placeholder="Từ" value={minPrice} onChange={e => setMinPrice(e.target.value)} />
                <span>-</span>
                <input type="number" placeholder="Đến" value={maxPrice} onChange={e => setMaxPrice(e.target.value)} />
              </div>
              <button className="btn-apply" onClick={handleSearch}>Áp dụng</button>
            </div>

            <button className="btn-clear" onClick={clearFilters}>🗑️ Xóa bộ lọc</button>
          </aside>

          {/* Products Grid */}
          <div className="products-main">
            <div className="products-toolbar">
              <span className="results-count">{products.length} sản phẩm</span>
              <select value={sortBy} onChange={e => handleSort(e.target.value)}>
                <option value="newest">Mới nhất</option>
                <option value="price_asc">Giá: Thấp → Cao</option>
                <option value="price_desc">Giá: Cao → Thấp</option>
                <option value="name_asc">Tên: A → Z</option>
                <option value="bestselling">Bán chạy</option>
              </select>
            </div>

            {loading ? (
              <div className="loading-state"><div className="spinner"></div><p>Đang tải sản phẩm...</p></div>
            ) : products.length === 0 ? (
              <div className="empty-state">
                <span className="icon">📦</span>
                <p>Không tìm thấy sản phẩm nào</p>
                <button className="btn-primary" onClick={clearFilters}>Xóa bộ lọc</button>
              </div>
            ) : (
              <>
                <div className="products-grid">
                  {products.map(product => (
                    <div className="product-card" key={product._id}>
                      <Link to={`/products/${product._id}`} className="product-image">
                        <img src={getImageUrl(product.imageUrl)} alt={product.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/no-product.svg'; }} />
                        {product.discountPrice && product.discountPrice < product.price && (
                          <span className="discount-badge">-{Math.round((1 - product.discountPrice / product.price) * 100)}%</span>
                        )}
                        {product.isHotDeal && <span className="hot-badge">🔥 Hot</span>}
                      </Link>
                      <div className="product-info">
                        <Link to={`/products/${product._id}`} className="product-name">{product.name}</Link>
                        <div className="product-rating">
                          {getStars(product.averageRating || 0).map((s, i) => (
                            <span key={i} className={s ? 'star filled' : 'star'}>★</span>
                          ))}
                          <span className="rating-count">({product.totalReviews || 0})</span>
                        </div>
                        <div className="product-price">
                          {product.discountPrice && product.discountPrice < product.price ? (
                            <>
                              <span className="current-price">{formatPrice(product.discountPrice)}</span>
                              <span className="original-price">{formatPrice(product.price)}</span>
                            </>
                          ) : (
                            <span className="current-price">{formatPrice(product.price)}</span>
                          )}
                        </div>
                        <button className="btn-add-cart" onClick={() => handleAddToCart(product)} disabled={product.stock === 0}>
                          {product.stock === 0 ? 'Hết hàng' : '🛒 Thêm vào giỏ'}
                        </button>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Pagination */}
                {totalPages > 1 && (
                  <div className="pagination">
                    <button disabled={currentPage === 1} onClick={() => handlePageChange(currentPage - 1)}>‹</button>
                    {Array.from({ length: totalPages }, (_, i) => i + 1).map(page => (
                      <button key={page} className={currentPage === page ? 'active' : ''} onClick={() => handlePageChange(page)}>{page}</button>
                    ))}
                    <button disabled={currentPage === totalPages} onClick={() => handlePageChange(currentPage + 1)}>›</button>
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
