// ume-frontend/src/app/pages/services/services.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, ActivatedRoute } from '@angular/router';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-services',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './services.component.html',
  styleUrl: './services.component.scss'
})
export class ServicesComponent implements OnInit {
  services: any[] = [];
  categories: any[] = [];
  selectedCategory = '';
  loading = false;

  constructor(
    private apiService: ApiService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.route.queryParams.subscribe(params => {
      if (params['category']) {
        this.selectedCategory = params['category'];
      }
      this.loadCategories();
      this.loadServices();
    });
  }

  loadCategories(): void {
    this.apiService.getServiceCategories().subscribe({
      next: (res: any) => {
        this.categories = res.data?.items || res.data || [];
      }
    });
  }

  loadServices(): void {
    this.loading = true;
    const params: any = {};
    if (this.selectedCategory) params.category = this.selectedCategory;

    this.apiService.getServices(params).subscribe({
      next: (res: any) => {
        this.services = res.data?.items || res.data || [];
        this.loading = false;
      },
      error: () => { this.loading = false; }
    });
  }

  filterByCategory(catId: string): void {
    this.selectedCategory = catId;
    this.loadServices();
  }

  viewServiceDetail(serviceId: string): void {
    this.router.navigate(['/services', serviceId]);
  }

  bookService(serviceId: string): void {
    this.router.navigate(['/booking'], { queryParams: { service: serviceId } });
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  getImageUrl(path: string, placeholder?: string): string {
    return this.apiService.getImageUrl(path, placeholder);
  }

  formatDuration(minutes: number): string {
    if (minutes < 60) return `${minutes} phút`;
    const h = Math.floor(minutes / 60);
    const m = minutes % 60;
    return m > 0 ? `${h} giờ ${m} phút` : `${h} giờ`;
  }

  getStars(rating: number): number[] {
    return Array(5).fill(0).map((_, i) => i < Math.round(rating) ? 1 : 0);
  }
}

<div class="services-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-concierge-bell"></i> Dịch vụ</h1>
      <p>Dịch vụ chăm sóc thú cưng chuyên nghiệp</p>
    </div>
  </div>

  <div class="container">
    <!-- Category Tabs -->
    <div class="category-tabs">
      <button [class.active]="selectedCategory === ''" (click)="filterByCategory('')">
        Tất cả
      </button>
      <button *ngFor="let cat of categories"
              [class.active]="selectedCategory === cat._id"
              (click)="filterByCategory(cat._id)">
        {{ cat.name }}
      </button>
    </div>

    <div class="loading-spinner" *ngIf="loading">
      <i class="fas fa-spinner fa-spin"></i> Đang tải...
    </div>

    <div class="services-grid" *ngIf="!loading">
      <div class="service-card" *ngFor="let service of services" (click)="viewServiceDetail(service._id)">
        <div class="service-image">
          <img [src]="getImageUrl(service.imageUrl, 'assets/images/no-service.svg')" [alt]="service.name"
               onerror="this.src='assets/images/no-service.svg'">
        </div>
        <div class="service-content">
          <h3>{{ service.name }}</h3>
          <p class="service-desc">{{ service.description }}</p>
          <div class="service-meta">
            <div class="meta-item">
              <i class="fas fa-clock"></i>
              <span>{{ formatDuration(service.durationMinutes) }}</span>
            </div>
            <div class="meta-item">
              <i class="fas fa-star filled"></i>
              <span>{{ service.averageRating?.toFixed(1) || '0.0' }} ({{ service.totalReviews || 0 }})</span>
            </div>
          </div>
          <div class="service-footer">
            <span class="service-price">{{ formatPrice(service.price) }}</span>
            <button class="btn-book" (click)="bookService(service._id); $event.stopPropagation()">
              <i class="fas fa-calendar-check"></i> Đặt lịch ngay
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="empty-state" *ngIf="!loading && services.length === 0">
      <i class="fas fa-concierge-bell"></i>
      <p>Không tìm thấy dịch vụ nào</p>
    </div>
  </div>
</div>

// ume-react/src/pages/services/Services.tsx
import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { serviceApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import './Services.scss';

const formatPrice = (price: number) =>
  new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);

const formatDuration = (minutes: number) => {
  if (!minutes) return 'N/A';
  if (minutes < 60) return `${minutes} phút`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m > 0 ? `${h} giờ ${m} phút` : `${h} giờ`;
};

const getStars = (rating: number) =>
  Array(5).fill(0).map((_, i) => (i < Math.round(rating) ? 1 : 0));

export default function Services() {
  const navigate = useNavigate();
  const [services, setServices] = useState<any[]>([]);
  const [categories, setCategories] = useState<any[]>([]);
  const [selectedCategory, setSelectedCategory] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadServices();
    loadCategories();
  }, []);

  const loadServices = async (categoryId?: string) => {
    setLoading(true);
    try {
      const params: any = { limit: 100 };
      if (categoryId) params.category = categoryId;
      const res = await serviceApi.getAll(params);
      setServices(res.data?.data?.services || res.data?.data || []);
    } catch {
      setServices([]);
    } finally {
      setLoading(false);
    }
  };

  const loadCategories = async () => {
    try {
      const res = await serviceApi.getCategories();
      setCategories(res.data?.data?.categories || res.data?.data || []);
    } catch {}
  };

  const filterByCategory = (catId: string) => {
    setSelectedCategory(catId);
    loadServices(catId || undefined);
  };

  const bookService = (serviceId: string) => {
    navigate(`/booking?service=${serviceId}`);
  };

  return (
    <div className="services-page">
      <div className="page-header">
        <div className="container">
          <h1>✂️ Dịch vụ của chúng tôi</h1>
          <p>Chăm sóc thú cưng chuyên nghiệp với đội ngũ giàu kinh nghiệm</p>
        </div>
      </div>

      <div className="container">
        {/* Category Tabs */}
        <div className="category-tabs">
          <button className={!selectedCategory ? 'active' : ''} onClick={() => filterByCategory('')}>
            Tất cả
          </button>
          {categories.map(cat => (
            <button key={cat._id} className={selectedCategory === cat._id ? 'active' : ''} onClick={() => filterByCategory(cat._id)}>
              {cat.name}
            </button>
          ))}
        </div>

        {loading ? (
          <div className="loading-state"><div className="spinner"></div><p>Đang tải dịch vụ...</p></div>
        ) : services.length === 0 ? (
          <div className="empty-state">
            <span className="icon">🐾</span>
            <p>Không tìm thấy dịch vụ nào</p>
          </div>
        ) : (
          <div className="services-grid">
            {services.map(service => (
              <div className="service-card" key={service._id}>
                <Link to={`/services/${service._id}`} className="service-image">
                  <img src={getImageUrl(service.imageUrl)} alt={service.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/no-service.svg'; }} />
                  {service.isHotDeal && <span className="hot-badge">🔥 Ưu đãi</span>}
                  {service.isFeatured && <span className="featured-badge">⭐</span>}
                </Link>
                <div className="service-info">
                  <Link to={`/services/${service._id}`} className="service-name">{service.name}</Link>
                  <p className="service-desc">{service.description}</p>
                  <div className="service-meta">
                    <span className="duration">⏱️ {formatDuration(service.durationMinutes)}</span>
                    <div className="rating">
                      {getStars(service.averageRating || 0).map((s, i) => (
                        <span key={i} className={s ? 'star filled' : 'star'}>★</span>
                      ))}
                      <span className="count">({service.totalReviews || 0})</span>
                    </div>
                  </div>
                  <div className="service-footer">
                    <span className="price">{formatPrice(service.price)}</span>
                    <button className="btn-book" onClick={() => bookService(service._id)}>Đặt lịch</button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
