// ume-react/src/pages/login/Login.tsx
import { useState, useEffect, useRef } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import config from '../../config';
import toast from 'react-hot-toast';
import './Login.scss';

declare global {
  interface Window {
    google?: {
      accounts: {
        id: {
          initialize: (config: any) => void;
          renderButton: (element: HTMLElement, config: any) => void;
        };
      };
    };
  }
}

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [googleLoading, setGoogleLoading] = useState(false);
  const { login, googleLogin } = useAuth();
  const navigate = useNavigate();
  const googleBtnRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Load Google Identity Services script
    const script = document.createElement('script');
    script.src = 'https://accounts.google.com/gsi/client';
    script.async = true;
    script.defer = true;
    script.onload = () => {
      if (window.google && googleBtnRef.current) {
        window.google.accounts.id.initialize({
          client_id: config.googleClientId,
          callback: handleGoogleCredential,
        });
        window.google.accounts.id.renderButton(googleBtnRef.current, {
          type: 'standard',
          theme: 'outline',
          size: 'large',
          text: 'signin_with',
          width: googleBtnRef.current.offsetWidth,
          locale: 'vi_VN',
        });
      }
    };
    document.head.appendChild(script);
    return () => { script.remove(); };
  }, []);

  async function handleGoogleCredential(response: { credential: string }) {
    setGoogleLoading(true);
    try {
      await googleLogin(response.credential);
      toast.success('Đăng nhập Google thành công!');
      navigate('/');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Đăng nhập Google thất bại');
    } finally {
      setGoogleLoading(false);
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !password) {
      toast.error('Vui lòng nhập đầy đủ thông tin');
      return;
    }

    setLoading(true);
    try {
      await login({ email, password });
      toast.success('Đăng nhập thành công!');
      navigate('/');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Đăng nhập thất bại. Vui lòng thử lại.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <div className="paw-decorations">
        {[1,2,3,4,5,6].map(i => <span key={i} className={`paw paw-${i}`}>🐾</span>)}
      </div>

      <div className="login-container">
        <div className="login-illustration">
          <div className="illustration-content">
            <div className="illustration-emoji">🐕‍🦺</div>
            <h2>Chào mừng trở lại!</h2>
            <p>Đăng nhập để đặt lịch chăm sóc thú cưng, mua sắm sản phẩm và quản lý thú cưng của bạn.</p>
            <div className="illustration-features">
              <div className="feature">✅ Đặt lịch nhanh chóng</div>
              <div className="feature">✅ Theo dõi lịch hẹn</div>
              <div className="feature">✅ Ưu đãi độc quyền</div>
              <div className="feature">✅ Quản lý thú cưng</div>
            </div>
            <div className="illustration-pets">
              <span>🐶</span><span>🐱</span><span>🐰</span><span>🐹</span>
            </div>
          </div>
        </div>

        <div className="login-form-section">
          <div className="form-wrapper">
            <div className="form-header">
              <Link to="/" className="form-logo">🐾 PetCare</Link>
              <h1>Đăng nhập</h1>
              <p>Nhập thông tin tài khoản của bạn</p>
            </div>

            <div className="divider"><span>Đăng nhập với email</span></div>

            <div className="google-btn-wrapper" ref={googleBtnRef}>
              {googleLoading && <div className="google-loading">⏳ Đang xử lý...</div>}
            </div>

            <div className="divider"><span>hoặc</span></div>

            <form onSubmit={handleSubmit} className="login-form">
              <div className="form-group">
                <label htmlFor="email">📧 Email</label>
                <input type="email" id="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Nhập email của bạn" required autoComplete="email" />
              </div>

              <div className="form-group">
                <label htmlFor="password">🔒 Mật khẩu</label>
                <div className="password-input">
                  <input type={showPassword ? 'text' : 'password'} id="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Nhập mật khẩu" required autoComplete="current-password" />
                  <button type="button" className="toggle-password" onClick={() => setShowPassword(!showPassword)}>
                    {showPassword ? '🙈' : '👁️'}
                  </button>
                </div>
              </div>

              <div className="form-options">
                <label className="remember-me">
                  <input type="checkbox" /> Ghi nhớ đăng nhập
                </label>
                <a href="#" className="forgot-password">Quên mật khẩu?</a>
              </div>

              <button type="submit" className="submit-btn" disabled={loading}>
                {loading ? '⏳ Đang xử lý...' : '🔑 Đăng nhập'}
              </button>
            </form>

            <div className="form-footer">
              <p>Chưa có tài khoản? <Link to="/register">Đăng ký ngay</Link></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ume-frontend/src/app/pages/login/login.component.ts
import { Component, NgZone, OnInit, AfterViewInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink, Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ToastrService } from 'ngx-toastr';
import { environment } from '../../../environments/environment';

declare const google: any;

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})
export class LoginComponent implements AfterViewInit, OnDestroy {
  email = '';
  password = '';
  showPassword = false;
  loading = false;
  private gsiInitialized = false;

  constructor(
    private authService: AuthService,
    private router: Router,
    private toastr: ToastrService,
    private ngZone: NgZone
  ) {}

  ngAfterViewInit(): void {
    this.loadGoogleScript();
  }

  ngOnDestroy(): void {
    // Cleanup if needed
  }

  private loadGoogleScript(): void {
    // Check if script already loaded
    if (typeof google !== 'undefined' && google.accounts) {
      this.initializeGSI();
      return;
    }

    // Check if script tag already exists
    const existing = document.querySelector('script[src*="accounts.google.com/gsi/client"]');
    if (existing) {
      existing.addEventListener('load', () => this.initializeGSI());
      // If already loaded
      if (typeof google !== 'undefined' && google.accounts) {
        this.initializeGSI();
      }
      return;
    }

    const script = document.createElement('script');
    script.src = 'https://accounts.google.com/gsi/client';
    script.async = true;
    script.defer = true;
    script.onload = () => this.initializeGSI();
    document.head.appendChild(script);
  }

  private initializeGSI(): void {
    if (this.gsiInitialized) return;
    this.gsiInitialized = true;

    try {
      google.accounts.id.initialize({
        client_id: environment.googleClientId,
        callback: (response: any) => this.handleGoogleCredential(response),
        auto_select: false,
        cancel_on_tap_outside: true
      });

      // Render the Google sign-in button
      const btnContainer = document.getElementById('google-signin-btn');
      if (btnContainer) {
        google.accounts.id.renderButton(btnContainer, {
          type: 'standard',
          theme: 'outline',
          size: 'large',
          text: 'signin_with',
          shape: 'rectangular',
          logo_alignment: 'left',
          width: '100%'
        });
      }
    } catch (e) {
      console.error('GSI init error:', e);
    }
  }

  private handleGoogleCredential(response: any): void {
    if (!response.credential) {
      this.ngZone.run(() => {
        this.toastr.error('Không nhận được thông tin từ Google');
      });
      return;
    }

    this.ngZone.run(() => {
      this.loading = true;
      this.authService.googleLogin(response.credential).subscribe({
        next: () => {
          this.toastr.success('Đăng nhập Google thành công!');
          this.router.navigate(['/']);
        },
        error: (err) => {
          this.loading = false;
          this.toastr.error(err.error?.message || 'Đăng nhập Google thất bại');
        }
      });
    });
  }

  togglePassword(): void {
    this.showPassword = !this.showPassword;
  }

  login(): void {
    if (!this.email || !this.password) {
      this.toastr.warning('Vui lòng nhập đầy đủ thông tin');
      return;
    }

    this.loading = true;
    this.authService.login({ email: this.email, password: this.password }).subscribe({
      next: () => {
        this.toastr.success('Đăng nhập thành công!');
        this.router.navigate(['/']);
      },
      error: (err) => {
        this.loading = false;
        this.toastr.error(err.error?.message || 'Đăng nhập thất bại. Vui lòng thử lại.');
      }
    });
  }

  googleLogin(): void {
    // Fallback: trigger One Tap prompt if rendered button not visible
    try {
      google.accounts.id.prompt();
    } catch (e) {
      this.toastr.error('Google Sign-In chưa sẵn sàng. Vui lòng thử lại.');
    }
  }

  facebookLogin(): void {
    this.toastr.info('Tính năng đăng nhập Facebook đang được phát triển.');
  }
}

<div class="login-page">
  <!-- Decorative paw prints -->
  <div class="paw-decorations">
    <span class="paw paw-1">🐾</span>
    <span class="paw paw-2">🐾</span>
    <span class="paw paw-3">🐾</span>
    <span class="paw paw-4">🐾</span>
    <span class="paw paw-5">🐾</span>
    <span class="paw paw-6">🐾</span>
  </div>

  <div class="login-container">
    <!-- Left - Illustration -->
    <div class="login-illustration">
      <div class="illustration-content">
        <div class="illustration-emoji">🐕‍🦺</div>
        <h2>Chào mừng trở lại!</h2>
        <p>Đăng nhập để đặt lịch chăm sóc thú cưng, mua sắm sản phẩm và quản lý thú cưng của bạn.</p>
        <div class="illustration-features">
          <div class="feature">
            <i class="fas fa-check-circle"></i>
            <span>Đặt lịch nhanh chóng</span>
          </div>
          <div class="feature">
            <i class="fas fa-check-circle"></i>
            <span>Theo dõi lịch hẹn</span>
          </div>
          <div class="feature">
            <i class="fas fa-check-circle"></i>
            <span>Ưu đãi độc quyền</span>
          </div>
          <div class="feature">
            <i class="fas fa-check-circle"></i>
            <span>Quản lý thú cưng</span>
          </div>
        </div>
        <div class="illustration-pets">
          <span>🐶</span>
          <span>🐱</span>
          <span>🐰</span>
          <span>🐹</span>
        </div>
      </div>
    </div>

    <!-- Right - Form -->
    <div class="login-form-section">
      <div class="form-wrapper">
        <div class="form-header">
          <a routerLink="/" class="form-logo">🐾 PetCare</a>
          <h1>Đăng nhập</h1>
          <p>Nhập thông tin tài khoản của bạn</p>
        </div>

        <!-- Social Login -->
        <div class="social-login">
          <div id="google-signin-btn" class="google-btn-container"></div>
          <button class="social-btn facebook-btn" (click)="facebookLogin()">
            <svg viewBox="0 0 24 24" width="20" height="20" fill="#1877F2">
              <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
            </svg>
            Facebook
          </button>
        </div>

        <div class="divider">
          <span>hoặc đăng nhập với email</span>
        </div>

        <!-- Login Form -->
        <form (ngSubmit)="login()" class="login-form">
          <div class="form-group">
            <label for="email">
              <i class="fas fa-envelope"></i> Email
            </label>
            <input
              type="email"
              id="email"
              [(ngModel)]="email"
              name="email"
              placeholder="Nhập email của bạn"
              required
              autocomplete="email"
            >
          </div>

          <div class="form-group">
            <label for="password">
              <i class="fas fa-lock"></i> Mật khẩu
            </label>
            <div class="password-input">
              <input
                [type]="showPassword ? 'text' : 'password'"
                id="password"
                [(ngModel)]="password"
                name="password"
                placeholder="Nhập mật khẩu"
                required
                autocomplete="current-password"
              >
              <button type="button" class="toggle-password" (click)="togglePassword()">
                <i [class]="showPassword ? 'fas fa-eye-slash' : 'fas fa-eye'"></i>
              </button>
            </div>
          </div>

          <div class="form-options">
            <label class="remember-me">
              <input type="checkbox"> Ghi nhớ đăng nhập
            </label>
            <a href="#" class="forgot-password">Quên mật khẩu?</a>
          </div>

          <button type="submit" class="submit-btn" [disabled]="loading">
            <span *ngIf="!loading">
              <i class="fas fa-sign-in-alt"></i> Đăng nhập
            </span>
            <span *ngIf="loading" class="spinner">
              <i class="fas fa-spinner fa-spin"></i> Đang xử lý...
            </span>
          </button>
        </form>

        <div class="form-footer">
          <p>Chưa có tài khoản? <a routerLink="/register">Đăng ký ngay</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
