// ume-frontend/src/app/pages/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';
import { ApiService } from '../../services/api.service';
import { SafeUrlPipe } from '../../pipes/safe-url.pipe';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule, FormsModule, SafeUrlPipe],
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.scss'
})
export class ContactComponent implements OnInit {
  contactForm = {
    fullName: '',
    phone: '',
    email: '',
    subject: '',
    message: ''
  };
  sending = false;

  // Settings from API
  settings: any = {
    address: '',
    phone: '',
    email: '',
    workingHours: '',
    facebook: '',
    instagram: '',
    tiktok: '',
    youtube: '',
    zalo: '',
    mapEmbedUrl: ''
  };

  subjects = [
    'Tư vấn dịch vụ',
    'Hỏi về sản phẩm',
    'Đặt lịch hẹn',
    'Khiếu nại / Góp ý',
    'Hợp tác kinh doanh',
    'Khác'
  ];

  constructor(
    private toastr: ToastrService,
    private api: ApiService
  ) {}

  ngOnInit(): void {
    this.loadSettings();
  }

  loadSettings(): void {
    this.api.getSettings().subscribe({
      next: (res: any) => {
        if (res.success) {
          this.settings = res.data;
        }
      }
    });
  }

  sendMessage(): void {
    if (!this.contactForm.fullName || !this.contactForm.phone || !this.contactForm.email || !this.contactForm.message) {
      this.toastr.warning('Vui lòng điền đầy đủ thông tin bắt buộc', 'Thông báo');
      return;
    }

    this.sending = true;

    // Simulate sending (can integrate with backend API later)
    setTimeout(() => {
      this.sending = false;
      this.toastr.success('Tin nhắn đã được gửi thành công! Chúng tôi sẽ phản hồi sớm nhất.', 'Thành công');
      this.contactForm = { fullName: '', phone: '', email: '', subject: '', message: '' };
    }, 1500);
  }
}

<div class="contact-page">
  <!-- Header -->
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-envelope"></i> Liên hệ với chúng tôi</h1>
      <p class="header-sub">Hãy để lại tin nhắn, chúng tôi sẽ phản hồi sớm nhất có thể!</p>
    </div>
  </div>

  <div class="container">
    <div class="contact-layout">
      <!-- Left: Contact Info -->
      <div class="contact-info-side">
        <div class="info-card">
          <h3><i class="fas fa-info-circle"></i> Thông tin liên hệ</h3>

          <div class="info-list">
            <div class="info-item">
              <div class="info-icon">
                <i class="fas fa-map-marker-alt"></i>
              </div>
              <div>
                <strong>Địa chỉ</strong>
                <p>{{ settings.address }}</p>
              </div>
            </div>

            <div class="info-item">
              <div class="info-icon">
                <i class="fas fa-phone-alt"></i>
              </div>
              <div>
                <strong>Điện thoại</strong>
                <p><a [href]="'tel:' + settings.phone">{{ settings.phone }}</a></p>
              </div>
            </div>

            <div class="info-item">
              <div class="info-icon">
                <i class="fas fa-envelope"></i>
              </div>
              <div>
                <strong>Email</strong>
                <p><a [href]="'mailto:' + settings.email">{{ settings.email }}</a></p>
              </div>
            </div>

            <div class="info-item">
              <div class="info-icon">
                <i class="fas fa-clock"></i>
              </div>
              <div>
                <strong>Giờ làm việc</strong>
                <p>{{ settings.workingHours }}</p>
              </div>
            </div>
          </div>

          <!-- Social -->
          <div class="social-section">
            <h4>Theo dõi chúng tôi</h4>
            <div class="social-icons">
              <a [href]="settings.facebook || '#'" class="social-icon facebook" title="Facebook" target="_blank" *ngIf="settings.facebook">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a [href]="settings.instagram || '#'" class="social-icon instagram" title="Instagram" target="_blank" *ngIf="settings.instagram">
                <i class="fab fa-instagram"></i>
              </a>
              <a [href]="settings.tiktok || '#'" class="social-icon tiktok" title="TikTok" target="_blank" *ngIf="settings.tiktok">
                <i class="fab fa-tiktok"></i>
              </a>
              <a [href]="settings.youtube || '#'" class="social-icon youtube" title="YouTube" target="_blank" *ngIf="settings.youtube">
                <i class="fab fa-youtube"></i>
              </a>
              <a [href]="settings.zalo || '#'" class="social-icon zalo" title="Zalo" target="_blank" *ngIf="settings.zalo">
                <i class="fas fa-comment-dots"></i>
              </a>
            </div>
          </div>

          <!-- Map -->
          <div class="map-placeholder" *ngIf="settings.mapEmbedUrl">
            <iframe
              [src]="settings.mapEmbedUrl | safeUrl"
              width="100%" height="180" style="border:0; border-radius: 12px;" allowfullscreen="" loading="lazy">
            </iframe>
          </div>
        </div>
      </div>

      <!-- Right: Contact Form -->
      <div class="contact-form-side">
        <div class="form-card">
          <h3><i class="fas fa-paper-plane"></i> Gửi tin nhắn</h3>
          <p class="form-subtitle">Điền thông tin và nội dung bên dưới để liên hệ với chúng tôi</p>

          <div class="form-grid">
            <div class="form-group">
              <label>Họ và tên <span class="required">*</span></label>
              <input type="text" [(ngModel)]="contactForm.fullName" placeholder="Nhập họ tên của bạn">
            </div>
            <div class="form-group">
              <label>Số điện thoại <span class="required">*</span></label>
              <input type="tel" [(ngModel)]="contactForm.phone" placeholder="Nhập số điện thoại">
            </div>
            <div class="form-group full">
              <label>Email <span class="required">*</span></label>
              <input type="email" [(ngModel)]="contactForm.email" placeholder="Nhập email của bạn">
            </div>
            <div class="form-group full">
              <label>Chủ đề</label>
              <select [(ngModel)]="contactForm.subject">
                <option value="">-- Chọn chủ đề --</option>
                <option *ngFor="let s of subjects" [value]="s">{{ s }}</option>
              </select>
            </div>
            <div class="form-group full">
              <label>Nội dung <span class="required">*</span></label>
              <textarea [(ngModel)]="contactForm.message" placeholder="Nhập nội dung tin nhắn..." rows="5"></textarea>
            </div>
          </div>

          <button class="btn-send" (click)="sendMessage()" [disabled]="sending">
            <i class="fas" [class.fa-paper-plane]="!sending" [class.fa-spinner]="sending" [class.fa-spin]="sending"></i>
            {{ sending ? 'Đang gửi...' : 'Gửi tin nhắn' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

// ume-react/src/pages/contact/Contact.tsx
import { useState, useEffect } from 'react';
import { settingsApi } from '../../services/api';
import toast from 'react-hot-toast';
import api from '../../services/api';
import './Contact.scss';

const subjects = [
  'Tư vấn dịch vụ', 'Hỏi về sản phẩm', 'Đặt lịch hẹn',
  'Khiếu nại / Góp ý', 'Hợp tác kinh doanh', 'Khác',
];

export default function Contact() {
  const [settings, setSettings] = useState<any>({});
  const [form, setForm] = useState({ fullName: '', phone: '', email: '', subject: '', message: '' });
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    settingsApi.get().then(res => setSettings(res.data?.data || {})).catch(() => {});
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setForm(f => ({ ...f, [e.target.name]: e.target.value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.fullName || !form.phone || !form.email || !form.subject || !form.message) {
      toast.error('Vui lòng điền đầy đủ thông tin'); return;
    }
    setLoading(true);
    try {
      await api.post('/contacts', form);
      setSubmitted(true);
      toast.success('Gửi liên hệ thành công!');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Gửi thất bại');
    } finally { setLoading(false); }
  };

  const resetForm = () => {
    setForm({ fullName: '', phone: '', email: '', subject: '', message: '' });
    setSubmitted(false);
  };

  return (
    <div className="contact-page">
      <div className="page-header">
        <div className="container">
          <h1>📞 Liên hệ</h1>
          <p>Chúng tôi luôn sẵn sàng hỗ trợ bạn</p>
        </div>
      </div>

      <div className="container">
        <div className="contact-grid">
          {/* Left: Info */}
          <div className="contact-info">
            <h2>Thông tin liên hệ</h2>

            <div className="info-items">
              {settings.address && (
                <div className="info-item"><span className="info-icon">📍</span><div><h4>Địa chỉ</h4><p>{settings.address}</p></div></div>
              )}
              {settings.phone && (
                <div className="info-item"><span className="info-icon">📱</span><div><h4>Điện thoại</h4><p>{settings.phone}</p></div></div>
              )}
              {settings.email && (
                <div className="info-item"><span className="info-icon">✉️</span><div><h4>Email</h4><p>{settings.email}</p></div></div>
              )}
              {settings.workingHours && (
                <div className="info-item"><span className="info-icon">🕐</span><div><h4>Giờ làm việc</h4><p>{settings.workingHours}</p></div></div>
              )}
            </div>

            <div className="social-links">
              <h4>Kết nối với chúng tôi</h4>
              <div className="social-icons">
                {settings.facebook && <a href={settings.facebook} target="_blank" rel="noopener noreferrer" className="social-icon facebook">f</a>}
                {settings.instagram && <a href={settings.instagram} target="_blank" rel="noopener noreferrer" className="social-icon instagram">📸</a>}
                {settings.tiktok && <a href={settings.tiktok} target="_blank" rel="noopener noreferrer" className="social-icon tiktok">🎵</a>}
                {settings.youtube && <a href={settings.youtube} target="_blank" rel="noopener noreferrer" className="social-icon youtube">▶</a>}
                {settings.zalo && <a href={settings.zalo} target="_blank" rel="noopener noreferrer" className="social-icon zalo">Z</a>}
              </div>
            </div>

            {settings.mapEmbedUrl && (
              <div className="map-section">
                <iframe src={settings.mapEmbedUrl} title="Bản đồ" allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" />
              </div>
            )}
          </div>

          {/* Right: Form */}
          <div className="contact-form-section">
            {!submitted ? (
              <>
                <h2>Gửi tin nhắn</h2>
                <form onSubmit={handleSubmit}>
                  <div className="form-group">
                    <label>Họ và tên *</label>
                    <input name="fullName" value={form.fullName} onChange={handleChange} placeholder="VD: Nguyễn Văn A" />
                  </div>
                  <div className="form-row">
                    <div className="form-group">
                      <label>Số điện thoại *</label>
                      <input name="phone" value={form.phone} onChange={handleChange} placeholder="VD: 0901234567" />
                    </div>
                    <div className="form-group">
                      <label>Email *</label>
                      <input name="email" type="email" value={form.email} onChange={handleChange} placeholder="VD: email@example.com" />
                    </div>
                  </div>
                  <div className="form-group">
                    <label>Chủ đề *</label>
                    <select name="subject" value={form.subject} onChange={handleChange}>
                      <option value="">-- Chọn chủ đề --</option>
                      {subjects.map(s => <option key={s} value={s}>{s}</option>)}
                    </select>
                  </div>
                  <div className="form-group">
                    <label>Nội dung *</label>
                    <textarea name="message" value={form.message} onChange={handleChange} rows={5} placeholder="Nhập nội dung tin nhắn..." />
                  </div>
                  <button type="submit" className="btn-send" disabled={loading}>{loading ? '⏳ Đang gửi...' : '📩 Gửi tin nhắn'}</button>
                </form>
              </>
            ) : (
              <div className="success-panel">
                <div className="success-icon">✅</div>
                <h2>Cảm ơn bạn!</h2>
                <p>Tin nhắn của bạn đã được gửi thành công. Chúng tôi sẽ phản hồi trong thời gian sớm nhất.</p>
                <button className="btn-new" onClick={resetForm}>📝 Gửi tin nhắn khác</button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
