// ume-react/src/pages/checkout/Checkout.tsx
import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useCart } from '../../contexts/CartContext';
import { useAuth } from '../../contexts/AuthContext';
import { orderApi, settingsApi, promotionApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import toast from 'react-hot-toast';
import './Checkout.scss';

const formatPrice = (price: number) =>
  new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);

export default function Checkout() {
  const navigate = useNavigate();
  const { items, totalAmount, clearCart } = useCart();
  const { user } = useAuth();

  const [settings, setSettings] = useState<any>({});
  const [shippingMethod, setShippingMethod] = useState('standard');
  const [shippingFee, setShippingFee] = useState(30000);
  const [paymentMethod, setPaymentMethod] = useState('COD');
  const [notes, setNotes] = useState('');
  const [promoCode, setPromoCode] = useState('');
  const [discount, setDiscount] = useState(0);
  const [promoApplied, setPromoApplied] = useState(false);
  const [promoName, setPromoName] = useState('');
  const [applyingPromo, setApplyingPromo] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const [shippingAddress, setShippingAddress] = useState({
    fullName: '', phone: '', email: '', address: '', ward: '', district: '', city: ''
  });

  useEffect(() => {
    if (items.length === 0) { navigate('/cart'); return; }
    settingsApi.get().then(res => {
      const s = res.data?.data || res.data;
      setSettings(s);
      setShippingFee(s.shippingStandardPrice || 30000);
      if (s.codEnabled === false && s.bankTransferEnabled !== false) setPaymentMethod('BankTransfer');
    }).catch(() => {});
    if (user) {
      setShippingAddress({
        fullName: user.fullName || '', phone: user.phoneNumber || '', email: user.email || '',
        address: user.address?.street || '', ward: user.address?.ward || '',
        district: user.address?.district || '', city: user.address?.city || ''
      });
    }
  }, []);

  const standardPrice = settings.shippingStandardPrice || 30000;
  const expressPrice = settings.shippingExpressPrice || 50000;
  const total = totalAmount + shippingFee - discount;

  const selectShipping = (method: string) => {
    setShippingMethod(method);
    setShippingFee(method === 'express' ? expressPrice : standardPrice);
  };

  const applyPromo = async () => {
    if (!promoCode.trim()) { toast.error('Vui lòng nhập mã khuyến mãi'); return; }
    setApplyingPromo(true);
    try {
      const res = await promotionApi.validate(promoCode, totalAmount);
      if (res.data?.success) {
        const d = res.data.data;
        if (d.promotion?.type === 'FreeShipping') {
          setDiscount(shippingFee);
          toast.success('Áp dụng miễn phí vận chuyển thành công!');
        } else {
          setDiscount(d.discount || 0);
          toast.success(`Giảm ${formatPrice(d.discount || 0)}`);
        }
        setPromoApplied(true);
        setPromoName(d.promotion?.name || promoCode);
      }
    } catch (err: any) {
      setDiscount(0); setPromoApplied(false);
      toast.error(err.response?.data?.message || 'Mã không hợp lệ');
    } finally { setApplyingPromo(false); }
  };

  const removePromo = () => {
    setPromoCode(''); setDiscount(0); setPromoApplied(false); setPromoName('');
    toast('Đã hủy mã khuyến mãi', { icon: 'ℹ️' });
  };

  const getItemPrice = (item: any) =>
    item.itemType === 'pet' ? (item.product.listingPrice || 0) : item.product.price;

  const isFormValid = () => !!(shippingAddress.fullName && shippingAddress.phone && shippingAddress.email && shippingAddress.address);

  const placeOrder = async () => {
    if (!isFormValid()) { toast.error('Vui lòng điền đầy đủ thông tin giao hàng'); return; }
    setSubmitting(true);
    try {
      const orderData: any = {
        items: items.map(item => item.itemType === 'pet'
          ? { petId: item.product._id, quantity: 1 }
          : { productId: item.product._id, quantity: item.quantity }
        ),
        shippingAddress, shippingFee, paymentMethod, notes
      };
      if (promoApplied && promoCode) orderData.promotionCode = promoCode;
      const res = await orderApi.create(orderData);
      const order = res.data?.data || res.data;
      clearCart();
      sessionStorage.setItem('newOrder', JSON.stringify({
        id: order._id, code: order.orderCode, total: order.total,
        items: order.items, shippingAddress: order.shippingAddress, paymentMethod: order.paymentMethod
      }));
      navigate('/checkout-success');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Đặt hàng thất bại');
    } finally { setSubmitting(false); }
  };

  const updateAddress = (field: string, value: string) => {
    setShippingAddress(prev => ({ ...prev, [field]: value }));
  };

  return (
    <div className="checkout-page">
      <div className="page-header">
        <div className="container"><h1>💳 Thanh toán</h1></div>
      </div>

      <div className="container">
        <div className="checkout-layout">
          <div className="checkout-form">
            {/* Shipping Info */}
            <div className="form-section">
              <h3>📍 Thông tin giao hàng</h3>
              <div className="form-grid">
                <div className="form-group full">
                  <label>Họ tên *</label>
                  <input type="text" value={shippingAddress.fullName} onChange={e => updateAddress('fullName', e.target.value)} placeholder="Nhập họ tên" />
                </div>
                <div className="form-group">
                  <label>Số điện thoại *</label>
                  <input type="tel" value={shippingAddress.phone} onChange={e => updateAddress('phone', e.target.value)} placeholder="Nhập số điện thoại" />
                </div>
                <div className="form-group">
                  <label>Email *</label>
                  <input type="email" value={shippingAddress.email} onChange={e => updateAddress('email', e.target.value)} placeholder="Nhập email" />
                </div>
                <div className="form-group full">
                  <label>Địa chỉ giao hàng *</label>
                  <textarea value={shippingAddress.address} onChange={e => updateAddress('address', e.target.value)} placeholder="Nhập địa chỉ chi tiết" rows={3} />
                </div>
              </div>
            </div>

            {/* Notes */}
            <div className="form-section">
              <h3>📝 Ghi chú</h3>
              <textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Ghi chú cho người bán (không bắt buộc)" rows={3} />
            </div>

            {/* Shipping Method */}
            <div className="form-section">
              <h3>🚚 Phương thức giao hàng</h3>
              <div className="shipping-options">
                <label className={`shipping-option ${shippingMethod === 'standard' ? 'selected' : ''}`} onClick={() => selectShipping('standard')}>
                  <input type="radio" name="shipping" checked={shippingMethod === 'standard'} readOnly />
                  <div className="shipping-content">
                    <div><strong>Giao hàng tiêu chuẩn</strong><p>Nhận hàng trong 3 - 4 ngày</p></div>
                  </div>
                  <span className="shipping-price">{formatPrice(standardPrice)}</span>
                </label>
                <label className={`shipping-option ${shippingMethod === 'express' ? 'selected' : ''}`} onClick={() => selectShipping('express')}>
                  <input type="radio" name="shipping" checked={shippingMethod === 'express'} readOnly />
                  <div className="shipping-content">
                    <div><strong>Giao hàng hỏa tốc</strong><p>Nhận hàng trong 1 - 2 ngày</p></div>
                  </div>
                  <span className="shipping-price">{formatPrice(expressPrice)}</span>
                </label>
              </div>
            </div>

            {/* Payment */}
            <div className="form-section">
              <h3>💰 Phương thức thanh toán</h3>
              <div className="payment-options">
                {settings.codEnabled !== false && (
                  <label className={`payment-option ${paymentMethod === 'COD' ? 'selected' : ''}`}>
                    <input type="radio" name="payment" value="COD" checked={paymentMethod === 'COD'} onChange={() => setPaymentMethod('COD')} />
                    <div><strong>💵 Thanh toán khi nhận hàng (COD)</strong><p>{settings.codDescription || 'Thanh toán bằng tiền mặt khi nhận hàng'}</p></div>
                  </label>
                )}
                {settings.bankTransferEnabled !== false && (
                  <label className={`payment-option ${paymentMethod === 'BankTransfer' ? 'selected' : ''}`}>
                    <input type="radio" name="payment" value="BankTransfer" checked={paymentMethod === 'BankTransfer'} onChange={() => setPaymentMethod('BankTransfer')} />
                    <div><strong>🏦 Chuyển khoản ngân hàng</strong><p>{settings.bankDescription || 'Chuyển khoản trước khi giao hàng'}</p></div>
                  </label>
                )}
              </div>
              {paymentMethod === 'BankTransfer' && settings.bankName && (
                <div className="bank-transfer-info">
                  <h4>🏦 Thông tin chuyển khoản</h4>
                  <div className="bank-detail-row"><span>Ngân hàng:</span><strong>{settings.bankName}</strong></div>
                  {settings.bankAccountNumber && <div className="bank-detail-row"><span>Số tài khoản:</span><strong>{settings.bankAccountNumber}</strong></div>}
                  {settings.bankAccountHolder && <div className="bank-detail-row"><span>Chủ tài khoản:</span><strong>{settings.bankAccountHolder}</strong></div>}
                  {settings.bankQrImage && <img src={getImageUrl(settings.bankQrImage)} alt="QR" className="bank-qr" />}
                </div>
              )}
            </div>
          </div>

          {/* Order Summary */}
          <div className="order-summary">
            <h3>Đơn hàng của bạn</h3>
            <div className="summary-items">
              {items.map(item => (
                <div className="summary-item" key={item.product._id + (item.itemType || '')}>
                  <div className="item-info">
                    <img src={getImageUrl(item.product.imageUrl)} alt={item.product.name} />
                    <div>
                      {item.itemType === 'pet' && <span className="pet-label">🐾 Thú cưng</span>}
                      <span className="item-name">{item.product.name}</span>
                      <span className="item-qty">x{item.quantity}</span>
                    </div>
                  </div>
                  <span className="item-price">{formatPrice(getItemPrice(item) * item.quantity)}</span>
                </div>
              ))}
            </div>
            <div className="summary-divider"></div>
            <div className="summary-row"><span>Tạm tính</span><span>{formatPrice(totalAmount)}</span></div>
            <div className="summary-row"><span>Phí vận chuyển</span><span>{formatPrice(shippingFee)}</span></div>

            {/* Promo */}
            <div className="promo-section">
              {!promoApplied ? (
                <div className="promo-input">
                  <input type="text" value={promoCode} onChange={e => setPromoCode(e.target.value)} placeholder="Mã khuyến mãi..." disabled={applyingPromo} />
                  <button onClick={applyPromo} disabled={applyingPromo}>{applyingPromo ? '...' : 'Áp dụng'}</button>
                </div>
              ) : (
                <div className="promo-applied">
                  <span>✅ {promoCode.toUpperCase()} - {promoName}</span>
                  <button onClick={removePromo}>✕</button>
                </div>
              )}
            </div>

            {discount > 0 && (
              <div className="summary-row discount"><span>Giảm giá</span><span>-{formatPrice(discount)}</span></div>
            )}
            <div className="summary-divider"></div>
            <div className="summary-row total"><span>Tổng cộng</span><span>{formatPrice(total)}</span></div>

            <button className="btn-place-order" onClick={placeOrder} disabled={submitting || !isFormValid()}>
              {submitting ? '⏳ Đang xử lý...' : '✅ Đặt hàng'}
            </button>
            <Link to="/cart" className="back-to-cart">← Quay lại giỏ hàng</Link>
          </div>
        </div>
      </div>
    </div>
  );
}

// ume-frontend/src/app/pages/checkout/checkout.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { CartService, CartItem } from '../../services/cart.service';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-checkout',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './checkout.component.html',
  styleUrl: './checkout.component.scss'
})
export class CheckoutComponent implements OnInit {
  cartItems: CartItem[] = [];
  shippingFee = 30000;
  submitting = false;
  shippingMethod = 'standard';
  sameAsUser = true;

  // Settings from admin
  settings: any = {};

  // Shipping address
  shippingAddress = {
    fullName: '',
    phone: '',
    email: '',
    address: '',
    ward: '',
    district: '',
    city: ''
  };

  paymentMethod = 'COD';
  notes = '';
  promoCode = '';
  discount = 0;
  promoApplied = false;
  promoName = '';
  applyingPromo = false;

  constructor(
    public cartService: CartService,
    private apiService: ApiService,
    private authService: AuthService,
    private toastr: ToastrService,
    private router: Router
  ) {}

  getImg(path: string): string { return this.apiService.getImageUrl(path); }

  ngOnInit(): void {
    this.cartItems = this.cartService.items;
    if (this.cartItems.length === 0) {
      this.router.navigate(['/cart']);
      return;
    }

    // Load settings
    this.apiService.getSettings().subscribe({
      next: (res: any) => {
        this.settings = res.data || res;
        // Apply shipping prices from settings
        this.shippingFee = this.shippingMethod === 'express'
          ? (this.settings.shippingExpressPrice || 50000)
          : (this.settings.shippingStandardPrice || 30000);
        // Set default payment method
        if (this.settings.codEnabled === false && this.settings.bankTransferEnabled !== false) {
          this.paymentMethod = 'BankTransfer';
        }
      },
      error: () => {}
    });

    // Pre-fill from user profile
    const user = this.authService.currentUser;
    if (user) {
      this.shippingAddress.fullName = user.fullName || '';
      this.shippingAddress.phone = user.phoneNumber || '';
      this.shippingAddress.email = user.email || '';
      if (user.address) {
        this.shippingAddress.address = user.address.street || '';
        this.shippingAddress.ward = user.address.ward || '';
        this.shippingAddress.district = user.address.district || '';
        this.shippingAddress.city = user.address.city || '';
      }
    }
  }

  get standardPrice(): number {
    return this.settings.shippingStandardPrice || 30000;
  }
  get expressPrice(): number {
    return this.settings.shippingExpressPrice || 50000;
  }
  get freeShipStandard(): number {
    return this.settings.freeShipStandardThreshold || 500000;
  }
  get freeShipExpress(): number {
    return this.settings.freeShipExpressThreshold || 1000000;
  }

  get shippingPolicyLines(): string[] {
    if (this.settings.shippingPolicy) {
      return this.settings.shippingPolicy.split('\n').filter((l: string) => l.trim());
    }
    return [];
  }

  get subtotal(): number {
    return this.cartService.totalAmount;
  }

  get total(): number {
    return this.subtotal + this.shippingFee - this.discount;
  }

  selectShippingMethod(method: string): void {
    this.shippingMethod = method;
    this.shippingFee = method === 'express' ? this.expressPrice : this.standardPrice;
  }

  applyPromoCode(): void {
    if (!this.promoCode.trim()) {
      this.toastr.warning('Vui lòng nhập mã khuyến mãi');
      return;
    }
    this.applyingPromo = true;
    this.apiService.validatePromoCode(this.promoCode, this.subtotal).subscribe({
      next: (res: any) => {
        this.applyingPromo = false;
        if (res.success) {
          this.discount = res.data.discount || 0;
          this.promoApplied = true;
          this.promoName = res.data.promotion?.name || this.promoCode;
          if (res.data.promotion?.type === 'FreeShipping') {
            this.discount = this.shippingFee;
            this.toastr.success('Áp dụng miễn phí vận chuyển thành công!');
          } else {
            this.toastr.success(`Áp dụng mã "${this.promoCode.toUpperCase()}" thành công! Giảm ${this.formatPrice(this.discount)}`);
          }
        }
      },
      error: (err: any) => {
        this.applyingPromo = false;
        this.discount = 0;
        this.promoApplied = false;
        this.promoName = '';
        this.toastr.error(err.error?.message || 'Mã khuyến mãi không hợp lệ');
      }
    });
  }

  removePromoCode(): void {
    this.promoCode = '';
    this.discount = 0;
    this.promoApplied = false;
    this.promoName = '';
    this.toastr.info('Đã hủy mã khuyến mãi');
  }

  getItemPrice(item: CartItem): number {
    return item.itemType === 'pet' ? (item.product.listingPrice || 0) : item.product.price;
  }

  isFormValid(): boolean {
    return !!(
      this.shippingAddress.fullName &&
      this.shippingAddress.phone &&
      this.shippingAddress.email &&
      this.shippingAddress.address
    );
  }

  placeOrder(): void {
    if (!this.isFormValid()) {
      this.toastr.warning('Vui lòng điền đầy đủ thông tin giao hàng', 'Thông báo');
      return;
    }

    this.submitting = true;
    const orderData: any = {
      items: this.cartItems.map(item => {
        if (item.itemType === 'pet') {
          return { petId: item.product._id, quantity: 1 };
        }
        return { productId: item.product._id, quantity: item.quantity };
      }),
      shippingAddress: this.shippingAddress,
      shippingFee: this.shippingFee,
      paymentMethod: this.paymentMethod,
      notes: this.notes
    };
    if (this.promoApplied && this.promoCode) {
      orderData.promotionCode = this.promoCode;
    }

    this.apiService.createOrder(orderData).subscribe({
      next: (res: any) => {
        this.submitting = false;
        const order = res.data || res;
        this.cartService.clearCart();
        
        // Store order data and redirect to success page
        sessionStorage.setItem('newOrder', JSON.stringify({
          id: order._id,
          code: order.orderCode,
          total: order.total,
          items: order.items,
          shippingAddress: order.shippingAddress,
          paymentMethod: order.paymentMethod
        }));
        
        this.router.navigate(['/checkout-success']);
      },
      error: (err: any) => {
        this.submitting = false;
        this.toastr.error(err.error?.message || 'Đặt hàng thất bại', 'Lỗi');
      }
    });
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }
}

<div class="checkout-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-credit-card"></i> Thanh toán</h1>
    </div>
  </div>

  <div class="container">
    <div class="checkout-layout">
      <!-- Shipping Form -->
      <div class="checkout-form">
        <div class="form-section">
          <h3><i class="fas fa-map-marker-alt"></i> Thông tin giao hàng</h3>
          <label class="same-as-user">
            <input type="checkbox" [(ngModel)]="sameAsUser">
            Người nhận giống người đặt hàng
          </label>
          <div class="form-grid">
            <div class="form-group full">
              <label>Họ tên *</label>
              <input type="text" [(ngModel)]="shippingAddress.fullName" placeholder="Nhập họ tên">
            </div>
            <div class="form-group">
              <label>Số điện thoại *</label>
              <input type="tel" [(ngModel)]="shippingAddress.phone" placeholder="Nhập số điện thoại">
            </div>
            <div class="form-group">
              <label>Email *</label>
              <input type="email" [(ngModel)]="shippingAddress.email" placeholder="Nhập email">
            </div>
            <div class="form-group full">
              <label>Địa chỉ giao hàng *</label>
              <textarea [(ngModel)]="shippingAddress.address" placeholder="Nhập địa chỉ chi tiết (số nhà, đường, phường/xã, quận/huyện, tỉnh/thành phố)" rows="3"></textarea>
            </div>
          </div>
        </div>

        <div class="form-section">
          <h3><i class="fas fa-sticky-note"></i> Ghi chú</h3>
          <textarea [(ngModel)]="notes" placeholder="Ghi chú cho người bán (không bắt buộc)" rows="3"></textarea>
        </div>

        <div class="form-section">
          <h3><i class="fas fa-truck"></i> Phương thức giao hàng</h3>
          <div class="shipping-options">
            <label class="shipping-option" [class.selected]="shippingMethod === 'standard'" (click)="selectShippingMethod('standard')">
              <input type="radio" name="shipping" value="standard" [(ngModel)]="shippingMethod">
              <div class="shipping-content">
                <i class="fas fa-truck"></i>
                <div>
                  <strong>Giao hàng tiêu chuẩn</strong>
                  <p>Nhận hàng trong 3 - 4 ngày làm việc</p>
                </div>
              </div>
              <span class="shipping-price">{{ formatPrice(standardPrice) }}</span>
            </label>
            <label class="shipping-option" [class.selected]="shippingMethod === 'express'" (click)="selectShippingMethod('express')">
              <input type="radio" name="shipping" value="express" [(ngModel)]="shippingMethod">
              <div class="shipping-content">
                <i class="fas fa-bolt"></i>
                <div>
                  <strong>Giao hàng hỏa tốc</strong>
                  <p>Nhận hàng trong ngày hoặc 1 - 2 ngày</p>
                </div>
              </div>
              <span class="shipping-price express">{{ formatPrice(expressPrice) }}</span>
            </label>
          </div>

          <!-- Chính sách giao hàng -->
          <div class="shipping-policy">
            <h4><i class="fas fa-info-circle"></i> Chính sách giao hàng</h4>
            <ul *ngIf="shippingPolicyLines.length > 0">
              <li *ngFor="let line of shippingPolicyLines">{{ line }}</li>
            </ul>
            <ul *ngIf="shippingPolicyLines.length === 0">
              <li><strong>Giao hàng tiêu chuẩn ({{ formatPrice(standardPrice) }}):</strong> Đơn hàng được xử lý trong 24h và nhận hàng trong 3 - 4 ngày làm việc.</li>
              <li><strong>Giao hàng hỏa tốc ({{ formatPrice(expressPrice) }}):</strong> Đơn hàng được ưu tiên xử lý ngay, nhận hàng trong ngày hoặc 1 - 2 ngày.</li>
              <li>🐾 Đơn hàng có thú cưng sẽ được giao hàng bởi nhân viên chuyên trách.</li>
              <li>Miễn phí giao hàng cho đơn từ <strong>{{ formatPrice(freeShipStandard) }}</strong> (tiêu chuẩn) hoặc <strong>{{ formatPrice(freeShipExpress) }}</strong> (hỏa tốc).</li>
              <li *ngIf="settings.returnPolicy">{{ settings.returnPolicy }}</li>
              <li *ngIf="!settings.returnPolicy">Hỗ trợ đổi trả trong <strong>7 ngày</strong> nếu sản phẩm lỗi từ nhà sản xuất.</li>
            </ul>
          </div>
        </div>

        <div class="form-section">
          <h3><i class="fas fa-wallet"></i> Phương thức thanh toán</h3>
          <div class="payment-options">
            <label class="payment-option" [class.selected]="paymentMethod === 'COD'" *ngIf="settings.codEnabled !== false">
              <input type="radio" name="payment" value="COD" [(ngModel)]="paymentMethod">
              <div class="payment-content">
                <i class="fas fa-money-bill-wave"></i>
                <div>
                  <strong>Thanh toán khi nhận hàng (COD)</strong>
                  <p>{{ settings.codDescription || 'Thanh toán bằng tiền mặt khi nhận hàng' }}</p>
                </div>
              </div>
            </label>
            <label class="payment-option" [class.selected]="paymentMethod === 'BankTransfer'" *ngIf="settings.bankTransferEnabled !== false">
              <input type="radio" name="payment" value="BankTransfer" [(ngModel)]="paymentMethod">
              <div class="payment-content">
                <i class="fas fa-university"></i>
                <div>
                  <strong>Chuyển khoản ngân hàng</strong>
                  <p>{{ settings.bankDescription || 'Chuyển khoản trước khi giao hàng' }}</p>
                </div>
              </div>
            </label>
          </div>

          <!-- Bank Transfer Details with QR -->
          <div class="bank-transfer-info" *ngIf="paymentMethod === 'BankTransfer' && (settings.bankName || settings.bankQrImage)">
            <div class="bank-details-grid">
              <div class="bank-details" *ngIf="settings.bankName">
                <h4><i class="fas fa-university"></i> Thông tin chuyển khoản</h4>
                <div class="bank-detail-row">
                  <span class="detail-label">Ngân hàng:</span>
                  <span class="detail-value">{{ settings.bankName }}</span>
                </div>
                <div class="bank-detail-row" *ngIf="settings.bankAccountNumber">
                  <span class="detail-label">Số tài khoản:</span>
                  <span class="detail-value account-number">{{ settings.bankAccountNumber }}</span>
                </div>
                <div class="bank-detail-row" *ngIf="settings.bankAccountHolder">
                  <span class="detail-label">Chủ tài khoản:</span>
                  <span class="detail-value">{{ settings.bankAccountHolder }}</span>
                </div>
                <div class="bank-detail-row" *ngIf="settings.bankBranch">
                  <span class="detail-label">Chi nhánh:</span>
                  <span class="detail-value">{{ settings.bankBranch }}</span>
                </div>
                <div class="bank-note">
                  <i class="fas fa-info-circle"></i>
                  Vui lòng ghi nội dung chuyển khoản là <strong>mã đơn hàng</strong> sau khi đặt hàng.
                </div>
              </div>
              <div class="bank-qr" *ngIf="settings.bankQrImage">
                <h4><i class="fas fa-qrcode"></i> Quét mã QR để thanh toán</h4>
                <img [src]="getImg(settings.bankQrImage)" alt="QR Code thanh toán">
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Order Summary -->
      <div class="order-summary">
        <h3>Đơn hàng của bạn</h3>
        <div class="summary-items">
          <div class="summary-item" *ngFor="let item of cartItems">
            <div class="item-info">
              <img [src]="getImg(item.product.imageUrl || item.product.mainImage)" [alt]="item.product.name"
                   onerror="this.src='assets/images/no-image.svg'">
              <div>
                <span class="pet-label" *ngIf="item.itemType === 'pet'"><i class="fas fa-paw"></i> Thú cưng</span>
                <span class="item-name">{{ item.product.name }}</span>
                <span class="item-qty">x{{ item.quantity }}</span>
              </div>
            </div>
            <span class="item-price">{{ formatPrice(getItemPrice(item) * item.quantity) }}</span>
          </div>
        </div>
        <div class="summary-divider"></div>
        <div class="summary-row">
          <span>Tạm tính</span>
          <span>{{ formatPrice(subtotal) }}</span>
        </div>
        <div class="summary-row">
          <span>Phí vận chuyển: <small>({{ shippingMethod === 'express' ? 'Giao hàng hỏa tốc' : 'Giao hàng tiêu chuẩn' }})</small></span>
          <span>{{ formatPrice(shippingFee) }}</span>
        </div>
        <div class="promo-section">
          <div class="promo-input" *ngIf="!promoApplied">
            <input type="text" [(ngModel)]="promoCode" placeholder="Nhập mã khuyến mãi..." [disabled]="applyingPromo">
            <button (click)="applyPromoCode()" class="btn-apply" [disabled]="applyingPromo">
              <i class="fas fa-spinner fa-spin" *ngIf="applyingPromo"></i>
              {{ applyingPromo ? '...' : 'Áp dụng' }}
            </button>
          </div>
          <div class="promo-applied" *ngIf="promoApplied">
            <div class="promo-info">
              <i class="fas fa-check-circle"></i>
              <span>Mã <strong>{{ promoCode | uppercase }}</strong> - {{ promoName }}</span>
            </div>
            <button class="btn-remove-promo" (click)="removePromoCode()">
              <i class="fas fa-times"></i> Hủy
            </button>
          </div>
        </div>
        <div class="summary-row discount" *ngIf="discount > 0">
          <span>Giảm giá</span>
          <span class="discount-amount">-{{ formatPrice(discount) }}</span>
        </div>
        <div class="summary-divider"></div>
        <div class="summary-row total">
          <span>Tổng cộng</span>
          <span>{{ formatPrice(total) }}</span>
        </div>
        <button class="btn-place-order" (click)="placeOrder()"
                [disabled]="submitting || !isFormValid()">
          <i class="fas" [class.fa-check]="!submitting" [class.fa-spinner]="submitting" [class.fa-spin]="submitting"></i>
          {{ submitting ? 'Đang xử lý...' : 'Đặt hàng' }}
        </button>
        <a routerLink="/cart" class="back-to-cart">
          <i class="fas fa-arrow-left"></i> Quay lại giỏ hàng
        </a>
      </div>
    </div>
  </div>
</div>
