// ume-frontend/src/app/pages/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ApiService } from '../../services/api.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './profile.component.html',
  styleUrl: './profile.component.scss'
})
export class ProfileComponent implements OnInit {
  profile: any = {};
  loading = true;
  saving = false;

  // Tabs
  activeTab = 'info'; // info | password | orders | appointments | pets

  // Stats
  orderCount = 0;
  appointmentCount = 0;
  petCount = 0;

  // Change password
  currentPassword = '';
  newPassword = '';
  confirmPassword = '';
  changingPassword = false;

  avatarPreview: string | null = null;
  selectedAvatarFile: File | null = null;

  // Orders, appointments, pets lists for tabs
  orders: any[] = [];
  appointments: any[] = [];
  pets: any[] = [];
  loadingOrders = false;
  loadingAppointments = false;
  loadingPets = false;

  constructor(
    private authService: AuthService,
    private apiService: ApiService,
    private toastr: ToastrService
  ) {}

  getImg(path: string): string { return this.apiService.getImageUrl(path); }

  ngOnInit(): void {
    this.loadProfile();
    this.loadStats();
  }

  loadProfile(): void {
    this.loading = true;
    this.authService.getProfile().subscribe({
      next: (res: any) => {
        this.profile = res.data || res;
        if (!this.profile.address) this.profile.address = {};
        this.loading = false;
      },
      error: () => { this.loading = false; }
    });
  }

  loadStats(): void {
    this.apiService.getMyOrders().subscribe({
      next: (res: any) => {
        const data = res.data || res;
        this.orderCount = Array.isArray(data) ? data.length : (data.orders?.length || 0);
      }
    });
    this.apiService.getMyAppointments().subscribe({
      next: (res: any) => {
        const data = res.data || res;
        this.appointmentCount = Array.isArray(data) ? data.length : (data.appointments?.length || 0);
      }
    });
    this.apiService.getMyPets().subscribe({
      next: (res: any) => {
        const data = res.data || res;
        this.petCount = Array.isArray(data) ? data.length : 0;
      }
    });
  }

  switchTab(tab: string): void {
    this.activeTab = tab;
    if (tab === 'orders' && this.orders.length === 0) this.loadOrders();
    if (tab === 'appointments' && this.appointments.length === 0) this.loadAppointments();
    if (tab === 'pets' && this.pets.length === 0) this.loadPets();
  }

  loadOrders(): void {
    this.loadingOrders = true;
    this.apiService.getMyOrders().subscribe({
      next: (res: any) => {
        const data = res.data || res;
        this.orders = Array.isArray(data) ? data : (data.orders || []);
        this.loadingOrders = false;
      },
      error: () => { this.loadingOrders = false; }
    });
  }

  loadAppointments(): void {
    this.loadingAppointments = true;
    this.apiService.getMyAppointments().subscribe({
      next: (res: any) => {
        const data = res.data || res;
        this.appointments = Array.isArray(data) ? data : (data.appointments || []);
        this.loadingAppointments = false;
      },
      error: () => { this.loadingAppointments = false; }
    });
  }

  loadPets(): void {
    this.loadingPets = true;
    this.apiService.getMyPets().subscribe({
      next: (res: any) => {
        const data = res.data || res;
        this.pets = Array.isArray(data) ? data : [];
        this.loadingPets = false;
      },
      error: () => { this.loadingPets = false; }
    });
  }

  getInitials(): string {
    if (!this.profile.fullName) return 'U';
    return this.profile.fullName.split(' ').map((w: string) => w.charAt(0)).join('').toUpperCase().substring(0, 2);
  }

  getFullAddress(): string {
    if (!this.profile.address) return '';
    if (typeof this.profile.address === 'string') return this.profile.address;
    const parts = [this.profile.address.street, this.profile.address.ward, this.profile.address.district, this.profile.address.city].filter(Boolean);
    return parts.join(', ');
  }

  getRoleBadges(): string[] {
    const roles: string[] = [];
    if (this.profile.role === 'admin') roles.push('Admin');
    roles.push('Khách hàng');
    return roles;
  }

  onAvatarSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files[0]) {
      this.selectedAvatarFile = input.files[0];
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.avatarPreview = e.target.result;
      };
      reader.readAsDataURL(input.files[0]);
    }
  }

  saveProfile(): void {
    this.saving = true;

    if (this.selectedAvatarFile) {
      this.apiService.uploadFile(this.selectedAvatarFile, 'avatars').subscribe({
        next: (uploadRes: any) => {
          this.profile.avatarUrl = uploadRes.data?.url || uploadRes.url;
          this.updateProfileData();
        },
        error: () => {
          this.updateProfileData();
        }
      });
    } else {
      this.updateProfileData();
    }
  }

  private updateProfileData(): void {
    const data = {
      fullName: this.profile.fullName,
      phoneNumber: this.profile.phoneNumber,
      gender: this.profile.gender,
      dateOfBirth: this.profile.dateOfBirth,
      avatarUrl: this.profile.avatarUrl,
      address: this.profile.address
    };

    this.authService.updateProfile(data).subscribe({
      next: () => {
        this.saving = false;
        this.selectedAvatarFile = null;
        this.avatarPreview = null;
        this.toastr.success('Cập nhật hồ sơ thành công!', 'Thành công');
        this.loadProfile();
      },
      error: (err: any) => {
        this.saving = false;
        this.toastr.error(err.error?.message || 'Cập nhật thất bại', 'Lỗi');
      }
    });
  }

  changePassword(): void {
    if (!this.currentPassword || !this.newPassword) {
      this.toastr.warning('Vui lòng nhập đầy đủ thông tin', 'Thông báo');
      return;
    }
    if (this.newPassword !== this.confirmPassword) {
      this.toastr.warning('Mật khẩu xác nhận không khớp', 'Thông báo');
      return;
    }
    if (this.newPassword.length < 6) {
      this.toastr.warning('Mật khẩu mới phải có ít nhất 6 ký tự', 'Thông báo');
      return;
    }

    this.changingPassword = true;
    this.authService.changePassword(this.currentPassword, this.newPassword).subscribe({
      next: () => {
        this.changingPassword = false;
        this.currentPassword = '';
        this.newPassword = '';
        this.confirmPassword = '';
        this.toastr.success('Đổi mật khẩu thành công!', 'Thành công');
      },
      error: (err: any) => {
        this.changingPassword = false;
        this.toastr.error(err.error?.message || 'Đổi mật khẩu thất bại', 'Lỗi');
      }
    });
  }

  getStatusLabel(status: string): string {
    const map: any = {
      pending: 'Chờ xử lý', confirmed: 'Đã xác nhận', processing: 'Đang xử lý',
      shipped: 'Đang giao', delivered: 'Đã giao', completed: 'Hoàn thành',
      cancelled: 'Đã hủy', scheduled: 'Đã lên lịch', 'in-progress': 'Đang thực hiện'
    };
    return map[status] || status;
  }

  getStatusClass(status: string): string {
    const map: any = {
      pending: 'warning', confirmed: 'info', processing: 'primary',
      shipped: 'info', delivered: 'success', completed: 'success',
      cancelled: 'danger', scheduled: 'info', 'in-progress': 'primary'
    };
    return map[status] || 'secondary';
  }
}

<div class="profile-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-user-circle"></i> Hồ sơ cá nhân</h1>
    </div>
  </div>

  <div class="container">
    <div class="loading-spinner" *ngIf="loading">
      <i class="fas fa-spinner fa-spin"></i> Đang tải...
    </div>

    <div class="profile-layout" *ngIf="!loading">
      <!-- Left Sidebar -->
      <div class="profile-sidebar">
        <div class="sidebar-card">
          <div class="avatar-section">
            <div class="avatar-wrapper">
              <img [src]="avatarPreview || getImg(profile.avatarUrl) || 'assets/images/default-avatar.svg'"
                   alt="Avatar" class="avatar-img">
              <label class="avatar-upload">
                <i class="fas fa-camera"></i>
                <input type="file" accept="image/*" (change)="onAvatarSelected($event)" hidden>
              </label>
            </div>
            <h3>{{ profile.fullName || 'Người dùng' }}</h3>
            <p class="email-text">{{ profile.email }}</p>
          </div>

          <!-- Role Badges -->
          <div class="role-badges">
            <span class="badge badge-admin" *ngIf="profile.role === 'admin'">
              <i class="fas fa-shield-alt"></i> Admin
            </span>
            <span class="badge badge-customer">
              <i class="fas fa-user"></i> Khách hàng
            </span>
          </div>

          <!-- Info List -->
          <div class="sidebar-info">
            <div class="info-item" *ngIf="profile.phoneNumber">
              <i class="fas fa-phone"></i>
              <span>{{ profile.phoneNumber }}</span>
            </div>
            <div class="info-item" *ngIf="getFullAddress()">
              <i class="fas fa-map-marker-alt"></i>
              <span>{{ getFullAddress() }}</span>
            </div>
            <div class="info-item">
              <i class="fas fa-calendar-plus"></i>
              <span>Tham gia: {{ profile.createdAt | date:'dd/MM/yyyy' }}</span>
            </div>
            <div class="info-item">
              <i class="fas fa-clock"></i>
              <span>Cập nhật: {{ profile.updatedAt | date:'dd/MM/yyyy' }}</span>
            </div>
          </div>

          <!-- Stats -->
          <div class="sidebar-stats">
            <div class="stat-item" (click)="switchTab('orders')">
              <span class="stat-number">{{ orderCount }}</span>
              <span class="stat-label">Đơn hàng</span>
            </div>
            <div class="stat-item" (click)="switchTab('appointments')">
              <span class="stat-number">{{ appointmentCount }}</span>
              <span class="stat-label">Lịch hẹn</span>
            </div>
            <div class="stat-item" (click)="switchTab('pets')">
              <span class="stat-number">{{ petCount }}</span>
              <span class="stat-label">Thú cưng</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Right Content -->
      <div class="profile-content">
        <!-- Tabs -->
        <div class="profile-tabs">
          <button class="tab-btn" [class.active]="activeTab === 'info'" (click)="switchTab('info')">
            <i class="fas fa-user"></i> Thông tin cá nhân
          </button>
          <button class="tab-btn" [class.active]="activeTab === 'password'" (click)="switchTab('password')">
            <i class="fas fa-lock"></i> Đổi mật khẩu
          </button>
          <button class="tab-btn" [class.active]="activeTab === 'orders'" (click)="switchTab('orders')">
            <i class="fas fa-box"></i> Đơn hàng
            <span class="tab-badge" *ngIf="orderCount > 0">{{ orderCount }}</span>
          </button>
          <button class="tab-btn" [class.active]="activeTab === 'appointments'" (click)="switchTab('appointments')">
            <i class="fas fa-calendar-check"></i> Lịch hẹn
            <span class="tab-badge" *ngIf="appointmentCount > 0">{{ appointmentCount }}</span>
          </button>
          <button class="tab-btn" [class.active]="activeTab === 'pets'" (click)="switchTab('pets')">
            <i class="fas fa-paw"></i> Thú cưng
            <span class="tab-badge" *ngIf="petCount > 0">{{ petCount }}</span>
          </button>
        </div>

        <!-- Tab: Thông tin cá nhân -->
        <div class="tab-content" *ngIf="activeTab === 'info'">
          <div class="content-card">
            <h3 class="card-title"><i class="fas fa-edit"></i> Chỉnh sửa thông tin</h3>
            <div class="form-grid">
              <div class="form-group">
                <label>Họ và tên <span class="required">*</span></label>
                <input type="text" [(ngModel)]="profile.fullName" placeholder="Nhập họ tên">
              </div>
              <div class="form-group">
                <label>Email</label>
                <input type="email" [value]="profile.email" disabled>
                <small class="hint">Email không thể thay đổi</small>
              </div>
              <div class="form-group">
                <label>Số điện thoại</label>
                <input type="tel" [(ngModel)]="profile.phoneNumber" placeholder="Nhập số điện thoại">
              </div>
              <div class="form-group">
                <label>Tên viết tắt</label>
                <input type="text" [value]="getInitials()" disabled>
              </div>
              <div class="form-group">
                <label>Giới tính</label>
                <select [(ngModel)]="profile.gender">
                  <option value="">Chọn giới tính</option>
                  <option value="Male">Nam</option>
                  <option value="Female">Nữ</option>
                  <option value="Other">Khác</option>
                </select>
              </div>
              <div class="form-group">
                <label>Ngày sinh</label>
                <input type="date" [(ngModel)]="profile.dateOfBirth">
              </div>
              <div class="form-group full">
                <label>Địa chỉ</label>
                <textarea [(ngModel)]="profile.address.street" placeholder="Nhập địa chỉ đầy đủ" rows="3"></textarea>
              </div>
            </div>
            <button class="btn-save" (click)="saveProfile()" [disabled]="saving">
              <i class="fas" [class.fa-save]="!saving" [class.fa-spinner]="saving" [class.fa-spin]="saving"></i>
              {{ saving ? 'Đang lưu...' : 'Lưu thay đổi' }}
            </button>
          </div>
        </div>

        <!-- Tab: Đổi mật khẩu -->
        <div class="tab-content" *ngIf="activeTab === 'password'">
          <div class="content-card">
            <h3 class="card-title"><i class="fas fa-key"></i> Đổi mật khẩu</h3>
            <div class="password-form">
              <div class="form-group">
                <label>Mật khẩu hiện tại</label>
                <input type="password" [(ngModel)]="currentPassword" placeholder="Nhập mật khẩu hiện tại">
              </div>
              <div class="form-group">
                <label>Mật khẩu mới</label>
                <input type="password" [(ngModel)]="newPassword" placeholder="Nhập mật khẩu mới (ít nhất 6 ký tự)">
              </div>
              <div class="form-group">
                <label>Xác nhận mật khẩu mới</label>
                <input type="password" [(ngModel)]="confirmPassword" placeholder="Nhập lại mật khẩu mới">
              </div>
              <button class="btn-save" (click)="changePassword()" [disabled]="changingPassword">
                <i class="fas" [class.fa-key]="!changingPassword" [class.fa-spinner]="changingPassword" [class.fa-spin]="changingPassword"></i>
                {{ changingPassword ? 'Đang đổi...' : 'Đổi mật khẩu' }}
              </button>
            </div>
          </div>
        </div>

        <!-- Tab: Đơn hàng -->
        <div class="tab-content" *ngIf="activeTab === 'orders'">
          <div class="content-card">
            <h3 class="card-title"><i class="fas fa-box"></i> Đơn hàng của tôi</h3>
            <div class="loading-inline" *ngIf="loadingOrders">
              <i class="fas fa-spinner fa-spin"></i> Đang tải...
            </div>
            <div class="empty-state" *ngIf="!loadingOrders && orders.length === 0">
              <i class="fas fa-box-open"></i>
              <p>Chưa có đơn hàng nào</p>
              <a routerLink="/products" class="btn-action">Mua sắm ngay</a>
            </div>
            <div class="data-list" *ngIf="!loadingOrders && orders.length > 0">
              <div class="data-item" *ngFor="let order of orders">
                <div class="item-header">
                  <span class="item-code">#{{ order.orderCode || order._id?.substring(0,8) }}</span>
                  <span class="status-badge" [ngClass]="'badge-' + getStatusClass(order.status)">
                    {{ getStatusLabel(order.status) }}
                  </span>
                </div>
                <div class="item-details">
                  <span><i class="fas fa-calendar"></i> {{ order.createdAt | date:'dd/MM/yyyy' }}</span>
                  <span><i class="fas fa-money-bill"></i> {{ (order.totalAmount || 0) | number }}đ</span>
                  <span><i class="fas fa-box"></i> {{ order.items?.length || 0 }} sản phẩm</span>
                </div>
              </div>
            </div>
            <a routerLink="/my-orders" class="view-all-link" *ngIf="orders.length > 0">
              Xem tất cả đơn hàng <i class="fas fa-arrow-right"></i>
            </a>
          </div>
        </div>

        <!-- Tab: Lịch hẹn -->
        <div class="tab-content" *ngIf="activeTab === 'appointments'">
          <div class="content-card">
            <h3 class="card-title"><i class="fas fa-calendar-check"></i> Lịch hẹn của tôi</h3>
            <div class="loading-inline" *ngIf="loadingAppointments">
              <i class="fas fa-spinner fa-spin"></i> Đang tải...
            </div>
            <div class="empty-state" *ngIf="!loadingAppointments && appointments.length === 0">
              <i class="fas fa-calendar-times"></i>
              <p>Chưa có lịch hẹn nào</p>
              <a routerLink="/booking" class="btn-action">Đặt lịch ngay</a>
            </div>
            <div class="data-list" *ngIf="!loadingAppointments && appointments.length > 0">
              <div class="data-item" *ngFor="let apt of appointments">
                <div class="item-header">
                  <span class="item-code">{{ apt.service?.name || 'Dịch vụ' }}</span>
                  <span class="status-badge" [ngClass]="'badge-' + getStatusClass(apt.status)">
                    {{ getStatusLabel(apt.status) }}
                  </span>
                </div>
                <div class="item-details">
                  <span><i class="fas fa-calendar"></i> {{ apt.date | date:'dd/MM/yyyy' }}</span>
                  <span><i class="fas fa-clock"></i> {{ apt.timeSlot }}</span>
                  <span *ngIf="apt.pet"><i class="fas fa-paw"></i> {{ apt.pet?.name }}</span>
                </div>
              </div>
            </div>
            <a routerLink="/my-appointments" class="view-all-link" *ngIf="appointments.length > 0">
              Xem tất cả lịch hẹn <i class="fas fa-arrow-right"></i>
            </a>
          </div>
        </div>

        <!-- Tab: Thú cưng -->
        <div class="tab-content" *ngIf="activeTab === 'pets'">
          <div class="content-card">
            <h3 class="card-title"><i class="fas fa-paw"></i> Thú cưng của tôi</h3>
            <div class="loading-inline" *ngIf="loadingPets">
              <i class="fas fa-spinner fa-spin"></i> Đang tải...
            </div>
            <div class="empty-state" *ngIf="!loadingPets && pets.length === 0">
              <i class="fas fa-dog"></i>
              <p>Chưa có thú cưng nào</p>
              <a routerLink="/my-pets" class="btn-action">Thêm thú cưng</a>
            </div>
            <div class="pets-grid" *ngIf="!loadingPets && pets.length > 0">
              <div class="pet-card-mini" *ngFor="let pet of pets">
                <img [src]="getImg(pet.imageUrl)" alt="{{ pet.name }}" class="pet-img">
                <div class="pet-info">
                  <h4>{{ pet.name }}</h4>
                  <p>{{ pet.breed || pet.type }}</p>
                  <span class="pet-meta">{{ pet.gender === 'Male' ? 'Đực' : 'Cái' }} · {{ pet.age }} {{ pet.ageUnit === 'years' ? 'tuổi' : 'tháng' }}</span>
                </div>
              </div>
            </div>
            <a routerLink="/my-pets" class="view-all-link" *ngIf="pets.length > 0">
              Xem tất cả thú cưng <i class="fas fa-arrow-right"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// ume-react/src/pages/profile/Profile.tsx
import { useState, useEffect } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import { orderApi, appointmentApi, petApi, uploadApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import api from '../../services/api';
import toast from 'react-hot-toast';
import './Profile.scss';

const formatPrice = (p: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(p);
const formatDate = (d: string) => new Date(d).toLocaleDateString('vi-VN', { year: 'numeric', month: '2-digit', day: '2-digit' });

const statusLabel: any = {
  Pending: 'Chờ xác nhận', Confirmed: 'Đã xác nhận', Processing: 'Đang xử lý',
  Shipping: 'Đang giao', Completed: 'Hoàn thành', Cancelled: 'Đã hủy',
  InProgress: 'Đang thực hiện', pending: 'Chờ xử lý', confirmed: 'Đã xác nhận',
  processing: 'Đang xử lý', shipped: 'Đang giao', delivered: 'Đã giao',
  completed: 'Hoàn thành', cancelled: 'Đã hủy', scheduled: 'Đã lên lịch', 'in-progress': 'Đang thực hiện',
};
const statusClass: any = {
  Pending: 'warning', Confirmed: 'info', Processing: 'primary', Shipping: 'info',
  Completed: 'success', Cancelled: 'danger', InProgress: 'primary',
  pending: 'warning', confirmed: 'info', processing: 'primary', shipped: 'info',
  delivered: 'success', completed: 'success', cancelled: 'danger', scheduled: 'info', 'in-progress': 'primary',
};

export default function Profile() {
  const { user, updateUser } = useAuth();
  const [searchParams] = useSearchParams();
  const [tab, setTab] = useState('info');
  const [profile, setProfile] = useState<any>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  // Stats
  const [orderCount, setOrderCount] = useState(0);
  const [aptCount, setAptCount] = useState(0);
  const [petCount, setPetCount] = useState(0);

  // Password
  const [pwd, setPwd] = useState({ current: '', newPwd: '', confirm: '' });
  const [changingPwd, setChangingPwd] = useState(false);

  // Avatar
  const [avatarPreview, setAvatarPreview] = useState<string | null>(null);
  const [avatarFile, setAvatarFile] = useState<File | null>(null);

  // Tab data
  const [orders, setOrders] = useState<any[]>([]);
  const [appointments, setAppointments] = useState<any[]>([]);
  const [pets, setPets] = useState<any[]>([]);
  const [loadingOrders, setLoadingOrders] = useState(false);
  const [loadingApts, setLoadingApts] = useState(false);
  const [loadingPets, setLoadingPets] = useState(false);

  useEffect(() => {
    loadProfile();
    loadStats();
    const t = searchParams.get('tab');
    if (t) switchTab(t);
  }, []);

  const loadProfile = async () => {
    setLoading(true);
    try {
      const res = await api.get('/auth/profile');
      const data = res.data?.data || res.data;
      setProfile(data);
    } catch {} finally { setLoading(false); }
  };

  const loadStats = async () => {
    try {
      const [o, a, p] = await Promise.all([orderApi.getMyOrders(), appointmentApi.getMyAppointments(), petApi.getMyPets()]);
      const od = o.data?.data; const ad = a.data?.data; const pd = p.data?.data;
      setOrderCount(Array.isArray(od) ? od.length : od?.orders?.length || od?.items?.length || 0);
      setAptCount(Array.isArray(ad) ? ad.length : ad?.appointments?.length || ad?.items?.length || 0);
      setPetCount(Array.isArray(pd) ? pd.length : pd?.length || 0);
    } catch {}
  };

  const switchTab = (t: string) => {
    setTab(t);
    if (t === 'orders' && orders.length === 0) loadOrders();
    if (t === 'appointments' && appointments.length === 0) loadAppointments();
    if (t === 'pets' && pets.length === 0) loadPets();
  };

  const loadOrders = async () => {
    setLoadingOrders(true);
    try {
      const r = await orderApi.getMyOrders();
      const d = r.data?.data;
      setOrders(Array.isArray(d) ? d : d?.orders || d?.items || []);
    } catch {} finally { setLoadingOrders(false); }
  };
  const loadAppointments = async () => {
    setLoadingApts(true);
    try {
      const r = await appointmentApi.getMyAppointments();
      const d = r.data?.data;
      setAppointments(Array.isArray(d) ? d : d?.appointments || d?.items || []);
    } catch {} finally { setLoadingApts(false); }
  };
  const loadPets = async () => {
    setLoadingPets(true);
    try {
      const r = await petApi.getMyPets();
      const d = r.data?.data;
      setPets(Array.isArray(d) ? d : d?.pets || []);
    } catch {} finally { setLoadingPets(false); }
  };

  const onAvatarSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0];
    if (!f) return;
    setAvatarFile(f);
    const reader = new FileReader();
    reader.onload = ev => setAvatarPreview(ev.target?.result as string);
    reader.readAsDataURL(f);
  };

  const saveProfile = async () => {
    setSaving(true);
    try {
      let avatarUrl = profile.avatarUrl;
      if (avatarFile) {
        const fd = new FormData();
        fd.append('file', avatarFile);
        fd.append('folder', 'avatars');
        const uRes = await uploadApi.upload(fd);
        avatarUrl = uRes.data?.data?.url || uRes.data?.url;
      }
      const data = {
        fullName: profile.fullName, phoneNumber: profile.phoneNumber,
        gender: profile.gender, dateOfBirth: profile.dateOfBirth,
        avatarUrl, address: profile.address,
      };
      await api.put('/auth/profile', data);
      setAvatarFile(null); setAvatarPreview(null);
      toast.success('Cập nhật hồ sơ thành công!');
      if (user) updateUser({ ...user, ...data });
      loadProfile();
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Cập nhật thất bại');
    } finally { setSaving(false); }
  };

  const changePassword = async () => {
    if (!pwd.current || !pwd.newPwd) { toast.error('Vui lòng nhập đầy đủ thông tin'); return; }
    if (pwd.newPwd !== pwd.confirm) { toast.error('Mật khẩu xác nhận không khớp'); return; }
    if (pwd.newPwd.length < 6) { toast.error('Mật khẩu mới phải có ít nhất 6 ký tự'); return; }
    setChangingPwd(true);
    try {
      await api.put('/auth/change-password', { currentPassword: pwd.current, newPassword: pwd.newPwd });
      setPwd({ current: '', newPwd: '', confirm: '' });
      toast.success('Đổi mật khẩu thành công!');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Đổi mật khẩu thất bại');
    } finally { setChangingPwd(false); }
  };

  if (loading) return <div className="profile-page"><div className="container" style={{ padding: '100px 0', textAlign: 'center' }}>⏳ Đang tải...</div></div>;

  return (
    <div className="profile-page">
      <div className="page-header"><div className="container"><h1>👤 Hồ sơ cá nhân</h1></div></div>
      <div className="container">
        <div className="profile-layout">
          {/* Sidebar */}
          <div className="profile-sidebar">
            <div className="sidebar-card">
              <div className="avatar-section">
                <div className="avatar-wrapper">
                  <img src={avatarPreview || getImageUrl(profile.avatarUrl) || '/assets/images/default-avatar.svg'} alt="Avatar" className="avatar-img"
                    onError={e => { (e.target as HTMLImageElement).src = '/assets/images/default-avatar.svg'; }} />
                  <label className="avatar-upload">📷<input type="file" accept="image/*" onChange={onAvatarSelect} hidden /></label>
                </div>
                <h3>{profile.fullName || 'Người dùng'}</h3>
                <p className="email-text">{profile.email}</p>
              </div>
              <div className="role-badges">
                {profile.role === 'admin' && <span className="badge badge-admin">🛡️ Admin</span>}
                <span className="badge badge-customer">👤 Khách hàng</span>
              </div>
              <div className="sidebar-info">
                {profile.phoneNumber && <div className="info-item">📱 {profile.phoneNumber}</div>}
                {profile.address && <div className="info-item">📍 {typeof profile.address === 'string' ? profile.address : [profile.address?.street, profile.address?.ward, profile.address?.district, profile.address?.city].filter(Boolean).join(', ')}</div>}
                <div className="info-item">📅 Tham gia: {formatDate(profile.createdAt)}</div>
              </div>
              <div className="sidebar-stats">
                <div className="stat-item" onClick={() => switchTab('orders')}><span className="stat-number">{orderCount}</span><span className="stat-label">Đơn hàng</span></div>
                <div className="stat-item" onClick={() => switchTab('appointments')}><span className="stat-number">{aptCount}</span><span className="stat-label">Lịch hẹn</span></div>
                <div className="stat-item" onClick={() => switchTab('pets')}><span className="stat-number">{petCount}</span><span className="stat-label">Thú cưng</span></div>
              </div>
            </div>
          </div>

          {/* Content */}
          <div className="profile-content">
            <div className="profile-tabs">
              {[['info', '👤 Thông tin'], ['password', '🔒 Đổi mật khẩu'], ['orders', '📦 Đơn hàng'], ['appointments', '📅 Lịch hẹn'], ['pets', '🐾 Thú cưng']].map(([k, l]) => (
                <button key={k} className={`tab-btn ${tab === k ? 'active' : ''}`} onClick={() => switchTab(k)}>{l}
                  {k === 'orders' && orderCount > 0 && <span className="tab-badge">{orderCount}</span>}
                  {k === 'appointments' && aptCount > 0 && <span className="tab-badge">{aptCount}</span>}
                  {k === 'pets' && petCount > 0 && <span className="tab-badge">{petCount}</span>}
                </button>
              ))}
            </div>

            {/* Info tab */}
            {tab === 'info' && (
              <div className="content-card">
                <h3>✏️ Chỉnh sửa thông tin</h3>
                <div className="form-grid">
                  <div className="form-group"><label>Họ và tên *</label><input value={profile.fullName || ''} onChange={e => setProfile((p: any) => ({ ...p, fullName: e.target.value }))} /></div>
                  <div className="form-group"><label>Email</label><input value={profile.email || ''} disabled /><small>Email không thể thay đổi</small></div>
                  <div className="form-group"><label>Số điện thoại</label><input value={profile.phoneNumber || ''} onChange={e => setProfile((p: any) => ({ ...p, phoneNumber: e.target.value }))} /></div>
                  <div className="form-group"><label>Giới tính</label>
                    <select value={profile.gender || ''} onChange={e => setProfile((p: any) => ({ ...p, gender: e.target.value }))}>
                      <option value="">Chọn giới tính</option><option value="Nam">Nam</option><option value="Nữ">Nữ</option><option value="Khác">Khác</option>
                    </select>
                  </div>
                  <div className="form-group"><label>Ngày sinh</label><input type="date" value={profile.dateOfBirth?.split('T')[0] || ''} onChange={e => setProfile((p: any) => ({ ...p, dateOfBirth: e.target.value }))} /></div>
                  <div className="form-group full"><label>Địa chỉ</label><textarea value={typeof profile.address === 'string' ? profile.address : ''} onChange={e => setProfile((p: any) => ({ ...p, address: e.target.value }))} rows={3} /></div>
                </div>
                <button className="btn-save" onClick={saveProfile} disabled={saving}>{saving ? '⏳ Đang lưu...' : '💾 Lưu thay đổi'}</button>
              </div>
            )}

            {/* Password tab */}
            {tab === 'password' && (
              <div className="content-card">
                <h3>🔑 Đổi mật khẩu</h3>
                <div className="password-form">
                  <div className="form-group"><label>Mật khẩu hiện tại</label><input type="password" value={pwd.current} onChange={e => setPwd(p => ({ ...p, current: e.target.value }))} /></div>
                  <div className="form-group"><label>Mật khẩu mới</label><input type="password" value={pwd.newPwd} onChange={e => setPwd(p => ({ ...p, newPwd: e.target.value }))} placeholder="Ít nhất 6 ký tự" /></div>
                  <div className="form-group"><label>Xác nhận mật khẩu</label><input type="password" value={pwd.confirm} onChange={e => setPwd(p => ({ ...p, confirm: e.target.value }))} /></div>
                  <button className="btn-save" onClick={changePassword} disabled={changingPwd}>{changingPwd ? '⏳ Đang đổi...' : '🔑 Đổi mật khẩu'}</button>
                </div>
              </div>
            )}

            {/* Orders tab */}
            {tab === 'orders' && (
              <div className="content-card">
                <h3>📦 Đơn hàng của tôi</h3>
                {loadingOrders && <p className="loading-inline">⏳ Đang tải...</p>}
                {!loadingOrders && orders.length === 0 && <div className="empty-state"><p>📭 Chưa có đơn hàng nào</p><Link to="/products" className="btn-action">Mua sắm ngay</Link></div>}
                <div className="data-list">
                  {orders.map(o => (
                    <div key={o._id} className="data-item">
                      <div className="item-header"><span className="item-code">#{o.orderCode || o._id?.substring(0, 8)}</span><span className={`status-badge badge-${statusClass[o.status] || 'secondary'}`}>{statusLabel[o.status] || o.status}</span></div>
                      <div className="item-details"><span>📅 {formatDate(o.createdAt)}</span><span>💰 {formatPrice(o.totalAmount || 0)}</span><span>📦 {o.items?.length || 0} sản phẩm</span></div>
                    </div>
                  ))}
                </div>
                {orders.length > 0 && <Link to="/my-orders" className="view-all-link">Xem tất cả đơn hàng →</Link>}
              </div>
            )}

            {/* Appointments tab */}
            {tab === 'appointments' && (
              <div className="content-card">
                <h3>📅 Lịch hẹn của tôi</h3>
                {loadingApts && <p className="loading-inline">⏳ Đang tải...</p>}
                {!loadingApts && appointments.length === 0 && <div className="empty-state"><p>📅 Chưa có lịch hẹn nào</p><Link to="/booking" className="btn-action">Đặt lịch ngay</Link></div>}
                <div className="data-list">
                  {appointments.map(a => (
                    <div key={a._id} className="data-item">
                      <div className="item-header"><span className="item-code">{a.appointmentCode}</span><span className={`status-badge badge-${statusClass[a.status] || 'secondary'}`}>{statusLabel[a.status] || a.status}</span></div>
                      <div className="item-details">
                        <span>📅 {formatDate(a.appointmentDate || a.date)}</span>
                        <span>🕐 {a.startTime || a.timeSlot}</span>
                        {a.pet && <span>🐾 {a.pet.name}</span>}
                      </div>
                    </div>
                  ))}
                </div>
                {appointments.length > 0 && <Link to="/my-appointments" className="view-all-link">Xem tất cả lịch hẹn →</Link>}
              </div>
            )}

            {/* Pets tab */}
            {tab === 'pets' && (
              <div className="content-card">
                <h3>🐾 Thú cưng của tôi</h3>
                {loadingPets && <p className="loading-inline">⏳ Đang tải...</p>}
                {!loadingPets && pets.length === 0 && <div className="empty-state"><p>🐾 Chưa có thú cưng nào</p><Link to="/my-pets" className="btn-action">Thêm thú cưng</Link></div>}
                <div className="pets-mini-grid">
                  {pets.map(p => (
                    <div key={p._id} className="pet-card-mini">
                      <img src={getImageUrl(p.imageUrl)} alt={p.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/default-pet.svg'; }} />
                      <div className="pet-info"><h4>{p.name}</h4><p>{p.breed || p.type}</p><span>{p.gender === 'Male' ? 'Đực' : 'Cái'} · {p.age} {p.ageUnit === 'years' ? 'tuổi' : 'tháng'}</span></div>
                    </div>
                  ))}
                </div>
                {pets.length > 0 && <Link to="/my-pets" className="view-all-link">Xem tất cả thú cưng →</Link>}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
