// ume-react/src/pages/admin/reviews/AdminReviews.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { reviewApi, getImageUrl } from '../../../services/api';
import '../shared/admin.scss';

function fmtD(d: string) { return d ? new Date(d).toLocaleDateString('vi-VN') : '-'; }
function stars(n: number) { return '★'.repeat(n) + '☆'.repeat(5 - n); }

export default function AdminReviews() {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState('');
  const [ratingFilter, setRatingFilter] = useState('');
  const [approvalFilter, setApprovalFilter] = useState('');
  const [stats, setStats] = useState({ total: 0, avg: 0, pending: 0, approved: 0 });

  const [showReply, setShowReply] = useState(false);
  const [replyItem, setReplyItem] = useState<any>(null);
  const [replyText, setReplyText] = useState('');

  const [showDelete, setShowDelete] = useState(false);
  const [deleteItem, setDeleteItem] = useState<any>(null);

  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  useEffect(() => { load(); }, [page]);

  async function load() {
    setLoading(true);
    try {
      const p: any = { page: String(page), limit: '20' };
      if (search) p.search = search;
      if (ratingFilter) p.rating = ratingFilter;
      if (approvalFilter) p.isApproved = approvalFilter;
      const r = await reviewApi.getAll(p);
      const d = r.data?.data || r.data;
      const list = d?.reviews || d || [];
      setItems(list);
      setTotalPages(d?.totalPages || 1);
      setStats({
        total: d?.total || list.length,
        avg: list.length ? (list.reduce((s: number, rv: any) => s + (rv.rating || 0), 0) / list.length) : 0,
        pending: list.filter((rv: any) => !rv.isApproved).length,
        approved: list.filter((rv: any) => rv.isApproved).length,
      });
    } catch {}
    setLoading(false);
  }

  async function toggleApproval(item: any) {
    try {
      await reviewApi.reply(item._id, { isApproved: !item.isApproved });
      toast.success(item.isApproved ? 'Đã ẩn đánh giá' : 'Đã duyệt đánh giá');
      load();
    } catch { toast.error('Có lỗi xảy ra'); }
  }

  function openReply(item: any) {
    setReplyItem(item);
    setReplyText(item.adminReply || '');
    setShowReply(true);
  }

  async function submitReply() {
    if (!replyItem || !replyText.trim()) { toast.error('Nhập nội dung phản hồi'); return; }
    try {
      await reviewApi.reply(replyItem._id, { adminReply: replyText });
      toast.success('Đã gửi phản hồi!');
      setShowReply(false); load();
    } catch { toast.error('Có lỗi xảy ra'); }
  }

  async function doDelete() {
    if (!deleteItem) return;
    try { await reviewApi.delete(deleteItem._id); toast.success('Đã xóa!'); setShowDelete(false); load(); }
    catch { toast.error('Có lỗi xảy ra'); }
  }

  return (
    <div>
      <div className="page-header">
        <div><h4>⭐ Quản lý đánh giá</h4>
          <ol className="breadcrumb"><li><Link to="/admin">Dashboard</Link></li><li className="active">Đánh giá</li></ol>
        </div>
      </div>

      <div className="stats-row">
        <div className="stat-box"><div className="sb-icon bg-info">⭐</div><div><div className="sb-num">{stats.total}</div><div className="sb-label">Tổng đánh giá</div></div></div>
        <div className="stat-box"><div className="sb-icon bg-gold">🌟</div><div><div className="sb-num">{stats.avg.toFixed(1)}</div><div className="sb-label">Điểm TB</div></div></div>
        <div className="stat-box"><div className="sb-icon bg-warning">⏳</div><div><div className="sb-num">{stats.pending}</div><div className="sb-label">Chờ duyệt</div></div></div>
        <div className="stat-box"><div className="sb-icon bg-success">✅</div><div><div className="sb-num">{stats.approved}</div><div className="sb-label">Đã duyệt</div></div></div>
      </div>

      <div className="card">
        <div className="card-header">
          <div className="filter-row">
            <div className="search-box">
              <input className="form-control" value={search} onChange={e => setSearch(e.target.value)} placeholder="Tìm đánh giá..." onKeyDown={e => e.key === 'Enter' && load()} />
              <button className="btn btn-gold btn-sm" onClick={load}>🔍</button>
            </div>
            <select className="form-control fc-sm" value={ratingFilter} onChange={e => { setRatingFilter(e.target.value); setTimeout(load, 0); }}>
              <option value="">Tất cả sao</option>
              {[5, 4, 3, 2, 1].map(n => <option key={n} value={String(n)}>{n} sao</option>)}
            </select>
            <select className="form-control fc-sm" value={approvalFilter} onChange={e => { setApprovalFilter(e.target.value); setTimeout(load, 0); }}>
              <option value="">Tất cả</option>
              <option value="true">Đã duyệt</option>
              <option value="false">Chờ duyệt</option>
            </select>
          </div>
        </div>
        <div className="card-body p-0">
          <table className="adm-table">
            <thead><tr><th>#</th><th>Khách hàng</th><th>Sản phẩm/DV</th><th>Đánh giá</th><th>Nội dung</th><th>Ngày</th><th>Duyệt</th><th>Thao tác</th></tr></thead>
            <tbody>
              {items.map((rv, i) => (
                <tr key={rv._id}>
                  <td>{(page - 1) * 20 + i + 1}</td>
                  <td><strong>{rv.user?.fullName || '-'}</strong><div className="sub-txt">{rv.user?.email}</div></td>
                  <td>{rv.product?.name || rv.service?.name || rv.pet?.name || '-'}<div className="sub-txt">{rv.type || '-'}</div></td>
                  <td><span style={{ color: '#f5a623', fontSize: '1rem' }}>{stars(rv.rating || 0)}</span></td>
                  <td style={{ maxWidth: 250, whiteSpace: 'normal' }}>
                    {rv.comment || '-'}
                    {rv.images?.length > 0 && (
                      <div style={{ display: 'flex', gap: 4, marginTop: 6, flexWrap: 'wrap' }}>
                        {rv.images.map((img: string, idx: number) => (
                          <a key={idx} href={getImageUrl(img)} target="_blank" rel="noopener noreferrer">
                            <img src={getImageUrl(img)} alt="" style={{ width: 48, height: 48, objectFit: 'cover', borderRadius: 4, border: '1px solid #dee2e6' }} />
                          </a>
                        ))}
                      </div>
                    )}
                    {rv.adminReply && <div className="sub-txt" style={{ marginTop: 4 }}>💬 Admin: {rv.adminReply}</div>}
                  </td>
                  <td>{fmtD(rv.createdAt)}</td>
                  <td>
                    <label className="toggle-switch"><input type="checkbox" checked={rv.isApproved} onChange={() => toggleApproval(rv)} /><span className="toggle-slider"></span></label>
                  </td>
                  <td><div className="act-g">
                    <button className="ab ab-edit" title="Phản hồi" onClick={() => openReply(rv)}>💬</button>
                    <button className="ab ab-del" onClick={() => { setDeleteItem(rv); setShowDelete(true); }}>🗑️</button>
                  </div></td>
                </tr>
              ))}
              {!items.length && !loading && <tr><td colSpan={8} className="empty">Không có đánh giá nào</td></tr>}
              {loading && <tr><td colSpan={8} className="empty">Đang tải...</td></tr>}
            </tbody>
          </table>
        </div>
        {totalPages > 1 && (
          <div className="card-footer" style={{ display: 'flex', justifyContent: 'center', gap: 4 }}>
            {Array.from({ length: totalPages }, (_, i) => (
              <button key={i} className={`btn btn-sm ${page === i + 1 ? 'btn-gold' : 'btn-outline-gold'}`} onClick={() => setPage(i + 1)}>{i + 1}</button>
            ))}
          </div>
        )}
      </div>

      {/* Reply Modal */}
      {showReply && replyItem && (
        <div className="mo" onClick={() => setShowReply(false)}>
          <div className="md" onClick={e => e.stopPropagation()}>
            <div className="mh bg-g"><h5>💬 Phản hồi đánh giá</h5><button className="mx" onClick={() => setShowReply(false)}>&times;</button></div>
            <div className="mb-modal">
              <div style={{ background: '#f8f9fa', borderRadius: 8, padding: 12, marginBottom: 12 }}>
                <p><strong>{replyItem.user?.fullName}</strong> <span style={{ color: '#f5a623' }}>{stars(replyItem.rating)}</span></p>
                <p>{replyItem.comment || '(Không có nội dung)'}</p>
              </div>
              <div className="fg"><label>Nội dung phản hồi</label><textarea className="form-control" rows={4} value={replyText} onChange={e => setReplyText(e.target.value)} placeholder="Nhập phản hồi..." /></div>
            </div>
            <div className="mf"><button className="btn btn-sec" onClick={() => setShowReply(false)}>Hủy</button><button className="btn btn-gold" onClick={submitReply}>💬 Gửi phản hồi</button></div>
          </div>
        </div>
      )}

      {showDelete && (
        <div className="mo" onClick={() => setShowDelete(false)}>
          <div className="md" onClick={e => e.stopPropagation()}>
            <div className="mh bg-r"><h5>🗑️ Xóa đánh giá</h5><button className="mx" onClick={() => setShowDelete(false)}>&times;</button></div>
            <div className="mb-modal"><p>Bạn có chắc muốn xóa đánh giá này?</p></div>
            <div className="mf"><button className="btn btn-sec" onClick={() => setShowDelete(false)}>Hủy</button><button className="btn btn-danger" onClick={doDelete}>🗑️ Xác nhận xóa</button></div>
          </div>
        </div>
      )}
    </div>
  );
}

// ume-frontend/src/app/pages/admin/admin-reviews/admin-reviews.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api.service';

@Component({
  selector: 'app-admin-reviews',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="page-header">
      <h2><i class="fas fa-star"></i> Quản lý đánh giá</h2>
    </div>

    <!-- Filters -->
    <div class="card mb-3">
      <div class="card-body">
        <div class="filter-row">
          <select [(ngModel)]="filterApproved" (change)="loadReviews()" class="form-control">
            <option value="">Tất cả trạng thái</option>
            <option value="true">Đã duyệt</option>
            <option value="false">Chưa duyệt</option>
          </select>
          <button class="btn btn-gold" (click)="loadReviews()"><i class="fas fa-sync"></i> Làm mới</button>
        </div>
      </div>
    </div>

    <!-- Reviews List -->
    <div class="card">
      <div class="card-body p-0">
        <div class="table-responsive">
          <table class="adm-table">
            <thead>
              <tr>
                <th>Khách hàng</th>
                <th>Đối tượng</th>
                <th>Đánh giá</th>
                <th>Nội dung</th>
                <th>Phản hồi</th>
                <th>Ngày</th>
                <th>Thao tác</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let review of reviews">
                <td>
                  <strong>{{ review.customer?.fullName || 'N/A' }}</strong>
                </td>
                <td>
                  <span *ngIf="review.product" class="target-badge bg-product">
                    <i class="fas fa-box"></i> {{ review.product?.name }}
                  </span>
                  <span *ngIf="review.service" class="target-badge bg-service">
                    <i class="fas fa-cut"></i> {{ review.service?.name }}
                  </span>
                  <span *ngIf="review.staff" class="target-badge bg-staff">
                    <i class="fas fa-user"></i> {{ review.staff?.fullName }}
                  </span>
                  <span *ngIf="review.appointment && !review.service && !review.product" class="target-badge bg-appointment">
                    <i class="fas fa-calendar-check"></i> {{ review.appointment?.appointmentCode || 'Lịch hẹn' }}
                  </span>
                </td>
                <td>
                  <div class="stars">
                    <span *ngFor="let s of [1,2,3,4,5]" [class.filled]="s <= review.rating">★</span>
                  </div>
                </td>
                <td class="review-content">
                  <strong *ngIf="review.title">{{ review.title }}</strong>
                  <p>{{ review.comment || 'Không có nội dung' }}</p>
                  <div class="review-images" *ngIf="review.images?.length">
                    <img *ngFor="let img of review.images" [src]="apiUrl + img" class="review-thumb">
                  </div>
                </td>
                <td>
                  <div *ngIf="review.reply" class="reply-box">
                    <p>{{ review.reply }}</p>
                    <small class="text-muted">{{ review.repliedAt | date:'dd/MM HH:mm' }}</small>
                  </div>
                  <div *ngIf="!review.reply && !review.showReplyForm">
                    <button class="btn btn-sm btn-outline" (click)="review.showReplyForm = true">Phản hồi</button>
                  </div>
                  <div *ngIf="review.showReplyForm" class="reply-form">
                    <textarea [(ngModel)]="review.replyText" placeholder="Nhập phản hồi..." rows="2" class="form-control"></textarea>
                    <div class="reply-actions">
                      <button class="btn btn-sm btn-gold" (click)="replyReview(review)">Gửi</button>
                      <button class="btn btn-sm btn-outline" (click)="review.showReplyForm = false">Hủy</button>
                    </div>
                  </div>
                </td>
                <td>{{ review.createdAt | date:'dd/MM/yyyy' }}</td>
                <td>
                  <button class="btn-icon btn-danger" (click)="deleteReview(review)" title="Xóa"><i class="fas fa-trash"></i></button>
                </td>
              </tr>
              <tr *ngIf="reviews.length === 0">
                <td colspan="7" class="text-center py-4 text-muted">Chưa có đánh giá nào</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Pagination -->
    <div class="pagination" *ngIf="pagination.pages > 1">
      <button [disabled]="pagination.page <= 1" (click)="goPage(pagination.page - 1)">«</button>
      <button *ngFor="let p of getPages()" [class.active]="p === pagination.page" (click)="goPage(p)">{{ p }}</button>
      <button [disabled]="pagination.page >= pagination.pages" (click)="goPage(pagination.page + 1)">»</button>
    </div>
  `,
  styles: [`
    :host { display: block; }
    .page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; }
    .page-header h2 { font-weight: 600; font-size: 1.4rem; color: #1a1a1a; margin: 0; }
    .page-header h2 i { color: #D4AF37; margin-right: 8px; }
    .card { border: none; border-radius: 12px; box-shadow: 0 2px 12px rgba(0,0,0,.08); background: #fff; margin-bottom: 16px; }
    .card-body { padding: 16px; }
    .mb-3 { margin-bottom: 16px; }
    .p-0 { padding: 0 !important; }
    .filter-row { display: flex; gap: 10px; flex-wrap: wrap; }
    .form-control { padding: 8px 12px; border: 1px solid #dee2e6; border-radius: 6px; font-size: .85rem; width: 100%; }
    .form-control:focus { outline: none; border-color: #D4AF37; }
    .btn { padding: 8px 16px; border: none; border-radius: 6px; cursor: pointer; font-size: .85rem; }
    .btn-sm { padding: 4px 10px; font-size: .78rem; }
    .btn-gold { background: #D4AF37; color: #fff; }
    .btn-gold:hover { background: #B8960C; }
    .btn-outline { background: #f8f9fa; border: 1px solid #dee2e6; color: #333; }
    .btn-outline:hover { background: #e9ecef; }
    .table-responsive { overflow-x: auto; }
    .adm-table { width: 100%; border-collapse: collapse; }
    .adm-table th, .adm-table td { padding: 10px 14px; border-bottom: 1px solid #f0f0f0; font-size: .85rem; vertical-align: top; }
    .adm-table thead th { background: #f8f9fa; font-weight: 600; white-space: nowrap; }
    .adm-table tbody tr:hover { background: rgba(212,175,55,.05); }
    .stars { color: #ddd; font-size: 1rem; }
    .stars .filled { color: #ffc107; }
    .target-badge { display: inline-block; padding: 3px 8px; border-radius: 4px; font-size: .73rem; color: #fff; margin-bottom: 2px; }
    .bg-product { background: #6c757d; }
    .bg-service { background: #17a2b8; }
    .bg-staff { background: #28a745; }
    .bg-appointment { background: #6f42c1; }
    .review-content { max-width: 250px; }
    .review-content p { margin: 4px 0 0; font-size: .82rem; color: #555; }
    .review-images { display: flex; gap: 4px; margin-top: 6px; }
    .review-thumb { width: 40px; height: 40px; border-radius: 4px; object-fit: cover; }
    .reply-box { background: #f8f9fa; padding: 8px; border-radius: 6px; font-size: .82rem; max-width: 200px; }
    .reply-box p { margin: 0; }
    .reply-form { display: flex; flex-direction: column; gap: 6px; max-width: 200px; }
    .reply-form textarea { font-size: .82rem; resize: none; }
    .reply-actions { display: flex; gap: 4px; }
    .text-muted { color: #6c757d; }
    .text-center { text-align: center; }
    .py-4 { padding: 30px 0; }
    .btn-icon { border: none; padding: 6px 10px; border-radius: 4px; cursor: pointer; font-size: .8rem; }
    .btn-danger { background: #dc3545; color: #fff; }
    .btn-danger:hover { background: #c82333; }
    .pagination { display: flex; justify-content: center; gap: 4px; margin-top: 16px; }
    .pagination button { padding: 6px 12px; border: 1px solid #dee2e6; background: #fff; border-radius: 4px; cursor: pointer; font-size: .85rem; }
    .pagination button.active { background: #D4AF37; color: #fff; border-color: #D4AF37; }
    .pagination button:disabled { opacity: .5; cursor: not-allowed; }
  `]
})
export class AdminReviewsComponent implements OnInit {
  reviews: any[] = [];
  filterApproved = '';
  pagination = { page: 1, limit: 20, total: 0, pages: 0 };
  apiUrl = '';

  constructor(private api: ApiService) {
    this.apiUrl = (this.api as any).apiUrl?.replace('/api', '') || 'http://localhost:5000';
  }

  ngOnInit(): void {
    this.loadReviews();
  }

  loadReviews(): void {
    const params: any = { page: this.pagination.page, limit: this.pagination.limit };
    if (this.filterApproved) params.isApproved = this.filterApproved;

    this.api.get('/reviews', params).subscribe({
      next: (res: any) => {
        if (res.success) {
          this.reviews = (res.data?.reviews || []).map((r: any) => ({ ...r, showReplyForm: false, replyText: '' }));
          if (res.data?.pagination) this.pagination = { ...this.pagination, ...res.data.pagination };
        }
      },
      error: () => {}
    });
  }

  replyReview(review: any): void {
    if (!review.replyText?.trim()) return;
    this.api.put(`/reviews/${review._id}/reply`, { reply: review.replyText }).subscribe({
      next: (res: any) => {
        if (res.success) {
          review.reply = review.replyText;
          review.repliedAt = new Date();
          review.showReplyForm = false;
        }
      },
      error: () => alert('Lỗi khi phản hồi')
    });
  }

  deleteReview(review: any): void {
    if (!confirm('Xóa đánh giá này?')) return;
    this.api.delete(`/reviews/${review._id}`).subscribe({
      next: () => this.loadReviews(),
      error: () => alert('Lỗi khi xóa')
    });
  }

  goPage(p: number): void {
    this.pagination.page = p;
    this.loadReviews();
  }

  getPages(): number[] {
    const pages = [];
    for (let i = 1; i <= this.pagination.pages; i++) pages.push(i);
    return pages;
  }
}
