// ume-react/src/pages/booking/Booking.tsx
import { useState, useEffect } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { serviceApi, staffApi, appointmentApi, petApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import toast from 'react-hot-toast';
import './Booking.scss';

const formatPrice = (price: number) =>
  new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);

const formatDuration = (mins: number) => {
  if (mins < 60) return `${mins} phút`;
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return m > 0 ? `${h}h${m}p` : `${h} giờ`;
};

const petTypes = [
  { value: 'Dog', label: 'Chó' }, { value: 'Cat', label: 'Mèo' },
  { value: 'Bird', label: 'Chim' }, { value: 'Hamster', label: 'Hamster' },
  { value: 'Rabbit', label: 'Thỏ' }, { value: 'Fish', label: 'Cá' },
  { value: 'Other', label: 'Khác' },
];
const petGenders = [
  { value: 'Male', label: 'Đực' }, { value: 'Female', label: 'Cái' },
  { value: 'Neutered', label: 'Đã triệt sản' },
];

export default function Booking() {
  const [searchParams] = useSearchParams();
  const [step, setStep] = useState(1);

  // Step 1
  const [services, setServices] = useState<any[]>([]);
  const [selectedServices, setSelectedServices] = useState<any[]>([]);

  // Step 2
  const [availableStaff, setAvailableStaff] = useState<any[]>([]);
  const [selectedStaff, setSelectedStaff] = useState<any>(null);

  // Step 3
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [selectedTime, setSelectedTime] = useState('');
  const [timeSlots, setTimeSlots] = useState<string[]>([]);
  const minDate = new Date().toISOString().split('T')[0];

  // Step 4
  const [myPets, setMyPets] = useState<any[]>([]);
  const [selectedPet, setSelectedPet] = useState<any>(null);
  const [describePet, setDescribePet] = useState(false);
  const [petDesc, setPetDesc] = useState({ name: '', type: '', gender: '', age: 0, weight: 0, notes: '' });

  // Step 5
  const [notes, setNotes] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [bookedCode, setBookedCode] = useState('');
  const [, setLoading] = useState(false);

  useEffect(() => {
    loadServices();
    loadMyPets();
  }, []);

  const loadServices = async () => {
    setLoading(true);
    try {
      const res = await serviceApi.getAll({ limit: 100 });
      const list = res.data?.data?.services || res.data?.data?.items || res.data?.data || [];
      setServices(list);
      const preselect = searchParams.get('service');
      if (preselect) {
        const found = list.find((s: any) => s._id === preselect);
        if (found) setSelectedServices([found]);
      }
    } catch {} finally { setLoading(false); }
  };

  const loadMyPets = async () => {
    try {
      const res = await petApi.getMyPets();
      setMyPets(res.data?.data?.items || res.data?.data || []);
    } catch {}
  };

  const loadStaff = async () => {
    try {
      const ids = selectedServices.map(s => s._id).join(',');
      const res = await staffApi.getAvailable({ services: ids, date: selectedDate });
      setAvailableStaff(res.data?.data?.items || res.data?.data || []);
    } catch {}
  };

  const generateTimeSlots = () => {
    const slots: string[] = [];
    for (let h = 8; h <= 19; h++) {
      slots.push(`${h.toString().padStart(2, '0')}:00`);
      if (h < 19) slots.push(`${h.toString().padStart(2, '0')}:30`);
    }
    setTimeSlots(slots);
  };

  const toggleService = (s: any) => {
    setSelectedServices(prev => {
      const idx = prev.findIndex(ss => ss._id === s._id);
      return idx > -1 ? prev.filter(ss => ss._id !== s._id) : [...prev, s];
    });
  };

  const totalAmount = selectedServices.reduce((sum, s) => sum + (s.price || 0), 0);
  const totalDuration = selectedServices.reduce((sum, s) => sum + (s.durationMinutes || 0), 0);

  const nextStep = () => {
    if (step === 1 && selectedServices.length === 0) { toast.error('Chọn ít nhất một dịch vụ'); return; }
    if (step === 3 && !selectedDate) { toast.error('Chọn ngày'); return; }
    if (step === 3 && !selectedTime) { toast.error('Chọn giờ'); return; }
    if (step < 5) {
      const next = step + 1;
      setStep(next);
      if (next === 2) loadStaff();
      if (next === 3) generateTimeSlots();
    }
  };

  const submitBooking = async () => {
    setSubmitting(true);
    try {
      const data: any = {
        services: selectedServices.map(s => s._id),
        appointmentDate: selectedDate,
        startTime: selectedTime,
        notes,
      };
      if (selectedStaff) data.staffId = selectedStaff._id;
      if (selectedPet) data.petId = selectedPet._id;
      if (describePet && petDesc.name) data.petDescription = petDesc;
      const res = await appointmentApi.create(data);
      setBookedCode(res.data?.data?.appointmentCode || res.data?.data?.appointment?.appointmentCode || '');
      setShowSuccess(true);
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Đặt lịch thất bại');
    } finally { setSubmitting(false); }
  };

  return (
    <div className="booking-page">
      <div className="page-header">
        <div className="container">
          <h1>📅 Đặt lịch hẹn</h1>
          <p>Đặt lịch chăm sóc thú cưng chỉ trong vài bước</p>
        </div>
      </div>

      <div className="container">
        {/* Stepper */}
        <div className="stepper">
          {[1, 2, 3, 4, 5].map(s => (
            <div key={s} className={`step ${step === s ? 'active' : ''} ${step > s ? 'completed' : ''}`}>
              <div className="step-circle">{step > s ? '✓' : s}</div>
              <span className="step-label">{['Dịch vụ', 'Nhân viên', 'Ngày giờ', 'Thú cưng', 'Xác nhận'][s - 1]}</span>
            </div>
          ))}
        </div>

        {/* Step 1 */}
        {step === 1 && (
          <div className="step-content">
            <h2>Chọn dịch vụ</h2>
            <div className="services-list">
              {services.map(s => (
                <div key={s._id} className={`service-item ${selectedServices.some(ss => ss._id === s._id) ? 'selected' : ''}`} onClick={() => toggleService(s)}>
                  <div className="service-check">{selectedServices.some(ss => ss._id === s._id) ? '✅' : '⭕'}</div>
                  {s.imageUrl && <div className="service-img"><img src={getImageUrl(s.imageUrl)} alt={s.name} /></div>}
                  <div className="service-info">
                    <h4>{s.name}</h4>
                    <p>{s.description}</p>
                    <div className="service-meta">
                      <span>⏱️ {formatDuration(s.durationMinutes)}</span>
                      <span className="service-price">{formatPrice(s.price)}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            {selectedServices.length > 0 && (
              <div className="selection-summary">
                <span>Đã chọn {selectedServices.length} dịch vụ</span>
                <span>Tổng: {formatPrice(totalAmount)} · {formatDuration(totalDuration)}</span>
              </div>
            )}
          </div>
        )}

        {/* Step 2 */}
        {step === 2 && (
          <div className="step-content">
            <h2>Chọn nhân viên (tùy chọn)</h2>
            <div className="staff-grid">
              {availableStaff.map(staff => (
                <div key={staff._id} className={`staff-card ${selectedStaff?._id === staff._id ? 'selected' : ''}`} onClick={() => setSelectedStaff(staff)}>
                  <img src={getImageUrl(staff.avatarUrl)} alt={staff.fullName} className="staff-avatar" onError={e => { (e.target as HTMLImageElement).src = '/assets/images/default-avatar.svg'; }} />
                  <h4>{staff.nickName || staff.fullName}</h4>
                  <p className="staff-position">{staff.position}</p>
                  <div className="staff-rating">⭐ {staff.averageRating?.toFixed(1) || '0.0'}</div>
                </div>
              ))}
            </div>
            {availableStaff.length === 0 && <p className="skip-note">Không có nhân viên khả dụng. Hệ thống sẽ tự động chỉ định.</p>}
            <button className="btn-skip" onClick={() => { setSelectedStaff(null); nextStep(); }}>Bỏ qua - Để hệ thống chọn</button>
          </div>
        )}

        {/* Step 3 */}
        {step === 3 && (
          <div className="step-content">
            <h2>Chọn ngày và giờ</h2>
            <div className="datetime-grid">
              <div className="date-section">
                <label>Ngày hẹn</label>
                <input type="date" value={selectedDate} min={minDate} onChange={e => { setSelectedDate(e.target.value); setSelectedTime(''); loadStaff(); }} />
              </div>
              <div className="time-section">
                <label>Giờ hẹn</label>
                <div className="time-slots">
                  {timeSlots.map(slot => (
                    <button key={slot} className={selectedTime === slot ? 'selected' : ''} onClick={() => setSelectedTime(slot)}>{slot}</button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Step 4 */}
        {step === 4 && (
          <div className="step-content">
            <h2>Chọn thú cưng (tùy chọn)</h2>
            <div className="pet-mode-tabs">
              <button className={!describePet ? 'active' : ''} onClick={() => setDescribePet(false)}>📋 Chọn có sẵn</button>
              <button className={describePet ? 'active' : ''} onClick={() => { setDescribePet(true); setSelectedPet(null); }}>✏️ Miêu tả thú cưng</button>
            </div>

            {!describePet && (
              <>
                {myPets.length > 0 ? (
                  <div className="pets-grid">
                    {myPets.map(pet => (
                      <div key={pet._id} className={`pet-card ${selectedPet?._id === pet._id ? 'selected' : ''}`} onClick={() => { setSelectedPet(pet); setDescribePet(false); }}>
                        <img src={getImageUrl(pet.imageUrl)} alt={pet.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/default-pet.svg'; }} />
                        <h4>{pet.name}</h4>
                        <p>{pet.type} - {pet.breed}</p>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="skip-note">Bạn chưa có thú cưng nào. <Link to="/my-pets">Thêm thú cưng</Link> hoặc miêu tả bên dưới.</p>
                )}
              </>
            )}

            {describePet && (
              <div className="pet-describe-form">
                <div className="form-row">
                  <div className="form-group">
                    <label>Tên thú cưng *</label>
                    <input value={petDesc.name} onChange={e => setPetDesc(p => ({ ...p, name: e.target.value }))} placeholder="VD: Milo, Lucky..." />
                  </div>
                  <div className="form-group">
                    <label>Loại *</label>
                    <select value={petDesc.type} onChange={e => setPetDesc(p => ({ ...p, type: e.target.value }))}>
                      <option value="">-- Chọn loại --</option>
                      {petTypes.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
                    </select>
                  </div>
                </div>
                <div className="form-row">
                  <div className="form-group">
                    <label>Giới tính</label>
                    <select value={petDesc.gender} onChange={e => setPetDesc(p => ({ ...p, gender: e.target.value }))}>
                      <option value="">-- Chọn --</option>
                      {petGenders.map(g => <option key={g.value} value={g.value}>{g.label}</option>)}
                    </select>
                  </div>
                  <div className="form-group">
                    <label>Tuổi (năm)</label>
                    <input type="number" value={petDesc.age || ''} onChange={e => setPetDesc(p => ({ ...p, age: +e.target.value }))} min={0} max={30} />
                  </div>
                </div>
                <div className="form-row">
                  <div className="form-group">
                    <label>Cân nặng (kg)</label>
                    <input type="number" value={petDesc.weight || ''} onChange={e => setPetDesc(p => ({ ...p, weight: +e.target.value }))} min={0} step={0.1} />
                  </div>
                  <div className="form-group">
                    <label>Ghi chú sức khỏe</label>
                    <input value={petDesc.notes} onChange={e => setPetDesc(p => ({ ...p, notes: e.target.value }))} placeholder="Dị ứng, bệnh lý..." />
                  </div>
                </div>
              </div>
            )}

            <button className="btn-skip" onClick={() => { setSelectedPet(null); setDescribePet(false); nextStep(); }}>Bỏ qua</button>
          </div>
        )}

        {/* Step 5 */}
        {step === 5 && (
          <div className="step-content">
            <h2>Xác nhận đặt lịch</h2>
            <div className="confirm-card">
              <div className="confirm-section">
                <h4>🔔 Dịch vụ đã chọn</h4>
                <ul>{selectedServices.map(s => <li key={s._id}>{s.name} - {formatPrice(s.price)} ({formatDuration(s.durationMinutes)})</li>)}</ul>
              </div>
              {selectedStaff && <div className="confirm-section"><h4>👤 Nhân viên</h4><p>{selectedStaff.nickName || selectedStaff.fullName}</p></div>}
              <div className="confirm-section"><h4>📅 Ngày giờ</h4><p>{selectedDate} lúc {selectedTime}</p></div>
              {selectedPet && <div className="confirm-section"><h4>🐾 Thú cưng</h4><p>{selectedPet.name} ({selectedPet.type})</p></div>}
              {describePet && petDesc.name && (
                <div className="confirm-section"><h4>🐾 Thú cưng (miêu tả)</h4><p><strong>{petDesc.name}</strong> - {petDesc.type}</p></div>
              )}
              <div className="confirm-section">
                <h4>📝 Ghi chú</h4>
                <textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Ghi chú thêm..." rows={3} />
              </div>
              <div className="confirm-total"><span>Tổng cộng:</span><strong>{formatPrice(totalAmount)}</strong></div>
            </div>
          </div>
        )}

        {/* Nav */}
        <div className="step-actions">
          {step > 1 && <button className="btn-prev" onClick={() => setStep(s => s - 1)}>← Quay lại</button>}
          <div className="spacer"></div>
          {step < 5 && <button className="btn-next" onClick={nextStep}>Tiếp theo →</button>}
          {step === 5 && <button className="btn-submit" onClick={submitBooking} disabled={submitting}>{submitting ? '⏳ Đang xử lý...' : '✅ Xác nhận đặt lịch'}</button>}
        </div>

        {/* Success Modal */}
        {showSuccess && (
          <div className="success-overlay">
            <div className="success-modal">
              <div className="success-icon">✅</div>
              <h2>Đặt lịch thành công!</h2>
              <p>Lịch hẹn của bạn đã được tạo thành công</p>
              {bookedCode && <p className="success-code">Mã lịch hẹn: <strong>{bookedCode}</strong></p>}
              <div className="success-details">
                <div>📅 {selectedDate} lúc {selectedTime}</div>
                {selectedStaff && <div>👤 {selectedStaff.nickName || selectedStaff.fullName}</div>}
                <div>🔔 {selectedServices.length} dịch vụ · {formatPrice(totalAmount)}</div>
              </div>
              <Link className="btn-go" to="/my-appointments">📋 Xem lịch hẹn của tôi</Link>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ume-frontend/src/app/pages/booking/booking.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute, RouterLink } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-booking',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './booking.component.html',
  styleUrl: './booking.component.scss'
})
export class BookingComponent implements OnInit {
  currentStep = 1;
  totalSteps = 5;

  // Step 1
  services: any[] = [];
  selectedServices: any[] = [];

  // Step 2
  availableStaff: any[] = [];
  selectedStaff: any = null;

  // Step 3
  selectedDate = '';
  selectedTime = '';
  availableTimeSlots: string[] = [];
  minDate = '';

  // Step 4
  myPets: any[] = [];
  selectedPet: any = null;
  skipPet = false;
  describePet = false;
  petDescription = { name: '', type: '', gender: '', age: 0, weight: 0, notes: '' };
  petGenders = [
    { value: 'Male', label: 'Đực' },
    { value: 'Female', label: 'Cái' },
    { value: 'Neutered', label: 'Đã triệt sản' }
  ];
  petTypes = [
    { value: 'Dog', label: 'Chó' },
    { value: 'Cat', label: 'Mèo' },
    { value: 'Bird', label: 'Chim' },
    { value: 'Hamster', label: 'Hamster' },
    { value: 'Rabbit', label: 'Thỏ' },
    { value: 'Fish', label: 'Cá' },
    { value: 'Other', label: 'Khác' }
  ];

  // Step 5
  notes = '';
  submitting = false;
  showSuccessModal = false;
  bookedCode = '';

  loading = false;

  constructor(
    private apiService: ApiService,
    private authService: AuthService,
    private toastr: ToastrService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  getImg(path: string): string { return this.apiService.getImageUrl(path); }

  ngOnInit(): void {
    const today = new Date();
    this.minDate = today.toISOString().split('T')[0];
    this.selectedDate = this.minDate;
    this.loadServices();
    this.loadMyPets();

    this.route.queryParams.subscribe(params => {
      if (params['service']) {
        this.preselectService(params['service']);
      }
    });
  }

  loadServices(): void {
    this.loading = true;
    this.apiService.getServices({ limit: 100 }).subscribe({
      next: (res: any) => {
        this.services = res.data?.items || res.data || [];
        this.loading = false;
      },
      error: () => { this.loading = false; }
    });
  }

  preselectService(serviceId: string): void {
    setTimeout(() => {
      const service = this.services.find(s => s._id === serviceId);
      if (service) {
        this.toggleService(service);
      }
    }, 500);
  }

  loadMyPets(): void {
    this.apiService.getMyPets().subscribe({
      next: (res: any) => {
        this.myPets = res.data?.items || res.data || [];
      }
    });
  }

  loadAvailableStaff(): void {
    const serviceIds = this.selectedServices.map(s => s._id);
    this.apiService.getAvailableStaff({ services: serviceIds.join(','), date: this.selectedDate }).subscribe({
      next: (res: any) => {
        this.availableStaff = res.data?.items || res.data || [];
      }
    });
  }

  toggleService(service: any): void {
    const idx = this.selectedServices.findIndex(s => s._id === service._id);
    if (idx > -1) {
      this.selectedServices.splice(idx, 1);
    } else {
      this.selectedServices.push(service);
    }
  }

  isServiceSelected(serviceId: string): boolean {
    return this.selectedServices.some(s => s._id === serviceId);
  }

  get totalAmount(): number {
    return this.selectedServices.reduce((sum, s) => sum + (s.price || 0), 0);
  }

  get totalDuration(): number {
    return this.selectedServices.reduce((sum, s) => sum + (s.durationMinutes || 0), 0);
  }

  generateTimeSlots(): void {
    this.availableTimeSlots = [];
    for (let h = 8; h <= 19; h++) {
      this.availableTimeSlots.push(`${h.toString().padStart(2, '0')}:00`);
      if (h < 19) {
        this.availableTimeSlots.push(`${h.toString().padStart(2, '0')}:30`);
      }
    }
  }

  onDateChange(): void {
    this.generateTimeSlots();
    this.selectedTime = '';
    if (this.selectedDate) {
      this.loadAvailableStaff();
    }
  }

  selectStaff(staff: any): void {
    this.selectedStaff = staff;
  }

  selectPet(pet: any): void {
    this.selectedPet = pet;
    this.skipPet = false;
    this.describePet = false;
  }

  toggleDescribePet(): void {
    this.describePet = !this.describePet;
    if (this.describePet) {
      this.selectedPet = null;
      this.skipPet = false;
    }
  }

  nextStep(): void {
    if (this.currentStep < this.totalSteps) {
      if (this.currentStep === 1 && this.selectedServices.length === 0) {
        this.toastr.warning('Vui lòng chọn ít nhất một dịch vụ', 'Thông báo');
        return;
      }
      if (this.currentStep === 3) {
        if (!this.selectedDate) {
          this.toastr.warning('Vui lòng chọn ngày', 'Thông báo');
          return;
        }
        if (!this.selectedTime) {
          this.toastr.warning('Vui lòng chọn giờ', 'Thông báo');
          return;
        }
      }
      this.currentStep++;
      if (this.currentStep === 2) this.loadAvailableStaff();
      if (this.currentStep === 3) this.generateTimeSlots();
    }
  }

  prevStep(): void {
    if (this.currentStep > 1) this.currentStep--;
  }

  submitBooking(): void {
    this.submitting = true;
    const data: any = {
      services: this.selectedServices.map(s => s._id),
      appointmentDate: this.selectedDate,
      startTime: this.selectedTime,
      notes: this.notes
    };
    if (this.selectedStaff) data.staffId = this.selectedStaff._id;
    if (this.selectedPet) data.petId = this.selectedPet._id;
    if (this.describePet && this.petDescription.name) {
      data.petDescription = this.petDescription;
    }

    this.apiService.createAppointment(data).subscribe({
      next: (res: any) => {
        this.submitting = false;
        this.bookedCode = res.data?.appointmentCode || res.data?.appointment?.appointmentCode || '';
        this.showSuccessModal = true;
      },
      error: (err: any) => {
        this.submitting = false;
        this.toastr.error(err.error?.message || 'Đặt lịch thất bại', 'Lỗi');
      }
    });
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  formatDuration(minutes: number): string {
    if (minutes < 60) return `${minutes} phút`;
    const h = Math.floor(minutes / 60);
    const m = minutes % 60;
    return m > 0 ? `${h}h${m}p` : `${h} giờ`;
  }
}

<div class="booking-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-calendar-alt"></i> Đặt lịch hẹn</h1>
      <p>Đặt lịch chăm sóc thú cưng chỉ trong vài bước</p>
    </div>
  </div>

  <div class="container">
    <!-- Stepper -->
    <div class="stepper">
      <div class="step" *ngFor="let step of [1,2,3,4,5]"
           [class.active]="currentStep === step"
           [class.completed]="currentStep > step">
        <div class="step-circle">{{ step }}</div>
        <span class="step-label">
          {{ step === 1 ? 'Dịch vụ' : step === 2 ? 'Nhân viên' : step === 3 ? 'Ngày giờ' : step === 4 ? 'Thú cưng' : 'Xác nhận' }}
        </span>
      </div>
    </div>

    <!-- Step 1: Services -->
    <div class="step-content" *ngIf="currentStep === 1">
      <h2>Chọn dịch vụ</h2>
      <div class="services-list">
        <div class="service-item" *ngFor="let s of services"
             [class.selected]="isServiceSelected(s._id)"
             (click)="toggleService(s)">
          <div class="service-check">
            <i class="fas" [class.fa-check-circle]="isServiceSelected(s._id)"
               [class.fa-circle]="!isServiceSelected(s._id)"></i>
          </div>
          <div class="service-img" *ngIf="s.imageUrl">
            <img [src]="getImg(s.imageUrl)" [alt]="s.name">
          </div>
          <div class="service-info">
            <h4>{{ s.name }}</h4>
            <p>{{ s.description }}</p>
            <div class="service-meta">
              <span><i class="fas fa-clock"></i> {{ formatDuration(s.durationMinutes) }}</span>
              <span class="service-price">{{ formatPrice(s.price) }}</span>
            </div>
          </div>
        </div>
      </div>
      <div class="selection-summary" *ngIf="selectedServices.length > 0">
        <span>Đã chọn {{ selectedServices.length }} dịch vụ</span>
        <span>Tổng: {{ formatPrice(totalAmount) }} · {{ formatDuration(totalDuration) }}</span>
      </div>
    </div>

    <!-- Step 2: Staff -->
    <div class="step-content" *ngIf="currentStep === 2">
      <h2>Chọn nhân viên (tùy chọn)</h2>
      <div class="staff-grid">
        <div class="staff-card" *ngFor="let staff of availableStaff"
             [class.selected]="selectedStaff?._id === staff._id"
             (click)="selectStaff(staff)">
          <img [src]="getImg(staff.avatarUrl) || 'assets/images/default-avatar.svg'"
               [alt]="staff.fullName" class="staff-avatar">
          <h4>{{ staff.nickName || staff.fullName }}</h4>
          <p class="staff-position">{{ staff.position }}</p>
          <div class="staff-rating">
            <i class="fas fa-star"></i>
            <span>{{ staff.averageRating?.toFixed(1) || '0.0' }}</span>
          </div>
        </div>
      </div>
      <p class="skip-note" *ngIf="availableStaff.length === 0">
        Không có nhân viên khả dụng. Hệ thống sẽ tự động chỉ định.
      </p>
      <button class="btn-skip" (click)="selectedStaff = null; nextStep()">
        Bỏ qua - Để hệ thống chọn
      </button>
    </div>

    <!-- Step 3: Date & Time -->
    <div class="step-content" *ngIf="currentStep === 3">
      <h2>Chọn ngày và giờ</h2>
      <div class="datetime-grid">
        <div class="date-section">
          <label>Ngày hẹn</label>
          <input type="date" [(ngModel)]="selectedDate" [min]="minDate"
                 (change)="onDateChange()">
        </div>
        <div class="time-section">
          <label>Giờ hẹn</label>
          <div class="time-slots">
            <button *ngFor="let slot of availableTimeSlots"
                    [class.selected]="selectedTime === slot"
                    (click)="selectedTime = slot">
              {{ slot }}
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Step 4: Pet -->
    <div class="step-content" *ngIf="currentStep === 4">
      <h2>Chọn thú cưng (tùy chọn)</h2>

      <!-- Tab chọn phương thức -->
      <div class="pet-mode-tabs">
        <button class="pet-mode-tab" [class.active]="!describePet" (click)="describePet = false">
          <i class="fas fa-list"></i> Chọn thú cưng có sẵn
        </button>
        <button class="pet-mode-tab" [class.active]="describePet" (click)="toggleDescribePet()">
          <i class="fas fa-edit"></i> Miêu tả thú cưng
        </button>
      </div>

      <!-- Chọn pet có sẵn -->
      <div *ngIf="!describePet">
        <div class="pets-grid" *ngIf="myPets.length > 0">
          <div class="pet-card" *ngFor="let pet of myPets"
               [class.selected]="selectedPet?._id === pet._id"
               (click)="selectPet(pet)">
            <img [src]="getImg(pet.imageUrl) || 'assets/images/default-pet.svg'"
                 [alt]="pet.name" class="pet-img">
            <h4>{{ pet.name }}</h4>
            <p>{{ pet.type }} - {{ pet.breed }}</p>
          </div>
        </div>
        <p class="skip-note" *ngIf="myPets.length === 0">
          Bạn chưa có thú cưng nào. <a routerLink="/my-pets">Thêm thú cưng</a>
          hoặc <a (click)="toggleDescribePet()" class="link-describe">miêu tả thú cưng</a> bên dưới.
        </p>
      </div>

      <!-- Miêu tả pet -->
      <div class="pet-describe-form" *ngIf="describePet">
        <div class="form-row">
          <div class="form-group">
            <label><i class="fas fa-paw"></i> Tên thú cưng *</label>
            <input type="text" [(ngModel)]="petDescription.name" class="form-control" placeholder="VD: Milo, Lucky...">
          </div>
          <div class="form-group">
            <label><i class="fas fa-dog"></i> Loại *</label>
            <select [(ngModel)]="petDescription.type" class="form-control">
              <option value="">-- Chọn loại --</option>
              <option *ngFor="let t of petTypes" [value]="t.value">{{ t.label }}</option>
            </select>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group">
            <label><i class="fas fa-venus-mars"></i> Giới tính</label>
            <select [(ngModel)]="petDescription.gender" class="form-control">
              <option value="">-- Chọn giới tính --</option>
              <option *ngFor="let g of petGenders" [value]="g.value">{{ g.label }}</option>
            </select>
          </div>
          <div class="form-group">
            <label><i class="fas fa-birthday-cake"></i> Tuổi (năm)</label>
            <input type="number" [(ngModel)]="petDescription.age" class="form-control" min="0" max="30" placeholder="VD: 2">
          </div>
        </div>
        <div class="form-row">
          <div class="form-group">
            <label><i class="fas fa-weight"></i> Cân nặng (kg)</label>
            <input type="number" [(ngModel)]="petDescription.weight" class="form-control" min="0" max="200" step="0.1" placeholder="VD: 5">
          </div>
          <div class="form-group">
            <label><i class="fas fa-notes-medical"></i> Ghi chú sức khỏe</label>
            <input type="text" [(ngModel)]="petDescription.notes" class="form-control" placeholder="Dị ứng, bệnh lý...">
          </div>
        </div>
      </div>

      <button class="btn-skip" (click)="selectedPet = null; describePet = false; skipPet = true; nextStep()">
        Bỏ qua
      </button>
    </div>

    <!-- Step 5: Confirm -->
    <div class="step-content" *ngIf="currentStep === 5">
      <h2>Xác nhận đặt lịch</h2>
      <div class="confirm-card">
        <div class="confirm-section">
          <h4><i class="fas fa-concierge-bell"></i> Dịch vụ đã chọn</h4>
          <ul>
            <li *ngFor="let s of selectedServices">
              {{ s.name }} - {{ formatPrice(s.price) }} ({{ formatDuration(s.durationMinutes) }})
            </li>
          </ul>
        </div>
        <div class="confirm-section" *ngIf="selectedStaff">
          <h4><i class="fas fa-user"></i> Nhân viên</h4>
          <p>{{ selectedStaff.nickName || selectedStaff.fullName }}</p>
        </div>
        <div class="confirm-section">
          <h4><i class="fas fa-calendar"></i> Ngày giờ</h4>
          <p>{{ selectedDate }} lúc {{ selectedTime }}</p>
        </div>
        <div class="confirm-section" *ngIf="selectedPet">
          <h4><i class="fas fa-paw"></i> Thú cưng</h4>
          <p>{{ selectedPet.name }} ({{ selectedPet.type }})</p>
        </div>
        <div class="confirm-section" *ngIf="describePet && petDescription.name">
          <h4><i class="fas fa-paw"></i> Thú cưng (miêu tả)</h4>
          <p><strong>{{ petDescription.name }}</strong> - {{ petDescription.type }} {{ petDescription.gender ? '· ' + (petDescription.gender === 'Male' ? 'Đực' : petDescription.gender === 'Female' ? 'Cái' : 'Đã triệt sản') : '' }}</p>
          <p *ngIf="petDescription.age || petDescription.weight">
            <span *ngIf="petDescription.age">{{ petDescription.age }} tuổi</span>
            <span *ngIf="petDescription.age && petDescription.weight"> · </span>
            <span *ngIf="petDescription.weight">{{ petDescription.weight }} kg</span>
          </p>
          <p *ngIf="petDescription.notes" class="text-muted">{{ petDescription.notes }}</p>
        </div>
        <div class="confirm-section">
          <h4><i class="fas fa-sticky-note"></i> Ghi chú</h4>
          <textarea [(ngModel)]="notes" placeholder="Ghi chú thêm (tùy chọn)..." rows="3"></textarea>
        </div>
        <div class="confirm-total">
          <span>Tổng cộng:</span>
          <strong>{{ formatPrice(totalAmount) }}</strong>
        </div>
      </div>
    </div>

    <!-- Navigation -->
    <div class="step-actions">
      <button class="btn-prev" (click)="prevStep()" *ngIf="currentStep > 1">
        <i class="fas fa-arrow-left"></i> Quay lại
      </button>
      <div class="spacer"></div>
      <button class="btn-next" (click)="nextStep()" *ngIf="currentStep < totalSteps">
        Tiếp theo <i class="fas fa-arrow-right"></i>
      </button>
      <button class="btn-submit" (click)="submitBooking()"
              *ngIf="currentStep === totalSteps" [disabled]="submitting">
        <i class="fas" [class.fa-check]="!submitting" [class.fa-spinner]="submitting" [class.fa-spin]="submitting"></i>
        {{ submitting ? 'Đang xử lý...' : 'Xác nhận đặt lịch' }}
      </button>
    </div>

    <!-- Success Modal -->
    <div class="success-overlay" *ngIf="showSuccessModal">
      <div class="success-modal">
        <div class="success-icon">
          <i class="fas fa-check-circle"></i>
        </div>
        <h2>Đặt lịch thành công!</h2>
        <p class="success-msg">Lịch hẹn của bạn đã được tạo thành công</p>
        <p class="success-code" *ngIf="bookedCode">Mã lịch hẹn: <strong>{{ bookedCode }}</strong></p>
        <div class="success-details">
          <div class="sd-item">
            <i class="fas fa-calendar"></i>
            <span>{{ selectedDate }} lúc {{ selectedTime }}</span>
          </div>
          <div class="sd-item" *ngIf="selectedStaff">
            <i class="fas fa-user"></i>
            <span>{{ selectedStaff.nickName || selectedStaff.fullName }}</span>
          </div>
          <div class="sd-item">
            <i class="fas fa-concierge-bell"></i>
            <span>{{ selectedServices.length }} dịch vụ · {{ formatPrice(totalAmount) }}</span>
          </div>
        </div>
        <a class="btn-go-appointments" routerLink="/my-appointments">
          <i class="fas fa-calendar-check"></i> Xem lịch hẹn của tôi
        </a>
      </div>
    </div>
  </div>
</div>
