// ume-frontend/src/app/pages/my-orders/my-orders.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-my-orders',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './my-orders.component.html',
  styleUrl: './my-orders.component.scss'
})
export class MyOrdersComponent implements OnInit {
  orders: any[] = [];
  loading = false;
  selectedStatus = '';
  cancellingId: string | null = null;
  cancelReason = '';
  selectedOrder: any = null;

  // Review
  showReviewModal = false;
  reviewingOrder: any = null;
  reviewingItem: any = null;
  reviewRating = 5;
  reviewComment = '';
  reviewSubmitting = false;
  hoverRating = 0;
  orderReviewedMap: { [orderId: string]: string[] } = {}; // orderId -> reviewed productId[]

  statuses = [
    { value: '', label: 'Tất cả' },
    { value: 'Pending', label: 'Chờ xác nhận' },
    { value: 'Confirmed', label: 'Đã xác nhận' },
    { value: 'Processing', label: 'Đang xử lý' },
    { value: 'Shipping', label: 'Đang giao' },
    { value: 'Completed', label: 'Hoàn thành' },
    { value: 'Cancelled', label: 'Đã hủy' }
  ];

  constructor(
    private apiService: ApiService,
    private toastr: ToastrService
  ) {}

  getImg(path: string): string { return this.apiService.getImageUrl(path); }

  ngOnInit(): void {
    this.loadOrders();
  }

  loadOrders(): void {
    this.loading = true;
    const params: any = {};
    if (this.selectedStatus) params.status = this.selectedStatus;

    this.apiService.getMyOrders(params).subscribe({
      next: (res: any) => {
        this.orders = res.data?.orders || res.data?.items || (Array.isArray(res.data) ? res.data : []);
        this.loading = false;
        // Check reviews for completed orders
        this.orders.forEach(order => {
          if (order.status === 'Completed') {
            this.checkOrderReviews(order._id);
          }
        });
      },
      error: () => { this.loading = false; }
    });
  }

  checkOrderReviews(orderId: string): void {
    this.apiService.get(`/reviews/check-order/${orderId}`).subscribe({
      next: (res: any) => {
        this.orderReviewedMap[orderId] = res.data?.reviewedProductIds || [];
      },
      error: () => {}
    });
  }

  hasUnreviewedItems(order: any): boolean {
    if (order.status !== 'Completed') return false;
    const reviewed = this.orderReviewedMap[order._id] || [];
    return (order.items || []).some((item: any) => {
      const pid = item.product?._id || item.product;
      return pid && !reviewed.includes(pid.toString());
    });
  }

  isItemReviewed(order: any, item: any): boolean {
    const reviewed = this.orderReviewedMap[order._id] || [];
    const pid = item.product?._id || item.product;
    return pid ? reviewed.includes(pid.toString()) : false;
  }

  filterByStatus(status: string): void {
    this.selectedStatus = status;
    this.loadOrders();
  }

  showCancelDialog(id: string): void {
    this.cancellingId = id;
    this.cancelReason = '';
  }

  closeCancelDialog(): void {
    this.cancellingId = null;
  }

  confirmCancel(): void {
    if (!this.cancellingId) return;
    this.apiService.cancelOrder(this.cancellingId, { cancelReason: this.cancelReason }).subscribe({
      next: () => {
        this.toastr.success('Đã hủy đơn hàng thành công', 'Thành công');
        this.cancellingId = null;
        this.loadOrders();
      },
      error: (err: any) => {
        this.toastr.error(err.error?.message || 'Hủy đơn hàng thất bại', 'Lỗi');
      }
    });
  }

  // Review methods
  openReviewModal(order: any, item: any): void {
    this.reviewingOrder = order;
    this.reviewingItem = item;
    this.reviewRating = 5;
    this.reviewComment = '';
    this.hoverRating = 0;
    this.showReviewModal = true;
  }

  closeReviewModal(): void {
    this.showReviewModal = false;
    this.reviewingOrder = null;
    this.reviewingItem = null;
  }

  setRating(star: number): void {
    this.reviewRating = star;
  }

  setHoverRating(star: number): void {
    this.hoverRating = star;
  }

  resetHover(): void {
    this.hoverRating = 0;
  }

  getStarClass(star: number): string {
    const active = this.hoverRating || this.reviewRating;
    return star <= active ? 'star active' : 'star';
  }

  getRatingLabel(): string {
    const active = this.hoverRating || this.reviewRating;
    const labels: { [key: number]: string } = {
      1: 'Rất không hài lòng',
      2: 'Không hài lòng',
      3: 'Bình thường',
      4: 'Hài lòng',
      5: 'Rất hài lòng'
    };
    return labels[active] || '';
  }

  submitReview(): void {
    if (!this.reviewingOrder || !this.reviewingItem) return;
    this.reviewSubmitting = true;

    const productId = this.reviewingItem.product?._id || this.reviewingItem.product;
    const formData = new FormData();
    formData.append('productId', productId);
    formData.append('orderId', this.reviewingOrder._id);
    formData.append('rating', this.reviewRating.toString());
    formData.append('comment', this.reviewComment);

    this.apiService.createReview(formData).subscribe({
      next: () => {
        this.toastr.success('Cảm ơn bạn đã đánh giá!', 'Thành công');
        // Update reviewed map
        if (!this.orderReviewedMap[this.reviewingOrder._id]) {
          this.orderReviewedMap[this.reviewingOrder._id] = [];
        }
        this.orderReviewedMap[this.reviewingOrder._id].push(productId);
        this.closeReviewModal();
        this.reviewSubmitting = false;
      },
      error: (err: any) => {
        this.reviewSubmitting = false;
        this.toastr.error(err.error?.message || 'Gửi đánh giá thất bại', 'Lỗi');
      }
    });
  }

  getStatusLabel(status: string): string {
    const map: any = {
      Pending: 'Chờ xác nhận',
      Confirmed: 'Đã xác nhận',
      Processing: 'Đang xử lý',
      Shipping: 'Đang giao',
      Completed: 'Hoàn thành',
      Cancelled: 'Đã hủy'
    };
    return map[status] || status;
  }

  getStatusClass(status: string): string {
    const map: any = {
      Pending: 'pending',
      Confirmed: 'confirmed',
      Processing: 'processing',
      Shipping: 'shipping',
      Completed: 'completed',
      Cancelled: 'cancelled'
    };
    return map[status] || '';
  }

  getItemsSummary(order: any): string {
    const items = order.items || [];
    if (items.length === 0) return '';
    const first = items[0].productName || items[0].product?.name || 'Sản phẩm';
    if (items.length === 1) return first;
    return `${first} và ${items.length - 1} sản phẩm khác`;
  }

  viewOrder(order: any): void {
    if (order._id) {
      this.apiService.getOrder(order._id).subscribe({
        next: (res: any) => { this.selectedOrder = res.data?.order || res.data || order; },
        error: () => { this.selectedOrder = order; }
      });
    } else {
      this.selectedOrder = order;
    }
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString('vi-VN', {
      year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit'
    });
  }
}

<div class="my-orders-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-shopping-bag"></i> Đơn hàng của tôi</h1>
    </div>
  </div>

  <div class="container">
    <!-- Status Filter -->
    <div class="status-tabs">
      <button *ngFor="let s of statuses"
              [class.active]="selectedStatus === s.value"
              (click)="filterByStatus(s.value)">
        {{ s.label }}
      </button>
    </div>

    <div class="loading-spinner" *ngIf="loading">
      <i class="fas fa-spinner fa-spin"></i> Đang tải...
    </div>

    <div class="orders-list" *ngIf="!loading">
      <div class="order-card" *ngFor="let order of orders">
        <div class="card-header">
          <div class="order-code">
            <i class="fas fa-receipt"></i> {{ order.orderCode }}
          </div>
          <span class="status-badge" [ngClass]="getStatusClass(order.status)">
            {{ getStatusLabel(order.status) }}
          </span>
        </div>

        <div class="card-body">
          <div class="order-items">
            <div class="order-item" *ngFor="let item of order.items; let i = index">
              <img [src]="getImg(item.productImage || item.product?.imageUrl || item.product?.mainImage)"
                   [alt]="item.productName" class="item-img"
                   onerror="this.src='assets/images/no-image.svg'" *ngIf="i < 3">
              <div class="item-info" *ngIf="i < 3">
                <span class="item-name">{{ item.productName || item.product?.name }}</span>
                <span class="item-qty">x{{ item.quantity }} · {{ formatPrice(item.unitPrice || item.price) }}</span>
              </div>
            </div>
            <div class="more-items" *ngIf="order.items?.length > 3">
              ... và {{ order.items.length - 3 }} sản phẩm khác
            </div>
          </div>
          <div class="order-meta">
            <span><i class="fas fa-clock"></i> {{ formatDate(order.createdAt) }}</span>
            <span *ngIf="order.paymentMethod">
              <i class="fas fa-wallet"></i> {{ order.paymentMethod === 'COD' ? 'COD' : 'Chuyển khoản' }}
            </span>
          </div>
        </div>

        <div class="card-footer">
          <span class="total-amount">
            Tổng: <strong>{{ formatPrice(order.totalAmount) }}</strong>
          </span>
          <div class="footer-actions">
            <button class="btn-detail" (click)="viewOrder(order)">
              <i class="fas fa-eye"></i> Chi tiết
            </button>
            <button class="btn-cancel" *ngIf="order.status === 'Pending' || order.status === 'Confirmed'"
                    (click)="showCancelDialog(order._id)">
              <i class="fas fa-times"></i> Hủy đơn
            </button>
            <!-- Review buttons for completed orders -->
            <ng-container *ngIf="order.status === 'Completed'">
              <ng-container *ngFor="let item of order.items">
                <button class="btn-review" *ngIf="!isItemReviewed(order, item)"
                        (click)="openReviewModal(order, item)">
                  <i class="fas fa-star"></i> Đánh giá {{ item.productName || item.product?.name }}
                </button>
                <span class="reviewed-badge" *ngIf="isItemReviewed(order, item)">
                  <i class="fas fa-check-circle"></i> Đã đánh giá {{ item.productName || item.product?.name }}
                </span>
              </ng-container>
            </ng-container>
          </div>
        </div>
      </div>
    </div>

    <div class="empty-state" *ngIf="!loading && orders.length === 0">
      <i class="fas fa-box-open"></i>
      <p>Bạn chưa có đơn hàng nào</p>
      <a routerLink="/products" class="btn-shop">Mua sắm ngay</a>
    </div>

    <!-- Cancel Dialog -->
    <div class="modal-overlay" *ngIf="cancellingId" (click)="closeCancelDialog()">
      <div class="modal-content" (click)="$event.stopPropagation()">
        <h3>Hủy đơn hàng</h3>
        <p>Bạn có chắc muốn hủy đơn hàng này?</p>
        <div class="form-group">
          <label>Lý do hủy</label>
          <textarea [(ngModel)]="cancelReason" placeholder="Nhập lý do hủy..." rows="3"></textarea>
        </div>
        <div class="modal-actions">
          <button class="btn-secondary" (click)="closeCancelDialog()">Đóng</button>
          <button class="btn-danger" (click)="confirmCancel()">Xác nhận hủy</button>
        </div>
      </div>
    </div>

    <!-- Order Detail Modal -->
    <div class="modal-overlay" *ngIf="selectedOrder" (click)="selectedOrder=null">
      <div class="modal-detail" (click)="$event.stopPropagation()">
        <div class="modal-header-detail">
          <h3><i class="fas fa-receipt"></i> Chi tiết đơn hàng #{{ selectedOrder.orderCode }}</h3>
          <button class="close-btn" (click)="selectedOrder=null">&times;</button>
        </div>
        <div class="modal-body-detail">
          <div class="detail-info-grid">
            <div class="info-item">
              <label>Trạng thái</label>
              <span class="status-badge" [ngClass]="getStatusClass(selectedOrder.status)">{{ getStatusLabel(selectedOrder.status) }}</span>
            </div>
            <div class="info-item">
              <label>Ngày đặt</label>
              <span>{{ formatDate(selectedOrder.createdAt) }}</span>
            </div>
            <div class="info-item">
              <label>Thanh toán</label>
              <span>{{ selectedOrder.paymentMethod || 'COD' }} — {{ selectedOrder.paymentStatus === 'Paid' ? 'Đã thanh toán' : 'Chưa thanh toán' }}</span>
            </div>
            <div class="info-item full-w">
              <label>Địa chỉ giao hàng</label>
              <span>{{ selectedOrder.shippingAddress?.address ? (selectedOrder.shippingAddress.address + ', ' + selectedOrder.shippingAddress.ward + ', ' + selectedOrder.shippingAddress.district + ', ' + selectedOrder.shippingAddress.city) : (selectedOrder.shippingAddress || '-') }}</span>
            </div>
            <div class="info-item full-w" *ngIf="selectedOrder.notes">
              <label>Ghi chú</label>
              <span>{{ selectedOrder.notes }}</span>
            </div>
          </div>
          <h4 class="section-title"><i class="fas fa-box"></i> Sản phẩm ({{ selectedOrder.items?.length || 0 }})</h4>
          <div class="detail-items">
            <div class="detail-item" *ngFor="let it of selectedOrder.items; let j = index">
              <span class="di-num">{{ j + 1 }}</span>
              <img [src]="getImg(it.productImage || it.product?.imageUrl || it.product?.mainImage)"
                   class="di-img" onerror="this.src='assets/images/no-image.svg'">
              <div class="di-info">
                <div class="di-name">{{ it.productName || it.product?.name || 'Sản phẩm' }}</div>
                <div class="di-meta">{{ formatPrice(it.unitPrice || it.price) }} × {{ it.quantity }}</div>
              </div>
              <div class="di-total">{{ formatPrice((it.unitPrice || it.price) * it.quantity) }}</div>
              <!-- Review button in detail modal -->
              <div class="di-review" *ngIf="selectedOrder.status === 'Completed'">
                <button class="btn-review-sm" *ngIf="!isItemReviewed(selectedOrder, it)"
                        (click)="openReviewModal(selectedOrder, it)">
                  <i class="fas fa-star"></i> Đánh giá
                </button>
                <span class="reviewed-badge-sm" *ngIf="isItemReviewed(selectedOrder, it)">
                  <i class="fas fa-check-circle"></i> Đã đánh giá
                </span>
              </div>
            </div>
          </div>
          <div class="detail-summary">
            <div class="summary-row" *ngIf="selectedOrder.subtotal">
              <span>Tạm tính:</span><span>{{ formatPrice(selectedOrder.subtotal) }}</span>
            </div>
            <div class="summary-row" *ngIf="selectedOrder.shippingFee">
              <span>Phí vận chuyển:</span><span>{{ formatPrice(selectedOrder.shippingFee) }}</span>
            </div>
            <div class="summary-row" *ngIf="selectedOrder.discount">
              <span>Giảm giá:</span><span style="color:#dc3545">-{{ formatPrice(selectedOrder.discount) }}</span>
            </div>
            <div class="summary-row total-row">
              <span>Tổng cộng:</span><span>{{ formatPrice(selectedOrder.totalAmount) }}</span>
            </div>
          </div>
        </div>
        <div class="modal-footer-detail">
          <button class="btn-secondary" (click)="selectedOrder=null">Đóng</button>
        </div>
      </div>
    </div>

    <!-- Review Modal -->
    <div class="modal-overlay review-overlay" *ngIf="showReviewModal" (click)="closeReviewModal()">
      <div class="review-modal" (click)="$event.stopPropagation()">
        <button class="close-btn" (click)="closeReviewModal()">&times;</button>
        <h3><i class="fas fa-star"></i> Đánh giá sản phẩm</h3>

        <div class="review-product-info" *ngIf="reviewingItem">
          <img [src]="getImg(reviewingItem.productImage || reviewingItem.product?.imageUrl || reviewingItem.product?.mainImage)"
               class="review-product-img" onerror="this.src='assets/images/no-image.svg'">
          <div class="review-product-name">{{ reviewingItem.productName || reviewingItem.product?.name }}</div>
        </div>

        <div class="stars-input" (mouseleave)="resetHover()">
          <span *ngFor="let star of [1,2,3,4,5]"
                [class]="getStarClass(star)"
                (click)="setRating(star)"
                (mouseenter)="setHoverRating(star)">
            ★
          </span>
        </div>
        <div class="rating-label" [ngClass]="'rating-' + (hoverRating || reviewRating)">
          {{ getRatingLabel() }}
        </div>

        <textarea [(ngModel)]="reviewComment"
                  placeholder="Chia sẻ trải nghiệm của bạn về sản phẩm này..."
                  rows="4"
                  class="review-textarea"></textarea>

        <button class="btn-submit-review" (click)="submitReview()" [disabled]="reviewSubmitting">
          <i class="fas fa-paper-plane" *ngIf="!reviewSubmitting"></i>
          <i class="fas fa-spinner fa-spin" *ngIf="reviewSubmitting"></i>
          {{ reviewSubmitting ? 'Đang gửi...' : 'Gửi đánh giá' }}
        </button>
      </div>
    </div>
  </div>
</div>

// ume-react/src/pages/my-orders/MyOrders.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { orderApi, reviewApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import api from '../../services/api';
import toast from 'react-hot-toast';
import './MyOrders.scss';

const formatPrice = (p: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(p);
const formatDate = (d: string) => new Date(d).toLocaleDateString('vi-VN', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' });

const statuses = [
  { value: '', label: 'Tất cả' }, { value: 'Pending', label: 'Chờ xác nhận' },
  { value: 'Confirmed', label: 'Đã xác nhận' }, { value: 'Processing', label: 'Đang xử lý' },
  { value: 'Shipping', label: 'Đang giao' }, { value: 'Completed', label: 'Hoàn thành' },
  { value: 'Cancelled', label: 'Đã hủy' },
];
const statusLabels: any = { Pending: 'Chờ xác nhận', Confirmed: 'Đã xác nhận', Processing: 'Đang xử lý', Shipping: 'Đang giao', Completed: 'Hoàn thành', Cancelled: 'Đã hủy' };
const ratingLabels: any = { 1: 'Rất không hài lòng', 2: 'Không hài lòng', 3: 'Bình thường', 4: 'Hài lòng', 5: 'Rất hài lòng' };

export default function MyOrders() {
  const [orders, setOrders] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedStatus, setSelectedStatus] = useState('');
  const [cancellingId, setCancellingId] = useState<string | null>(null);
  const [cancelReason, setCancelReason] = useState('');
  const [selectedOrder, setSelectedOrder] = useState<any>(null);

  // Review
  const [showReview, setShowReview] = useState(false);
  const [reviewOrder, setReviewOrder] = useState<any>(null);
  const [reviewItem, setReviewItem] = useState<any>(null);
  const [reviewRating, setReviewRating] = useState(5);
  const [reviewComment, setReviewComment] = useState('');
  const [reviewSubmitting, setReviewSubmitting] = useState(false);
  const [hoverRating, setHoverRating] = useState(0);
  const [reviewedMap, setReviewedMap] = useState<Record<string, string[]>>({});

  useEffect(() => { loadOrders(); }, []);

  const loadOrders = async (status?: string) => {
    setLoading(true);
    try {
      const params: any = {};
      const s = status ?? selectedStatus;
      if (s) params.status = s;
      const r = await orderApi.getMyOrders(params);
      const list = r.data?.data?.orders || r.data?.data?.items || (Array.isArray(r.data?.data) ? r.data.data : []);
      setOrders(list);
      list.forEach((o: any) => { if (o.status === 'Completed') checkReviews(o._id); });
    } catch {} finally { setLoading(false); }
  };

  const checkReviews = async (orderId: string) => {
    try {
      const r = await api.get(`/reviews/check-order/${orderId}`);
      setReviewedMap(m => ({ ...m, [orderId]: r.data?.data?.reviewedProductIds || [] }));
    } catch {}
  };

  const isItemReviewed = (order: any, item: any) => {
    const reviewed = reviewedMap[order._id] || [];
    const pid = item.product?._id || item.product;
    return pid ? reviewed.includes(pid.toString()) : false;
  };

  const filterByStatus = (s: string) => { setSelectedStatus(s); loadOrders(s); };

  const confirmCancel = async () => {
    if (!cancellingId) return;
    try {
      await orderApi.cancel(cancellingId, { cancelReason });
      toast.success('Đã hủy đơn hàng thành công');
      setCancellingId(null);
      loadOrders();
    } catch (err: any) { toast.error(err.response?.data?.message || 'Hủy thất bại'); }
  };

  const viewOrder = async (order: any) => {
    try {
      const r = await orderApi.getById(order._id);
      setSelectedOrder(r.data?.data?.order || r.data?.data || order);
    } catch { setSelectedOrder(order); }
  };

  const openReview = (order: any, item: any) => {
    setReviewOrder(order); setReviewItem(item); setReviewRating(5); setReviewComment(''); setHoverRating(0); setShowReview(true);
  };

  const submitReview = async () => {
    if (!reviewOrder || !reviewItem) return;
    setReviewSubmitting(true);
    try {
      const pid = reviewItem.product?._id || reviewItem.product;
      const fd = new FormData();
      fd.append('productId', pid);
      fd.append('orderId', reviewOrder._id);
      fd.append('rating', reviewRating.toString());
      fd.append('comment', reviewComment);
      await reviewApi.create(fd);
      toast.success('Cảm ơn bạn đã đánh giá!');
      setReviewedMap(m => ({ ...m, [reviewOrder._id]: [...(m[reviewOrder._id] || []), pid] }));
      setShowReview(false);
    } catch (err: any) { toast.error(err.response?.data?.message || 'Gửi đánh giá thất bại'); }
    finally { setReviewSubmitting(false); }
  };

  const activeRating = hoverRating || reviewRating;

  return (
    <div className="my-orders-page">
      <div className="page-header"><div className="container"><h1>🛍️ Đơn hàng của tôi</h1></div></div>
      <div className="container">
        <div className="status-tabs">
          {statuses.map(s => (
            <button key={s.value} className={selectedStatus === s.value ? 'active' : ''} onClick={() => filterByStatus(s.value)}>{s.label}</button>
          ))}
        </div>

        {loading && <div className="loading-center">⏳ Đang tải...</div>}

        {!loading && orders.length === 0 && (
          <div className="empty-state">📭<p>Bạn chưa có đơn hàng nào</p><Link to="/products" className="btn-shop">Mua sắm ngay</Link></div>
        )}

        <div className="orders-list">
          {orders.map(order => (
            <div key={order._id} className="order-card">
              <div className="card-header">
                <div className="order-code">🧾 {order.orderCode}</div>
                <span className={`status-badge ${order.status?.toLowerCase()}`}>{statusLabels[order.status] || order.status}</span>
              </div>
              <div className="card-body">
                <div className="order-items">
                  {(order.items || []).slice(0, 3).map((item: any, i: number) => (
                    <div key={i} className="order-item">
                      <img src={getImageUrl(item.productImage || item.product?.imageUrl || item.product?.mainImage)} alt="" onError={e => { (e.target as HTMLImageElement).src = '/assets/images/no-image.svg'; }} />
                      <div className="item-info"><span className="item-name">{item.productName || item.product?.name}</span><span className="item-qty">x{item.quantity} · {formatPrice(item.unitPrice || item.price)}</span></div>
                    </div>
                  ))}
                  {(order.items?.length || 0) > 3 && <div className="more-items">... và {order.items.length - 3} sản phẩm khác</div>}
                </div>
                <div className="order-meta"><span>🕐 {formatDate(order.createdAt)}</span>{order.paymentMethod && <span>💳 {order.paymentMethod === 'COD' ? 'COD' : 'Chuyển khoản'}</span>}</div>
              </div>
              <div className="card-footer">
                <span className="total-amount">Tổng: <strong>{formatPrice(order.totalAmount)}</strong></span>
                <div className="footer-actions">
                  <button className="btn-detail" onClick={() => viewOrder(order)}>👁️ Chi tiết</button>
                  {(order.status === 'Pending' || order.status === 'Confirmed') && <button className="btn-cancel" onClick={() => { setCancellingId(order._id); setCancelReason(''); }}>❌ Hủy đơn</button>}
                  {order.status === 'Completed' && (order.items || []).map((item: any, i: number) => (
                    !isItemReviewed(order, item) ? <button key={i} className="btn-review" onClick={() => openReview(order, item)}>⭐ Đánh giá {item.productName || item.product?.name}</button>
                    : <span key={i} className="reviewed-badge">✅ Đã đánh giá {item.productName || item.product?.name}</span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Cancel Modal */}
        {cancellingId && (
          <div className="modal-overlay" onClick={() => setCancellingId(null)}>
            <div className="modal-content" onClick={e => e.stopPropagation()}>
              <h3>Hủy đơn hàng</h3><p>Bạn có chắc muốn hủy đơn hàng này?</p>
              <textarea value={cancelReason} onChange={e => setCancelReason(e.target.value)} placeholder="Lý do hủy..." rows={3} />
              <div className="modal-actions"><button className="btn-secondary" onClick={() => setCancellingId(null)}>Đóng</button><button className="btn-danger" onClick={confirmCancel}>Xác nhận hủy</button></div>
            </div>
          </div>
        )}

        {/* Order Detail Modal */}
        {selectedOrder && (
          <div className="modal-overlay" onClick={() => setSelectedOrder(null)}>
            <div className="modal-detail" onClick={e => e.stopPropagation()}>
              <div className="modal-header-detail"><h3>🧾 Chi tiết đơn hàng #{selectedOrder.orderCode}</h3><button onClick={() => setSelectedOrder(null)}>×</button></div>
              <div className="modal-body-detail">
                <div className="detail-grid">
                  <div><label>Trạng thái</label><span className={`status-badge ${selectedOrder.status?.toLowerCase()}`}>{statusLabels[selectedOrder.status] || selectedOrder.status}</span></div>
                  <div><label>Ngày đặt</label><span>{formatDate(selectedOrder.createdAt)}</span></div>
                  <div><label>Thanh toán</label><span>{selectedOrder.paymentMethod || 'COD'} — {selectedOrder.paymentStatus === 'Paid' ? 'Đã thanh toán' : 'Chưa thanh toán'}</span></div>
                  <div className="full-w"><label>Địa chỉ giao hàng</label><span>{typeof selectedOrder.shippingAddress === 'string' ? selectedOrder.shippingAddress : [selectedOrder.shippingAddress?.address, selectedOrder.shippingAddress?.ward, selectedOrder.shippingAddress?.district, selectedOrder.shippingAddress?.city].filter(Boolean).join(', ')}</span></div>
                </div>
                <h4>📦 Sản phẩm ({selectedOrder.items?.length || 0})</h4>
                <div className="detail-items">
                  {(selectedOrder.items || []).map((it: any, j: number) => (
                    <div key={j} className="detail-item">
                      <span className="di-num">{j + 1}</span>
                      <img src={getImageUrl(it.productImage || it.product?.imageUrl)} alt="" className="di-img" onError={e => { (e.target as HTMLImageElement).src = '/assets/images/no-image.svg'; }} />
                      <div className="di-info"><div className="di-name">{it.productName || it.product?.name}</div><div className="di-meta">{formatPrice(it.unitPrice || it.price)} × {it.quantity}</div></div>
                      <div className="di-total">{formatPrice((it.unitPrice || it.price) * it.quantity)}</div>
                    </div>
                  ))}
                </div>
                <div className="detail-summary">
                  {selectedOrder.subtotal && <div className="summary-row"><span>Tạm tính:</span><span>{formatPrice(selectedOrder.subtotal)}</span></div>}
                  {selectedOrder.shippingFee && <div className="summary-row"><span>Phí vận chuyển:</span><span>{formatPrice(selectedOrder.shippingFee)}</span></div>}
                  {selectedOrder.discount && <div className="summary-row"><span>Giảm giá:</span><span style={{ color: '#dc3545' }}>-{formatPrice(selectedOrder.discount)}</span></div>}
                  <div className="summary-row total-row"><span>Tổng cộng:</span><span>{formatPrice(selectedOrder.totalAmount)}</span></div>
                </div>
              </div>
              <div className="modal-footer-detail"><button className="btn-secondary" onClick={() => setSelectedOrder(null)}>Đóng</button></div>
            </div>
          </div>
        )}

        {/* Review Modal */}
        {showReview && (
          <div className="modal-overlay" onClick={() => setShowReview(false)}>
            <div className="review-modal" onClick={e => e.stopPropagation()}>
              <button className="close-btn" onClick={() => setShowReview(false)}>×</button>
              <h3>⭐ Đánh giá sản phẩm</h3>
              {reviewItem && (
                <div className="review-product"><img src={getImageUrl(reviewItem.productImage || reviewItem.product?.imageUrl)} alt="" /><span>{reviewItem.productName || reviewItem.product?.name}</span></div>
              )}
              <div className="stars-input" onMouseLeave={() => setHoverRating(0)}>
                {[1,2,3,4,5].map(s => (
                  <span key={s} className={s <= activeRating ? 'star active' : 'star'} onClick={() => setReviewRating(s)} onMouseEnter={() => setHoverRating(s)}>★</span>
                ))}
              </div>
              <div className="rating-label">{ratingLabels[activeRating]}</div>
              <textarea value={reviewComment} onChange={e => setReviewComment(e.target.value)} placeholder="Chia sẻ trải nghiệm..." rows={4} />
              <button className="btn-submit-review" onClick={submitReview} disabled={reviewSubmitting}>{reviewSubmitting ? '⏳ Đang gửi...' : '📩 Gửi đánh giá'}</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
