// ume-frontend/src/app/pages/my-pets/my-pets.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-my-pets',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './my-pets.component.html',
  styleUrl: './my-pets.component.scss'
})
export class MyPetsComponent implements OnInit {
  pets: any[] = [];
  loading = false;

  showModal = false;
  editingPet: any = null;
  petForm: any = {
    name: '',
    type: 'Dog',
    breed: '',
    age: null,
    ageUnit: 'months',
    weight: null,
    gender: 'Male',
    color: '',
    description: '',
    healthNotes: '',
    vaccinated: false,
    neutered: false,
    listingType: 'None',
    listingPrice: 0,
    listingDescription: ''
  };
  selectedImage: File | null = null;
  imagePreview: string | null = null;
  submitting = false;

  petTypes = [
    { value: 'Dog', label: 'Chó' },
    { value: 'Cat', label: 'Mèo' },
    { value: 'Bird', label: 'Chim' },
    { value: 'Fish', label: 'Cá' },
    { value: 'Hamster', label: 'Hamster' },
    { value: 'Rabbit', label: 'Thỏ' },
    { value: 'Other', label: 'Khác' }
  ];
  genderOptions = [
    { value: 'Male', label: 'Đực' },
    { value: 'Female', label: 'Cái' },
    { value: 'Unknown', label: 'Chưa rõ' }
  ];
  ageUnits = [
    { value: 'months', label: 'Tháng' },
    { value: 'years', label: 'Năm' }
  ];
  listingTypes = [
    { value: 'None', label: 'Không đăng' },
    { value: 'Sale', label: 'Đăng bán' },
    { value: 'Adoption', label: 'Cho nhận nuôi' }
  ];

  constructor(
    private apiService: ApiService,
    private toastr: ToastrService
  ) {}

  getImg(path: string): string { return this.apiService.getImageUrl(path); }

  ngOnInit(): void {
    this.loadPets();
  }

  loadPets(): void {
    this.loading = true;
    this.apiService.getMyPets().subscribe({
      next: (res: any) => {
        this.pets = res.data?.pets || res.data || [];
        this.loading = false;
      },
      error: () => { this.loading = false; }
    });
  }

  openAddModal(): void {
    this.editingPet = null;
    this.petForm = {
      name: '', type: 'Dog', breed: '', age: null, ageUnit: 'months',
      weight: null, gender: 'Male', color: '', description: '',
      healthNotes: '', vaccinated: false, neutered: false,
      listingType: 'None', listingPrice: 0, listingDescription: ''
    };
    this.selectedImage = null;
    this.imagePreview = null;
    this.showModal = true;
  }

  openEditModal(pet: any): void {
    this.editingPet = pet;
    this.petForm = {
      name: pet.name, type: pet.type, breed: pet.breed,
      age: pet.age, ageUnit: pet.ageUnit || 'months',
      weight: pet.weight, gender: pet.gender, color: pet.color,
      description: pet.description, healthNotes: pet.healthNotes,
      vaccinated: pet.vaccinated, neutered: pet.neutered,
      listingType: pet.listingType || 'None', listingPrice: pet.listingPrice || 0,
      listingDescription: pet.listingDescription || ''
    };
    this.selectedImage = null;
    this.imagePreview = pet.imageUrl ? this.getImg(pet.imageUrl) : null;
    this.showModal = true;
  }

  closeModal(): void {
    this.showModal = false;
  }

  onImageSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files[0]) {
      this.selectedImage = input.files[0];
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.imagePreview = e.target.result;
      };
      reader.readAsDataURL(input.files[0]);
    }
  }

  savePet(): void {
    if (!this.petForm.name) {
      this.toastr.warning('Vui lòng nhập tên thú cưng', 'Thông báo');
      return;
    }

    this.submitting = true;
    const formData = new FormData();
    Object.keys(this.petForm).forEach(key => {
      if (this.petForm[key] !== null && this.petForm[key] !== undefined) {
        formData.append(key, this.petForm[key].toString());
      }
    });
    if (this.selectedImage) {
      formData.append('image', this.selectedImage);
    }

    const request = this.editingPet
      ? this.apiService.updatePet(this.editingPet._id, formData)
      : this.apiService.createPet(formData);

    request.subscribe({
      next: () => {
        this.submitting = false;
        this.showModal = false;
        this.toastr.success(
          this.editingPet ? 'Cập nhật thú cưng thành công!' : 'Thêm thú cưng thành công!',
          'Thành công'
        );
        this.loadPets();
      },
      error: (err: any) => {
        this.submitting = false;
        this.toastr.error(err.error?.message || 'Thao tác thất bại', 'Lỗi');
      }
    });
  }

  deletePet(pet: any): void {
    if (!confirm(`Bạn có chắc muốn xóa ${pet.name}?`)) return;
    this.apiService.deletePet(pet._id).subscribe({
      next: () => {
        this.toastr.success('Đã xóa thú cưng', 'Thành công');
        this.loadPets();
      },
      error: (err: any) => {
        this.toastr.error(err.error?.message || 'Xóa thất bại', 'Lỗi');
      }
    });
  }

  getAgeLabel(pet: any): string {
    if (!pet.age) return 'Không rõ';
    const unit = pet.ageUnit === 'years' ? 'tuổi' : 'tháng';
    return `${pet.age} ${unit}`;
  }

  getTypeName(type: string): string {
    const m: any = { Dog: 'Chó', Cat: 'Mèo', Bird: 'Chim', Fish: 'Cá', Hamster: 'Hamster', Rabbit: 'Thỏ', Other: 'Khác' };
    return m[type] || type;
  }

  getGenderName(g: string): string {
    const m: any = { Male: 'Đực', Female: 'Cái', Unknown: 'Chưa rõ' };
    return m[g] || g;
  }

  getListingLabel(t: string): string {
    const m: any = { None: 'Không đăng', Sale: 'Đang bán', Adoption: 'Cho nhận nuôi' };
    return m[t] || '';
  }
}

<div class="my-pets-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-paw"></i> Thú cưng của tôi</h1>
    </div>
  </div>

  <div class="container">
    <div class="toolbar">
      <span>{{ pets.length }} thú cưng</span>
      <button class="btn-add" (click)="openAddModal()">
        <i class="fas fa-plus"></i> Thêm thú cưng
      </button>
    </div>

    <div class="loading-spinner" *ngIf="loading">
      <i class="fas fa-spinner fa-spin"></i> Đang tải...
    </div>

    <div class="pets-grid" *ngIf="!loading">
      <div class="pet-card" *ngFor="let pet of pets">
        <div class="pet-image">
          <img [src]="getImg(pet.imageUrl) || 'assets/images/default-pet.svg'" [alt]="pet.name">
        </div>
        <div class="pet-info">
          <h3>{{ pet.name }}</h3>
          <div class="pet-details">
            <span><i class="fas fa-paw"></i> {{ getTypeName(pet.type) }}</span>
            <span *ngIf="pet.breed"><i class="fas fa-dna"></i> {{ pet.breed }}</span>
            <span><i class="fas fa-birthday-cake"></i> {{ getAgeLabel(pet) }}</span>
            <span *ngIf="pet.weight"><i class="fas fa-weight"></i> {{ pet.weight }} kg</span>
            <span><i class="fas fa-venus-mars"></i> {{ getGenderName(pet.gender) }}</span>
          </div>
          <div class="pet-tags">
            <span class="tag success" *ngIf="pet.vaccinated"><i class="fas fa-syringe"></i> Đã tiêm phòng</span>
            <span class="tag success" *ngIf="pet.neutered"><i class="fas fa-cut"></i> Đã triệt sản</span>
            <span class="tag sale" *ngIf="false && pet.listingType==='Sale'"><i class="fas fa-tag"></i> Đang bán <span *ngIf="pet.listingPrice">- {{pet.listingPrice | number:'1.0-0'}}đ</span></span>
            <span class="tag adoption" *ngIf="false && pet.listingType==='Adoption'"><i class="fas fa-heart"></i> Cho nhận nuôi</span>
          </div>
          <p class="pet-desc" *ngIf="pet.description">{{ pet.description }}</p>
          <div class="pet-actions">
            <button class="btn-edit" (click)="openEditModal(pet)">
              <i class="fas fa-edit"></i> Sửa
            </button>
            <button class="btn-delete" (click)="deletePet(pet)">
              <i class="fas fa-trash"></i> Xóa
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="empty-state" *ngIf="!loading && pets.length === 0">
      <i class="fas fa-paw"></i>
      <p>Bạn chưa thêm thú cưng nào</p>
      <button class="btn-add-first" (click)="openAddModal()">
        <i class="fas fa-plus"></i> Thêm thú cưng đầu tiên
      </button>
    </div>

    <!-- Add/Edit Modal -->
    <div class="modal-overlay" *ngIf="showModal" (click)="closeModal()">
      <div class="modal-content" (click)="$event.stopPropagation()">
        <div class="modal-header">
          <h3>{{ editingPet ? 'Chỉnh sửa thú cưng' : 'Thêm thú cưng mới' }}</h3>
          <button class="btn-close" (click)="closeModal()"><i class="fas fa-times"></i></button>
        </div>
        <div class="modal-body">
          <div class="image-upload" (click)="imageInput.click()">
            <img *ngIf="imagePreview" [src]="imagePreview" alt="preview">
            <div class="upload-placeholder" *ngIf="!imagePreview">
              <i class="fas fa-camera"></i>
              <span>Chọn ảnh</span>
            </div>
            <input #imageInput type="file" accept="image/*" (change)="onImageSelected($event)" hidden>
          </div>

          <div class="form-grid">
            <div class="form-group">
              <label>Tên thú cưng *</label>
              <input type="text" [(ngModel)]="petForm.name" placeholder="Nhập tên">
            </div>
            <div class="form-group">
              <label>Loại</label>
              <select [(ngModel)]="petForm.type">
                <option *ngFor="let t of petTypes" [value]="t.value">{{ t.label }}</option>
              </select>
            </div>
            <div class="form-group">
              <label>Giống</label>
              <input type="text" [(ngModel)]="petForm.breed" placeholder="Giống">
            </div>
            <div class="form-group">
              <label>Giới tính</label>
              <select [(ngModel)]="petForm.gender">
                <option *ngFor="let g of genderOptions" [value]="g.value">{{ g.label }}</option>
              </select>
            </div>
            <div class="form-group">
              <label>Tuổi</label>
              <div class="age-input">
                <input type="number" [(ngModel)]="petForm.age" placeholder="Tuổi" min="0">
                <select [(ngModel)]="petForm.ageUnit">
                  <option *ngFor="let u of ageUnits" [value]="u.value">{{ u.label }}</option>
                </select>
              </div>
            </div>
            <div class="form-group">
              <label>Cân nặng (kg)</label>
              <input type="number" [(ngModel)]="petForm.weight" placeholder="Cân nặng" min="0" step="0.1">
            </div>
            <div class="form-group">
              <label>Màu lông</label>
              <input type="text" [(ngModel)]="petForm.color" placeholder="Màu lông">
            </div>
            <div class="form-group full">
              <label>Mô tả</label>
              <textarea [(ngModel)]="petForm.description" placeholder="Mô tả thú cưng..." rows="2"></textarea>
            </div>
            <div class="form-group full">
              <label>Ghi chú sức khỏe</label>
              <textarea [(ngModel)]="petForm.healthNotes" placeholder="Tình trạng sức khỏe, dị ứng..." rows="2"></textarea>
            </div>
            <div class="form-group checkbox-group">
              <label>
                <input type="checkbox" [(ngModel)]="petForm.vaccinated">
                Đã tiêm phòng
              </label>
            </div>
            <div class="form-group checkbox-group">
              <label>
                <input type="checkbox" [(ngModel)]="petForm.neutered">
                Đã triệt sản
              </label>
            </div>

            <div class="listing-section full" *ngIf="false">
              <h4><i class="fas fa-store"></i> Đăng bán / Nhận nuôi</h4>
              <div class="form-grid">
                <div class="form-group">
                  <label>Hình thức</label>
                  <select [(ngModel)]="petForm.listingType">
                    <option *ngFor="let lt of listingTypes" [value]="lt.value">{{ lt.label }}</option>
                  </select>
                </div>
                <div class="form-group" *ngIf="petForm.listingType==='Sale'">
                  <label>Giá (VNĐ)</label>
                  <input type="number" [(ngModel)]="petForm.listingPrice" placeholder="Nhập giá" min="0">
                </div>
                <div class="form-group full">
                  <label>Mô tả cho người mua</label>
                  <textarea [(ngModel)]="petForm.listingDescription" placeholder="Thông tin chi tiết cho người quan tâm..." rows="2"></textarea>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn-secondary" (click)="closeModal()">Hủy</button>
          <button class="btn-primary" (click)="savePet()" [disabled]="submitting">
            <i class="fas" [class.fa-save]="!submitting" [class.fa-spinner]="submitting" [class.fa-spin]="submitting"></i>
            {{ submitting ? 'Đang lưu...' : (editingPet ? 'Cập nhật' : 'Thêm mới') }}
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

// ume-react/src/pages/my-pets/MyPets.tsx
import { useState, useEffect } from 'react';
import { petApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import toast from 'react-hot-toast';
import './MyPets.scss';

const petTypes = [
  { value: 'Dog', label: 'Chó' }, { value: 'Cat', label: 'Mèo' }, { value: 'Bird', label: 'Chim' },
  { value: 'Fish', label: 'Cá' }, { value: 'Hamster', label: 'Hamster' }, { value: 'Rabbit', label: 'Thỏ' },
  { value: 'Other', label: 'Khác' },
];
const genderOptions = [{ value: 'Male', label: 'Đực' }, { value: 'Female', label: 'Cái' }, { value: 'Unknown', label: 'Chưa rõ' }];
const ageUnits = [{ value: 'months', label: 'Tháng' }, { value: 'years', label: 'Năm' }];

const typeNames: any = { Dog: 'Chó', Cat: 'Mèo', Bird: 'Chim', Fish: 'Cá', Hamster: 'Hamster', Rabbit: 'Thỏ', Other: 'Khác' };
const genderNames: any = { Male: 'Đực', Female: 'Cái', Unknown: 'Chưa rõ' };

const defaultForm = { name: '', type: 'Dog', breed: '', age: '', ageUnit: 'months', weight: '', gender: 'Male', color: '', description: '', healthNotes: '', vaccinated: false, neutered: false };

export default function MyPets() {
  const [pets, setPets] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [editingPet, setEditingPet] = useState<any>(null);
  const [form, setForm] = useState<any>({ ...defaultForm });
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => { loadPets(); }, []);

  const loadPets = async () => {
    setLoading(true);
    try {
      const r = await petApi.getMyPets();
      setPets(r.data?.data?.pets || r.data?.data || []);
    } catch {} finally { setLoading(false); }
  };

  const openAdd = () => { setEditingPet(null); setForm({ ...defaultForm }); setImageFile(null); setImagePreview(null); setShowModal(true); };
  const openEdit = (pet: any) => {
    setEditingPet(pet);
    setForm({ name: pet.name, type: pet.type, breed: pet.breed || '', age: pet.age || '', ageUnit: pet.ageUnit || 'months', weight: pet.weight || '', gender: pet.gender, color: pet.color || '', description: pet.description || '', healthNotes: pet.healthNotes || '', vaccinated: pet.vaccinated || false, neutered: pet.neutered || false });
    setImageFile(null);
    setImagePreview(pet.imageUrl ? getImageUrl(pet.imageUrl) : null);
    setShowModal(true);
  };

  const onImageSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0];
    if (!f) return;
    setImageFile(f);
    const reader = new FileReader();
    reader.onload = ev => setImagePreview(ev.target?.result as string);
    reader.readAsDataURL(f);
  };

  const savePet = async () => {
    if (!form.name) { toast.error('Vui lòng nhập tên thú cưng'); return; }
    setSubmitting(true);
    try {
      const fd = new FormData();
      Object.keys(form).forEach(k => { if (form[k] !== null && form[k] !== undefined && form[k] !== '') fd.append(k, form[k].toString()); });
      if (imageFile) fd.append('image', imageFile);
      if (editingPet) {
        await petApi.update(editingPet._id, fd);
        toast.success('Cập nhật thú cưng thành công!');
      } else {
        await petApi.create(fd);
        toast.success('Thêm thú cưng thành công!');
      }
      setShowModal(false);
      loadPets();
    } catch (err: any) { toast.error(err.response?.data?.message || 'Thao tác thất bại'); }
    finally { setSubmitting(false); }
  };

  const deletePet = async (pet: any) => {
    if (!window.confirm(`Bạn có chắc muốn xóa ${pet.name}?`)) return;
    try { await petApi.delete(pet._id); toast.success('Đã xóa thú cưng'); loadPets(); }
    catch (err: any) { toast.error(err.response?.data?.message || 'Xóa thất bại'); }
  };

  const getAgeLabel = (pet: any) => pet.age ? `${pet.age} ${pet.ageUnit === 'years' ? 'tuổi' : 'tháng'}` : 'Không rõ';

  return (
    <div className="my-pets-page">
      <div className="page-header"><div className="container"><h1>🐾 Thú cưng của tôi</h1></div></div>
      <div className="container">
        <div className="toolbar"><span>{pets.length} thú cưng</span><button className="btn-add" onClick={openAdd}>➕ Thêm thú cưng</button></div>

        {loading && <div className="loading-center">⏳ Đang tải...</div>}
        {!loading && pets.length === 0 && (
          <div className="empty-state">🐾<p>Bạn chưa thêm thú cưng nào</p><button className="btn-add-first" onClick={openAdd}>➕ Thêm thú cưng đầu tiên</button></div>
        )}

        <div className="pets-grid">
          {pets.map(pet => (
            <div key={pet._id} className="pet-card">
              <div className="pet-image"><img src={getImageUrl(pet.imageUrl) || '/assets/images/default-pet.svg'} alt={pet.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/default-pet.svg'; }} /></div>
              <div className="pet-info">
                <h3>{pet.name}</h3>
                <div className="pet-details">
                  <span>🐾 {typeNames[pet.type] || pet.type}</span>
                  {pet.breed && <span>🧬 {pet.breed}</span>}
                  <span>🎂 {getAgeLabel(pet)}</span>
                  {pet.weight && <span>⚖️ {pet.weight} kg</span>}
                  <span>{pet.gender === 'Male' ? '♂️' : '♀️'} {genderNames[pet.gender] || pet.gender}</span>
                </div>
                <div className="pet-tags">
                  {pet.vaccinated && <span className="tag success">💉 Đã tiêm phòng</span>}
                  {pet.neutered && <span className="tag success">✂️ Đã triệt sản</span>}
                </div>
                {pet.description && <p className="pet-desc">{pet.description}</p>}
                <div className="pet-actions">
                  <button className="btn-edit" onClick={() => openEdit(pet)}>✏️ Sửa</button>
                  <button className="btn-delete" onClick={() => deletePet(pet)}>🗑️ Xóa</button>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Modal */}
        {showModal && (
          <div className="modal-overlay" onClick={() => setShowModal(false)}>
            <div className="modal-content" onClick={e => e.stopPropagation()}>
              <div className="modal-header"><h3>{editingPet ? 'Chỉnh sửa thú cưng' : 'Thêm thú cưng mới'}</h3><button className="btn-close" onClick={() => setShowModal(false)}>×</button></div>
              <div className="modal-body">
                <div className="image-upload" onClick={() => document.getElementById('pet-img-input')?.click()}>
                  {imagePreview ? <img src={imagePreview} alt="preview" /> : <div className="upload-placeholder">📷<span>Chọn ảnh</span></div>}
                  <input id="pet-img-input" type="file" accept="image/*" onChange={onImageSelect} hidden />
                </div>
                <div className="form-grid">
                  <div className="form-group"><label>Tên *</label><input value={form.name} onChange={e => setForm((f: any) => ({ ...f, name: e.target.value }))} /></div>
                  <div className="form-group"><label>Loại</label><select value={form.type} onChange={e => setForm((f: any) => ({ ...f, type: e.target.value }))}>{petTypes.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}</select></div>
                  <div className="form-group"><label>Giống</label><input value={form.breed} onChange={e => setForm((f: any) => ({ ...f, breed: e.target.value }))} /></div>
                  <div className="form-group"><label>Giới tính</label><select value={form.gender} onChange={e => setForm((f: any) => ({ ...f, gender: e.target.value }))}>{genderOptions.map(g => <option key={g.value} value={g.value}>{g.label}</option>)}</select></div>
                  <div className="form-group"><label>Tuổi</label>
                    <div className="age-input"><input type="number" value={form.age} onChange={e => setForm((f: any) => ({ ...f, age: e.target.value }))} min={0} /><select value={form.ageUnit} onChange={e => setForm((f: any) => ({ ...f, ageUnit: e.target.value }))}>{ageUnits.map(u => <option key={u.value} value={u.value}>{u.label}</option>)}</select></div>
                  </div>
                  <div className="form-group"><label>Cân nặng (kg)</label><input type="number" value={form.weight} onChange={e => setForm((f: any) => ({ ...f, weight: e.target.value }))} min={0} step={0.1} /></div>
                  <div className="form-group"><label>Màu lông</label><input value={form.color} onChange={e => setForm((f: any) => ({ ...f, color: e.target.value }))} /></div>
                  <div className="form-group full"><label>Mô tả</label><textarea value={form.description} onChange={e => setForm((f: any) => ({ ...f, description: e.target.value }))} rows={2} /></div>
                  <div className="form-group full"><label>Ghi chú sức khỏe</label><textarea value={form.healthNotes} onChange={e => setForm((f: any) => ({ ...f, healthNotes: e.target.value }))} rows={2} /></div>
                  <div className="form-group checkbox-group"><label><input type="checkbox" checked={form.vaccinated} onChange={e => setForm((f: any) => ({ ...f, vaccinated: e.target.checked }))} /> Đã tiêm phòng</label></div>
                  <div className="form-group checkbox-group"><label><input type="checkbox" checked={form.neutered} onChange={e => setForm((f: any) => ({ ...f, neutered: e.target.checked }))} /> Đã triệt sản</label></div>
                </div>
              </div>
              <div className="modal-footer"><button className="btn-secondary" onClick={() => setShowModal(false)}>Hủy</button><button className="btn-primary" onClick={savePet} disabled={submitting}>{submitting ? '⏳ Đang lưu...' : (editingPet ? 'Cập nhật' : 'Thêm mới')}</button></div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
