// ume-react/src/pages/product-detail/ProductDetail.tsx
import { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { productApi, reviewApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import { useCart } from '../../contexts/CartContext';
import { useAuth } from '../../contexts/AuthContext';
import toast from 'react-hot-toast';
import './ProductDetail.scss';

const formatPrice = (price: number) =>
  new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);

const getStars = (rating: number) =>
  Array(5).fill(0).map((_, i) => (i < Math.round(rating) ? 1 : 0));

const getTimeAgo = (date: string) => {
  const diff = Date.now() - new Date(date).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins} phút trước`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs} giờ trước`;
  const days = Math.floor(hrs / 24);
  if (days < 30) return `${days} ngày trước`;
  return new Date(date).toLocaleDateString('vi-VN');
};

export default function ProductDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { addToCart } = useCart();
  const { isLoggedIn } = useAuth();

  const [product, setProduct] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [quantity, setQuantity] = useState(1);
  const [selectedImage, setSelectedImage] = useState('');
  const [allImages, setAllImages] = useState<string[]>([]);

  const [reviews, setReviews] = useState<any[]>([]);
  const [reviewPage, setReviewPage] = useState(1);
  const [reviewTotalPages, setReviewTotalPages] = useState(1);

  const [showReviewForm, setShowReviewForm] = useState(false);
  const [newRating, setNewRating] = useState(5);
  const [hoverRating, setHoverRating] = useState(0);
  const [newComment, setNewComment] = useState('');
  const [reviewImages, setReviewImages] = useState<File[]>([]);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (id) {
      loadProduct(id);
      loadReviews(id, 1);
    }
  }, [id]);

  const loadProduct = async (productId: string) => {
    setLoading(true);
    try {
      const res = await productApi.getById(productId);
      const p = res.data?.data || res.data;
      setProduct(p);
      const imgs: string[] = [];
      if (p.imageUrl) imgs.push(p.imageUrl);
      if (p.images?.length) imgs.push(...p.images);
      setAllImages(imgs);
      setSelectedImage(imgs[0] || '');
    } catch {
      toast.error('Không tìm thấy sản phẩm');
      navigate('/products');
    } finally {
      setLoading(false);
    }
  };

  const loadReviews = async (productId: string, page: number) => {
    try {
      const res = await reviewApi.getByProduct(productId, { page, limit: 5 });
      const data = res.data?.data;
      if (page === 1) {
        setReviews(data?.reviews || []);
      } else {
        setReviews(prev => [...prev, ...(data?.reviews || [])]);
      }
      setReviewPage(page);
      setReviewTotalPages(data?.pagination?.pages || 1);
    } catch {
      if (page === 1) setReviews([]);
    }
  };

  const handleAddToCart = () => {
    if (!product) return;
    addToCart(product, quantity);
    toast.success(`Đã thêm ${product.name} vào giỏ hàng!`);
  };

  const getDiscountPercent = () => {
    if (!product?.discountPrice || product.discountPrice >= product.price) return 0;
    return Math.round((1 - product.discountPrice / product.price) * 100);
  };

  const handleSubmitReview = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!isLoggedIn) { toast.error('Vui lòng đăng nhập'); navigate('/login'); return; }
    if (!newComment.trim()) { toast.error('Vui lòng nhập nội dung đánh giá'); return; }
    setSubmitting(true);
    try {
      const formData = new FormData();
      formData.append('productId', id!);
      formData.append('rating', String(newRating));
      formData.append('comment', newComment);
      reviewImages.forEach(f => formData.append('images', f));
      await reviewApi.create(formData);
      toast.success('Đánh giá thành công!');
      setShowReviewForm(false);
      setNewComment('');
      setNewRating(5);
      setReviewImages([]);
      loadReviews(id!, 1);
      loadProduct(id!);
    } catch {
      toast.error('Lỗi khi gửi đánh giá');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return (
    <div className="loading-state"><div className="spinner"></div><p>Đang tải sản phẩm...</p></div>
  );

  if (!product) return null;

  const displayPrice = product.discountPrice && product.discountPrice < product.price ? product.discountPrice : product.price;

  return (
    <div className="product-detail-page">
      <div className="container">
        {/* Breadcrumb */}
        <div className="breadcrumb">
          <Link to="/">Trang chủ</Link>
          <span>/</span>
          <Link to="/products">Sản phẩm</Link>
          <span>/</span>
          <span>{product.name}</span>
        </div>

        <div className="product-detail-content">
          {/* Image Gallery */}
          <div className="image-gallery">
            <div className="main-image">
              <img src={getImageUrl(selectedImage)} alt={product.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/no-product.svg'; }} />
              {getDiscountPercent() > 0 && <span className="discount-badge">-{getDiscountPercent()}%</span>}
            </div>
            {allImages.length > 1 && (
              <div className="thumbnails">
                {allImages.map((img, i) => (
                  <div key={i} className={`thumb ${selectedImage === img ? 'active' : ''}`} onClick={() => setSelectedImage(img)}>
                    <img src={getImageUrl(img)} alt={`${product.name} ${i + 1}`} />
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Product Info */}
          <div className="product-info">
            {product.isHotDeal && <span className="hot-tag">🔥 Ưu đãi hot</span>}
            {product.isFeatured && <span className="featured-tag">⭐ Nổi bật</span>}
            <h1>{product.name}</h1>
            <div className="meta">
              <span className="code">SKU: {product.code || product.sku || 'N/A'}</span>
              {product.brand && <span className="brand">Thương hiệu: <strong>{typeof product.brand === 'string' ? product.brand : product.brand.name}</strong></span>}
            </div>

            <div className="rating-row">
              {getStars(product.averageRating || 0).map((s, i) => (
                <span key={i} className={s ? 'star filled' : 'star'}>★</span>
              ))}
              <span className="rating-text">{(product.averageRating || 0).toFixed(1)} ({product.totalReviews || 0} đánh giá)</span>
              <span className="sold">| Đã bán: {product.soldCount || 0}</span>
            </div>

            <div className="price-section">
              <span className="current-price">{formatPrice(displayPrice)}</span>
              {getDiscountPercent() > 0 && (
                <>
                  <span className="original-price">{formatPrice(product.price)}</span>
                  <span className="save-badge">Tiết kiệm {getDiscountPercent()}%</span>
                </>
              )}
            </div>

            <div className="stock-info">
              {product.stock > 0 ? (
                <span className="in-stock">✓ Còn hàng ({product.stock})</span>
              ) : (
                <span className="out-stock">✗ Hết hàng</span>
              )}
            </div>

            {/* Quantity */}
            <div className="quantity-section">
              <label>Số lượng:</label>
              <div className="qty-control">
                <button onClick={() => setQuantity(q => Math.max(1, q - 1))}>-</button>
                <span>{quantity}</span>
                <button onClick={() => setQuantity(q => Math.min(product.stock || 99, q + 1))}>+</button>
              </div>
            </div>

            <div className="action-buttons">
              <button className="btn-add-cart" onClick={handleAddToCart} disabled={product.stock === 0}>
                🛒 Thêm vào giỏ hàng
              </button>
              <button className="btn-buy-now" onClick={() => { handleAddToCart(); navigate('/cart'); }} disabled={product.stock === 0}>
                ⚡ Mua ngay
              </button>
            </div>
          </div>
        </div>

        {/* Description */}
        {product.description && (
          <div className="description-section">
            <h3>📋 Mô tả sản phẩm</h3>
            <div className="desc-content" dangerouslySetInnerHTML={{ __html: product.description }} />
          </div>
        )}

        {/* Reviews */}
        <div className="reviews-section">
          <div className="reviews-header">
            <h3>⭐ Đánh giá ({product.totalReviews || 0})</h3>
            {isLoggedIn && (
              <button className="btn-write-review" onClick={() => setShowReviewForm(!showReviewForm)}>
                ✍️ Viết đánh giá
              </button>
            )}
          </div>

          {showReviewForm && (
            <form className="review-form" onSubmit={handleSubmitReview}>
              <div className="rating-select">
                <label>Đánh giá:</label>
                <div className="stars-select">
                  {[1, 2, 3, 4, 5].map(s => (
                    <span key={s} className={`star ${s <= (hoverRating || newRating) ? 'filled' : ''}`}
                      onMouseEnter={() => setHoverRating(s)} onMouseLeave={() => setHoverRating(0)}
                      onClick={() => setNewRating(s)}>★</span>
                  ))}
                </div>
              </div>
              <textarea placeholder="Nhập nhận xét của bạn..." value={newComment} onChange={e => setNewComment(e.target.value)} rows={4} />
              <input type="file" multiple accept="image/*" onChange={e => setReviewImages(Array.from(e.target.files || []))} />
              <div className="form-actions">
                <button type="submit" className="btn-submit" disabled={submitting}>
                  {submitting ? 'Đang gửi...' : 'Gửi đánh giá'}
                </button>
                <button type="button" className="btn-cancel" onClick={() => setShowReviewForm(false)}>Hủy</button>
              </div>
            </form>
          )}

          {reviews.length > 0 ? (
            <div className="reviews-list">
              {reviews.map(review => (
                <div className="review-item" key={review._id}>
                  <div className="review-header">
                    <div className="reviewer">
                      <div className="avatar">{(review.userId?.name || review.userId?.fullName || 'K')[0]}</div>
                      <div>
                        <p className="name">{review.userId?.name || review.userId?.fullName || 'Khách hàng'}</p>
                        <p className="date">{getTimeAgo(review.createdAt)}</p>
                      </div>
                    </div>
                    <div className="review-stars">
                      {getStars(review.rating).map((s, i) => (
                        <span key={i} className={s ? 'star filled' : 'star'}>★</span>
                      ))}
                    </div>
                  </div>
                  <p className="review-text">{review.comment}</p>
                  {review.images?.length > 0 && (
                    <div className="review-images">
                      {review.images.map((img: string, i: number) => (
                        <img key={i} src={getImageUrl(img)} alt="Review" />
                      ))}
                    </div>
                  )}
                </div>
              ))}
              {reviewPage < reviewTotalPages && (
                <button className="btn-load-more" onClick={() => loadReviews(id!, reviewPage + 1)}>
                  Xem thêm đánh giá
                </button>
              )}
            </div>
          ) : (
            <div className="no-reviews">
              <p>💬 Chưa có đánh giá nào</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ume-frontend/src/app/pages/product-detail/product-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { CartService } from '../../services/cart.service';
import { AuthService } from '../../services/auth.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-product-detail',
  standalone: true,
  imports: [CommonModule, RouterLink, FormsModule],
  templateUrl: './product-detail.component.html',
  styleUrl: './product-detail.component.scss'
})
export class ProductDetailComponent implements OnInit {
  product: any = null;
  reviews: any[] = [];
  loading = true;
  quantity = 1;
  selectedImage = '';
  reviewPage = 1;
  reviewTotalPages = 1;

  // Write review
  showReviewForm = false;
  newReviewRating = 5;
  newReviewComment = '';
  hoverRating = 0;
  reviewSubmitting = false;

  constructor(
    private route: ActivatedRoute,
    private apiService: ApiService,
    private cartService: CartService,
    private toastr: ToastrService,
    public authService: AuthService
  ) {}

  getImg(path: string): string { return this.apiService.getImageUrl(path); }

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.loadProduct(params['id']);
      this.loadReviews(params['id']);
    });
  }

  loadProduct(id: string): void {
    this.loading = true;
    this.apiService.getProduct(id).subscribe({
      next: (res: any) => {
        this.product = res.data || res;
        this.selectedImage = this.getImg(this.product.imageUrl || this.product.mainImage);
        this.loading = false;
      },
      error: () => { this.loading = false; }
    });
  }

  loadReviews(productId: string): void {
    this.apiService.getProductReviews(productId, { page: this.reviewPage, limit: 5 }).subscribe({
      next: (res: any) => {
        this.reviews = res.data?.items || res.data || [];
        this.reviewTotalPages = res.data?.pagination?.pages || 1;
      }
    });
  }

  selectImage(img: string): void {
    this.selectedImage = img;
  }

  get allImages(): string[] {
    if (!this.product) return [];
    const imgs = [this.getImg(this.product.imageUrl || this.product.mainImage)];
    if (this.product.additionalImages) {
      imgs.push(...this.product.additionalImages.map((img: string) => this.getImg(img)));
    }
    return imgs.filter(Boolean);
  }

  increaseQty(): void {
    if (this.quantity < (this.product?.stockQuantity || 99)) this.quantity++;
  }

  decreaseQty(): void {
    if (this.quantity > 1) this.quantity--;
  }

  addToCart(): void {
    if (!this.product) return;
    this.cartService.addToCart(this.product, this.quantity);
    this.toastr.success(`Đã thêm ${this.quantity} sản phẩm vào giỏ hàng!`, 'Thành công');
  }

  getDiscountPercent(): number {
    if (!this.product?.originalPrice || this.product.originalPrice <= this.product.price) return 0;
    return Math.round((1 - this.product.price / this.product.originalPrice) * 100);
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  getStars(rating: number): number[] {
    return Array(5).fill(0).map((_, i) => i < Math.round(rating) ? 1 : 0);
  }

  getTimeAgo(date: string): string {
    const diff = Date.now() - new Date(date).getTime();
    const days = Math.floor(diff / 86400000);
    if (days < 1) return 'Hôm nay';
    if (days < 30) return `${days} ngày trước`;
    if (days < 365) return `${Math.floor(days / 30)} tháng trước`;
    return `${Math.floor(days / 365)} năm trước`;
  }

  // Review form methods
  toggleReviewForm(): void {
    this.showReviewForm = !this.showReviewForm;
    if (this.showReviewForm) {
      this.newReviewRating = 5;
      this.newReviewComment = '';
      this.hoverRating = 0;
    }
  }

  setNewRating(star: number): void {
    this.newReviewRating = star;
  }

  setHoverRating(star: number): void {
    this.hoverRating = star;
  }

  resetHover(): void {
    this.hoverRating = 0;
  }

  getNewStarClass(star: number): string {
    const active = this.hoverRating || this.newReviewRating;
    return star <= active ? 'star active' : 'star';
  }

  getNewRatingLabel(): string {
    const active = this.hoverRating || this.newReviewRating;
    const labels: { [key: number]: string } = {
      1: 'Rất không hài lòng',
      2: 'Không hài lòng',
      3: 'Bình thường',
      4: 'Hài lòng',
      5: 'Rất hài lòng'
    };
    return labels[active] || '';
  }

  submitReview(): void {
    if (!this.product) return;
    this.reviewSubmitting = true;

    const formData = new FormData();
    formData.append('productId', this.product._id);
    formData.append('rating', this.newReviewRating.toString());
    formData.append('comment', this.newReviewComment);

    this.apiService.createReview(formData).subscribe({
      next: () => {
        this.toastr.success('Cảm ơn bạn đã đánh giá!', 'Thành công');
        this.showReviewForm = false;
        this.reviewSubmitting = false;
        this.newReviewComment = '';
        this.newReviewRating = 5;
        // Reload reviews
        this.loadReviews(this.product._id);
        this.loadProduct(this.product._id);
      },
      error: (err: any) => {
        this.reviewSubmitting = false;
        this.toastr.error(err.error?.message || 'Gửi đánh giá thất bại', 'Lỗi');
      }
    });
  }
}

<div class="product-detail-page">
  <div class="container">
    <div class="breadcrumb">
      <a routerLink="/">Trang chủ</a>
      <span>/</span>
      <a routerLink="/products">Sản phẩm</a>
      <span>/</span>
      <span>{{ product?.name }}</span>
    </div>

    <div class="loading-spinner" *ngIf="loading">
      <i class="fas fa-spinner fa-spin"></i> Đang tải...
    </div>

    <div class="product-detail" *ngIf="!loading && product">
      <!-- Image Gallery -->
      <div class="product-gallery">
        <div class="main-image">
          <img [src]="selectedImage" [alt]="product.name"
               onerror="this.src='assets/images/no-image.svg'">
          <span class="badge-sale" *ngIf="getDiscountPercent() > 0">
            -{{ getDiscountPercent() }}%
          </span>
        </div>
        <div class="thumbnails" *ngIf="allImages.length > 1">
          <div class="thumb" *ngFor="let img of allImages"
               [class.active]="img === selectedImage"
               (click)="selectImage(img)">
            <img [src]="img" alt="thumbnail">
          </div>
        </div>
      </div>

      <!-- Product Info -->
      <div class="product-info">
        <h1>{{ product.name }}</h1>
        <div class="meta">
          <div class="rating">
            <i *ngFor="let s of getStars(product.averageRating)"
               class="fas fa-star" [class.filled]="s === 1"></i>
            <span>({{ product.totalReviews || 0 }} đánh giá)</span>
          </div>
          <span class="sold">Đã bán {{ product.soldCount || 0 }}</span>
        </div>

        <div class="price-section">
          <span class="current-price">{{ formatPrice(product.price) }}</span>
          <span class="original-price" *ngIf="product.originalPrice && product.originalPrice > product.price">
            {{ formatPrice(product.originalPrice) }}
          </span>
          <span class="discount-tag" *ngIf="getDiscountPercent() > 0">
            Giảm {{ getDiscountPercent() }}%
          </span>
        </div>

        <div class="info-row" *ngIf="product.category">
          <span class="label">Danh mục:</span>
          <span>{{ product.category.name }}</span>
        </div>
        <div class="info-row" *ngIf="product.brand">
          <span class="label">Thương hiệu:</span>
          <span>{{ product.brand.name }}</span>
        </div>
        <div class="info-row">
          <span class="label">Kho:</span>
          <span [class.out-of-stock]="product.stockQuantity <= 0">
            {{ product.stockQuantity > 0 ? product.stockQuantity + ' sản phẩm' : 'Hết hàng' }}
          </span>
        </div>

        <div class="quantity-section">
          <span class="label">Số lượng:</span>
          <div class="qty-control">
            <button (click)="decreaseQty()" [disabled]="quantity <= 1">-</button>
            <input type="number" [(ngModel)]="quantity" [max]="product.stockQuantity" min="1">
            <button (click)="increaseQty()" [disabled]="quantity >= product.stockQuantity">+</button>
          </div>
        </div>

        <button class="btn-add-cart" (click)="addToCart()" [disabled]="product.stockQuantity <= 0">
          <i class="fas fa-cart-plus"></i>
          {{ product.stockQuantity > 0 ? 'Thêm vào giỏ hàng' : 'Hết hàng' }}
        </button>
      </div>
    </div>

    <!-- Description -->
    <div class="product-description" *ngIf="product">
      <h2>Mô tả sản phẩm</h2>
      <div class="desc-content" [innerHTML]="product.description"></div>
    </div>

    <!-- Reviews -->
    <div class="reviews-section" *ngIf="product">
      <div class="reviews-header">
        <h2>Đánh giá sản phẩm ({{ product.totalReviews || 0 }})</h2>
        <button class="btn-write-review" *ngIf="authService.isLoggedIn && !showReviewForm"
                (click)="toggleReviewForm()">
          <i class="fas fa-pen"></i> Viết đánh giá
        </button>
      </div>

      <!-- Write Review Form -->
      <div class="write-review-form" *ngIf="showReviewForm">
        <h3><i class="fas fa-star"></i> Đánh giá của bạn</h3>
        <div class="form-stars" (mouseleave)="resetHover()">
          <span *ngFor="let star of [1,2,3,4,5]"
                [class]="getNewStarClass(star)"
                (click)="setNewRating(star)"
                (mouseenter)="setHoverRating(star)">
            ★
          </span>
        </div>
        <div class="form-rating-label" [ngClass]="'rating-' + (hoverRating || newReviewRating)">
          {{ getNewRatingLabel() }}
        </div>
        <textarea [(ngModel)]="newReviewComment"
                  placeholder="Chia sẻ trải nghiệm của bạn về sản phẩm này..."
                  rows="4"
                  class="form-textarea"></textarea>
        <div class="form-actions">
          <button class="btn-cancel-review" (click)="toggleReviewForm()">Hủy</button>
          <button class="btn-submit-review" (click)="submitReview()" [disabled]="reviewSubmitting">
            <i class="fas fa-paper-plane" *ngIf="!reviewSubmitting"></i>
            <i class="fas fa-spinner fa-spin" *ngIf="reviewSubmitting"></i>
            {{ reviewSubmitting ? 'Đang gửi...' : 'Gửi đánh giá' }}
          </button>
        </div>
      </div>

      <div class="review-list">
        <div class="review-item" *ngFor="let review of reviews">
          <div class="review-header">
            <img [src]="getImg(review.customer?.avatarUrl) || 'assets/images/default-avatar.svg'"
                 class="reviewer-avatar" alt="">
            <div>
              <strong>{{ review.customer?.fullName || 'Khách hàng' }}</strong>
              <div class="review-rating">
                <i *ngFor="let s of getStars(review.rating)"
                   class="fas fa-star" [class.filled]="s === 1"></i>
              </div>
            </div>
            <span class="review-date">{{ getTimeAgo(review.createdAt) }}</span>
          </div>
          <p class="review-comment">{{ review.comment }}</p>
          <div class="review-images" *ngIf="review.images?.length">
            <img *ngFor="let img of review.images" [src]="getImg(img)" alt="review image">
          </div>
        </div>
        <div class="empty-reviews" *ngIf="reviews.length === 0">
          <i class="fas fa-comment-slash"></i>
          <p>Chưa có đánh giá nào</p>
        </div>
      </div>
    </div>
  </div>
</div>
