// ume-frontend/src/app/pages/admin/admin-brands/admin-brands.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService } from '../../../services/api.service';

@Component({
  selector: 'app-admin-brands',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div class="page-header">
      <div><h4><i class="fas fa-tags text-gold"></i> Quản lý thương hiệu</h4>
        <ol class="breadcrumb"><li><a routerLink="/admin">Dashboard</a></li><li class="active">Thương hiệu</li></ol>
      </div>
      <button class="btn btn-gold" (click)="openForm()"><i class="fas fa-plus mr-1"></i>Thêm thương hiệu</button>
    </div>
    <div class="alert alert-success" *ngIf="msg"><i class="fas fa-check-circle mr-2"></i>{{msg}}<button class="alert-x" (click)="msg=''">&times;</button></div>

    <div class="card">
      <div class="card-header">
        <div class="search-box"><input class="form-control" [(ngModel)]="search" placeholder="Tìm kiếm..." (keyup.enter)="load()"><button class="btn btn-gold btn-sm" (click)="load()"><i class="fas fa-search"></i></button></div>
      </div>
      <div class="card-body p-0">
        <table class="adm-table">
          <thead><tr><th>#</th><th>Logo</th><th>Tên thương hiệu</th><th>Mô tả</th><th>Sản phẩm</th><th>Thứ tự</th><th>Trạng thái</th><th>Thao tác</th></tr></thead>
          <tbody>
            <tr *ngFor="let b of items; let i=index">
              <td>{{i+1}}</td>
              <td><img [src]="getImg(b.logoUrl||b.logo||b.imageUrl||b.image)" class="img-t-sm"></td>
              <td><strong>{{b.name}}</strong></td>
              <td class="muted">{{b.description?(b.description.length>50?b.description.substring(0,50)+'...':b.description):'-'}}</td>
              <td><span class="cat-b">{{b.productCount||0}}</span></td>
              <td>{{b.displayOrder||0}}</td>
              <td><label class="sw"><input type="checkbox" [checked]="b.isActive!==false" (change)="togAct(b)"><span class="sl"></span></label></td>
              <td><div class="act-g"><button class="ab aw" (click)="openForm(b)"><i class="fas fa-edit"></i></button><button class="ab ar" (click)="confirmDel(b)"><i class="fas fa-trash"></i></button></div></td>
            </tr>
            <tr *ngIf="!items.length&&!ld"><td colspan="8" class="empty">Không có thương hiệu nào</td></tr>
            <tr *ngIf="ld"><td colspan="8" class="empty"><i class="fas fa-spinner fa-spin fa-2x text-gold"></i></td></tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="mo" *ngIf="showForm" (click)="showForm=false"><div class="md" (click)="$event.stopPropagation()">
      <div class="mh bg-g"><h5><i class="fas fa-tags mr-2"></i>{{editing?'Sửa':'Thêm'}} thương hiệu</h5><button class="mx" (click)="showForm=false">&times;</button></div>
      <div class="mb-modal">
        <div class="fg"><label>Tên thương hiệu <span class="req">*</span></label><input class="form-control" [(ngModel)]="fd.name"></div>
        <div class="fg"><label>Mô tả</label><textarea class="form-control" [(ngModel)]="fd.description" rows="3"></textarea></div>
        <div class="fg"><label>Thứ tự</label><input type="number" class="form-control" [(ngModel)]="fd.displayOrder" min="0"></div>
        <div class="fg"><label>Logo</label><div class="img-up-sm" (click)="fi.click()"><img *ngIf="imgPv" [src]="imgPv" class="pv-img"><div *ngIf="!imgPv" class="up-ph"><i class="fas fa-image"></i><span>Chọn ảnh</span></div></div><input type="file" #fi (change)="onFile($event)" accept="image/*" hidden></div>
        <div class="fg"><label class="ck-label"><input type="checkbox" [(ngModel)]="fd.isActive"> Hoạt động</label></div>
      </div>
      <div class="mf"><button class="btn btn-sec" (click)="showForm=false">Hủy</button><button class="btn btn-gold" (click)="save()" [disabled]="saving"><i class="fas fa-save mr-1"></i>{{saving?'Đang lưu...':'Lưu'}}</button></div>
    </div></div>

    <div class="mo" *ngIf="showDel" (click)="showDel=false"><div class="md" (click)="$event.stopPropagation()">
      <div class="mh bg-r"><h5><i class="fas fa-trash mr-2"></i>Xác nhận xóa</h5><button class="mx" (click)="showDel=false">&times;</button></div>
      <div class="mb-modal"><p>Bạn có chắc muốn xóa <strong>{{delItem?.name}}</strong>?</p></div>
      <div class="mf"><button class="btn btn-sec" (click)="showDel=false">Hủy</button><button class="btn btn-danger" (click)="doDelete()"><i class="fas fa-trash mr-1"></i>Xóa</button></div>
    </div></div>
  `,
  styles: [`
    :host{display:block}
    .page-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:16px;flex-wrap:wrap;gap:8px}
    .page-header h4{font-weight:600;color:#1a1a1a;font-size:1.3rem;margin:0}.page-header h4 i{margin-right:8px}
    .text-gold{color:#D4AF37!important}
    .breadcrumb{list-style:none;display:flex;gap:8px;padding:0;margin:4px 0 0;font-size:.85rem}.breadcrumb a{color:#D4AF37;text-decoration:none}.breadcrumb .active{color:#6c757d}.breadcrumb li+li::before{content:"/";margin-right:8px;color:#adb5bd}
    .btn{padding:8px 16px;border:none;border-radius:6px;cursor:pointer;font-size:.85rem;display:inline-flex;align-items:center;gap:4px;transition:all .2s}
    .btn-gold{background:#D4AF37;color:#fff}.btn-gold:hover{background:#B8960C}.btn-sec{background:#6c757d;color:#fff}.btn-danger{background:#dc3545;color:#fff}.btn-sm{padding:6px 12px}.btn:disabled{opacity:.6}
    .alert{padding:12px 16px;border-radius:8px;margin-bottom:16px;display:flex;align-items:center;position:relative}.alert-success{background:#d4edda;color:#155724;border:1px solid #c3e6cb}.alert-x{position:absolute;right:12px;background:none;border:none;font-size:1.2rem;cursor:pointer;color:inherit}
    .card{border:none;border-radius:12px;box-shadow:0 2px 12px rgba(0,0,0,.08);margin-bottom:16px;background:#fff}
    .card-header{background:#fff;border-bottom:1px solid #f0f0f0;padding:12px 16px;border-radius:12px 12px 0 0!important;display:flex;justify-content:space-between;align-items:center}.card-body{padding:16px}
    .search-box{display:flex;gap:8px}.search-box .form-control{width:250px}
    label{display:block;font-size:.85rem;font-weight:500;margin-bottom:4px;color:#333}
    .form-control{width:100%;padding:8px 12px;border:1px solid #dee2e6;border-radius:6px;font-size:.9rem;box-sizing:border-box}.form-control:focus{border-color:#D4AF37;outline:none;box-shadow:0 0 0 3px rgba(212,175,55,.15)}
    select.form-control{appearance:auto}textarea.form-control{resize:vertical}.fg{margin-bottom:12px}
    .p-0{padding:0!important}.mr-1{margin-right:4px}.mr-2{margin-right:8px}
    .adm-table{width:100%;border-collapse:collapse}.adm-table th,.adm-table td{padding:10px 16px;border-bottom:1px solid #f0f0f0;font-size:.85rem;vertical-align:middle}
    .adm-table thead th{background:#343a40;color:#fff;font-weight:600;white-space:nowrap}.adm-table tbody tr:nth-child(odd){background:rgba(0,0,0,.02)}.adm-table tbody tr:hover{background:rgba(212,175,55,.05)}
    .img-t-sm{width:50px;height:50px;object-fit:contain;border-radius:6px;border:1px solid #dee2e6}
    .cat-b{background:#17a2b8;color:#fff;padding:2px 8px;border-radius:4px;font-size:.75rem}.muted{color:#6c757d}
    .sw{position:relative;display:inline-block;width:40px;height:22px;margin:0}.sw input{opacity:0;width:0;height:0}
    .sl{position:absolute;cursor:pointer;top:0;left:0;right:0;bottom:0;background:#ccc;transition:.3s;border-radius:22px}
    .sl:before{position:absolute;content:"";height:16px;width:16px;left:3px;bottom:3px;background:#fff;transition:.3s;border-radius:50%}
    input:checked+.sl{background:#D4AF37}input:checked+.sl:before{transform:translateX(18px)}
    .act-g{display:flex;gap:4px}.ab{padding:6px 10px;border:none;border-radius:4px;cursor:pointer;color:#fff;font-size:.8rem}.aw{background:#ffc107;color:#1a1a1a}.ar{background:#dc3545}
    .empty{text-align:center;padding:30px 0;color:#adb5bd}
    .mo{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.5);z-index:1060;display:flex;align-items:center;justify-content:center;padding:20px}
    .md{background:#fff;border-radius:12px;max-width:500px;width:100%;max-height:90vh;overflow-y:auto;box-shadow:0 10px 40px rgba(0,0,0,.2)}
    .mh{padding:16px 20px;border-radius:12px 12px 0 0;display:flex;justify-content:space-between;align-items:center;color:#fff}.mh h5{margin:0;font-size:1.05rem}.mx{background:none;border:none;color:#fff;font-size:1.5rem;cursor:pointer}
    .mb-modal{padding:20px}.mf{padding:12px 20px;border-top:1px solid #f0f0f0;display:flex;justify-content:flex-end;gap:8px}
    .bg-g{background:#D4AF37}.bg-r{background:#dc3545}
    .img-up-sm{width:100%;height:120px;border:2px dashed #dee2e6;border-radius:8px;cursor:pointer;display:flex;align-items:center;justify-content:center;overflow:hidden}.img-up-sm:hover{border-color:#D4AF37}
    .pv-img{width:100%;height:100%;object-fit:cover}.up-ph{display:flex;flex-direction:column;align-items:center;color:#adb5bd;gap:8px}.up-ph i{font-size:1.5rem}
    .ck-label{display:flex;align-items:center;gap:8px;cursor:pointer;font-size:.9rem}.ck-label input{width:16px;height:16px;accent-color:#D4AF37}
    .req{color:#dc3545}
    .row{display:flex;flex-wrap:wrap;margin:0 -8px}
  `]
})
export class AdminBrandsComponent implements OnInit {
  items: any[] = [];
  ld = false; saving = false; msg = ''; search = '';
  showForm = false; editing: any = null; fd: any = {}; selFile: File | null = null; imgPv = '';
  showDel = false; delItem: any = null;

  constructor(private api: ApiService) {}
  ngOnInit() { this.load(); }

  getImg(path: string): string { return this.api.getImageUrl(path) || 'https://via.placeholder.com/50'; }

  load() {
    this.ld = true;
    this.api.getBrands({ limit: 100, search: this.search || undefined }).subscribe({
      next: (r: any) => { this.ld = false; this.items = r.data?.brands || r.data || []; },
      error: () => this.ld = false
    });
  }

  openForm(b?: any) {
    this.editing = b || null;
    this.fd = b ? { name: b.name, description: b.description || '', displayOrder: b.displayOrder || 0, isActive: b.isActive !== false }
      : { name: '', description: '', displayOrder: 0, isActive: true };
    this.selFile = null; this.imgPv = this.getImg(b?.logoUrl || b?.logo || b?.imageUrl || b?.image || '');
    this.showForm = true;
  }

  onFile(e: any) { const f = e.target.files[0]; if (f) { this.selFile = f; const r = new FileReader(); r.onload = (ev: any) => this.imgPv = ev.target.result; r.readAsDataURL(f); } }

  save() {
    if (!this.fd.name) return;
    this.saving = true;
    const d = new FormData();
    Object.keys(this.fd).forEach(k => { if (this.fd[k] !== null && this.fd[k] !== undefined && this.fd[k] !== '') d.append(k, this.fd[k]); });
    if (this.selFile) d.append('logo', this.selFile);
    const obs = this.editing ? this.api.updateBrand(this.editing._id, d) : this.api.createBrand(d);
    obs.subscribe({ next: () => { this.saving = false; this.msg = this.editing ? 'Đã cập nhật!' : 'Đã thêm!'; this.showForm = false; this.load(); setTimeout(() => this.msg = '', 3000); }, error: () => this.saving = false });
  }

  togAct(b: any) { const d = new FormData(); d.append('isActive', String(!b.isActive)); this.api.updateBrand(b._id, d).subscribe({ next: () => b.isActive = !b.isActive, error: () => {} }); }
  confirmDel(b: any) { this.delItem = b; this.showDel = true; }
  doDelete() { if (!this.delItem) return; this.api.deleteBrand(this.delItem._id).subscribe({ next: () => { this.msg = 'Đã xóa!'; this.load(); this.showDel = false; setTimeout(() => this.msg = '', 3000); }, error: () => this.showDel = false }); }
}

// ume-react/src/pages/admin/brands/AdminBrands.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { brandApi, getImageUrl } from '../../../services/api';
import '../shared/admin.scss';

export default function AdminBrands() {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState('');

  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState<any>(null);
  const [fd, setFd] = useState<any>({});
  const [imgFile, setImgFile] = useState<File | null>(null);
  const [imgPreview, setImgPreview] = useState('');
  const [saving, setSaving] = useState(false);

  const [showDelete, setShowDelete] = useState(false);
  const [deleteItem, setDeleteItem] = useState<any>(null);

  useEffect(() => { load(); }, []);

  async function load() {
    setLoading(true);
    try {
      const r = await brandApi.getAll({ limit: '200', search: search || undefined });
      const d = r.data?.data || r.data;
      setItems(d?.brands || d || []);
    } catch {}
    setLoading(false);
  }

  function openForm(item?: any) {
    setEditing(item || null);
    setFd(item ? {
      name: item.name || '', description: item.description || '',
      displayOrder: item.displayOrder || 0, isActive: item.isActive !== false,
    } : { name: '', description: '', displayOrder: 0, isActive: true });
    setImgFile(null);
    setImgPreview(item?.logoUrl ? getImageUrl(item.logoUrl) : '');
    setShowForm(true);
  }

  async function save() {
    if (!fd.name) { toast.error('Nhập tên thương hiệu'); return; }
    setSaving(true);
    try {
      const formData = new FormData();
      Object.keys(fd).forEach(k => { if (fd[k] !== undefined && fd[k] !== '') formData.append(k, String(fd[k])); });
      if (imgFile) formData.append('logo', imgFile);
      if (editing) await brandApi.update(editing._id, formData);
      else await brandApi.create(formData);
      toast.success(editing ? 'Đã cập nhật!' : 'Đã tạo thương hiệu!');
      setShowForm(false); load();
    } catch { toast.error('Có lỗi xảy ra'); }
    setSaving(false);
  }

  async function toggleActive(item: any) {
    try {
      const formData = new FormData();
      formData.append('isActive', String(!item.isActive));
      await brandApi.update(item._id, formData);
      load();
    } catch {}
  }

  async function doDelete() {
    if (!deleteItem) return;
    try { await brandApi.delete(deleteItem._id); toast.success('Đã xóa!'); setShowDelete(false); load(); }
    catch { toast.error('Có lỗi xảy ra'); }
  }

  return (
    <div>
      <div className="page-header">
        <div><h4>🏷️ Quản lý thương hiệu</h4>
          <ol className="breadcrumb"><li><Link to="/admin">Dashboard</Link></li><li className="active">Thương hiệu</li></ol>
        </div>
        <button className="btn btn-gold" onClick={() => openForm()}>➕ Thêm thương hiệu</button>
      </div>

      <div className="card">
        <div className="card-header">
          <div className="search-box">
            <input className="form-control" value={search} onChange={e => setSearch(e.target.value)} placeholder="Tìm thương hiệu..." onKeyDown={e => e.key === 'Enter' && load()} />
            <button className="btn btn-gold btn-sm" onClick={load}>🔍</button>
          </div>
        </div>
        <div className="card-body p-0">
          <table className="adm-table">
            <thead><tr><th>#</th><th>Logo</th><th>Tên</th><th>Mô tả</th><th>SP</th><th>Thứ tự</th><th>Active</th><th>Thao tác</th></tr></thead>
            <tbody>
              {items.map((b, i) => (
                <tr key={b._id}>
                  <td>{i + 1}</td>
                  <td><img src={getImageUrl(b.logoUrl)} alt="" className="img-preview" /></td>
                  <td><strong>{b.name}</strong></td>
                  <td className="sub-txt">{(b.description || '').substring(0, 60)}</td>
                  <td>{b.productCount || 0}</td>
                  <td>{b.displayOrder || 0}</td>
                  <td><label className="toggle-switch"><input type="checkbox" checked={b.isActive !== false} onChange={() => toggleActive(b)} /><span className="slider" /></label></td>
                  <td><div className="act-g">
                    <button className="ab ab-edit" onClick={() => openForm(b)}>✏️</button>
                    <button className="ab ab-del" onClick={() => { setDeleteItem(b); setShowDelete(true); }}>🗑️</button>
                  </div></td>
                </tr>
              ))}
              {!items.length && !loading && <tr><td colSpan={8} className="empty">Không có thương hiệu nào</td></tr>}
              {loading && <tr><td colSpan={8} className="empty">Đang tải...</td></tr>}
            </tbody>
          </table>
        </div>
      </div>

      {showForm && (
        <div className="mo" onClick={() => setShowForm(false)}>
          <div className="md" onClick={e => e.stopPropagation()}>
            <div className="mh bg-g"><h5>{editing ? '✏️ Sửa' : '➕ Thêm'} thương hiệu</h5><button className="mx" onClick={() => setShowForm(false)}>&times;</button></div>
            <div className="mb-modal">
              <div className="fg"><label>Tên <span className="req">*</span></label><input className="form-control" value={fd.name} onChange={e => setFd({ ...fd, name: e.target.value })} /></div>
              <div className="fg"><label>Mô tả</label><textarea className="form-control" rows={3} value={fd.description} onChange={e => setFd({ ...fd, description: e.target.value })} /></div>
              <div className="fg"><label>Thứ tự</label><input type="number" className="form-control" value={fd.displayOrder} onChange={e => setFd({ ...fd, displayOrder: Number(e.target.value) })} /></div>
              <div className="fg"><label><input type="checkbox" checked={fd.isActive} onChange={e => setFd({ ...fd, isActive: e.target.checked })} /> Hiển thị</label></div>
              <div className="fg"><label>Logo</label><input type="file" accept="image/*" onChange={e => { const f = e.target.files?.[0]; if (f) { setImgFile(f); setImgPreview(URL.createObjectURL(f)); } }} />
                {imgPreview && <img src={imgPreview} alt="" className="img-preview-lg" style={{ marginTop: 8 }} />}
              </div>
            </div>
            <div className="mf"><button className="btn btn-sec" onClick={() => setShowForm(false)}>Hủy</button><button className="btn btn-gold" onClick={save} disabled={saving}>{saving ? 'Đang lưu...' : '💾 Lưu'}</button></div>
          </div>
        </div>
      )}

      {showDelete && (
        <div className="mo" onClick={() => setShowDelete(false)}>
          <div className="md" onClick={e => e.stopPropagation()}>
            <div className="mh bg-r"><h5>🗑️ Xóa thương hiệu</h5><button className="mx" onClick={() => setShowDelete(false)}>&times;</button></div>
            <div className="mb-modal"><p>Bạn có chắc muốn xóa <strong>{deleteItem?.name}</strong>?</p><p className="text-danger">Hành động này không thể hoàn tác!</p></div>
            <div className="mf"><button className="btn btn-sec" onClick={() => setShowDelete(false)}>Hủy</button><button className="btn btn-danger" onClick={doDelete}>🗑️ Xác nhận xóa</button></div>
          </div>
        </div>
      )}
    </div>
  );
}
