// ume-react/src/pages/admin/promotions/AdminPromotions.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { promotionApi } from '../../../services/api';
import '../shared/admin.scss';

function fmtN(n: number) { return new Intl.NumberFormat('vi-VN').format(n); }
function fmtD(d: string) { return d ? new Date(d).toLocaleDateString('vi-VN') : '-'; }

const TYPES = [
  { value: 'Percentage', label: 'Giảm %' },
  { value: 'Fixed', label: 'Giảm cố định' },
  { value: 'FreeShipping', label: 'Miễn phí ship' },
  { value: 'BuyXGetY', label: 'Mua X tặng Y' },
];

export default function AdminPromotions() {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState('');
  const [stats, setStats] = useState({ total: 0, active: 0, expired: 0, totalUsed: 0 });

  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState<any>(null);
  const [fd, setFd] = useState<any>({});
  const [saving, setSaving] = useState(false);

  const [showDelete, setShowDelete] = useState(false);
  const [deleteItem, setDeleteItem] = useState<any>(null);

  useEffect(() => { load(); }, []);

  async function load() {
    setLoading(true);
    try {
      const p: any = { limit: '200' };
      if (search) p.search = search;
      const r = await promotionApi.getAll(p);
      const d = r.data?.data || r.data;
      const list = d?.promotions || d || [];
      setItems(list);
      const now = new Date();
      setStats({
        total: list.length,
        active: list.filter((p: any) => p.isActive && new Date(p.endDate) > now).length,
        expired: list.filter((p: any) => new Date(p.endDate) <= now).length,
        totalUsed: list.reduce((s: number, p: any) => s + (p.usedCount || 0), 0),
      });
    } catch {}
    setLoading(false);
  }

  function isExpired(item: any) { return new Date(item.endDate) <= new Date(); }
  function isActive(item: any) { return item.isActive && !isExpired(item); }

  function openForm(item?: any) {
    setEditing(item || null);
    setFd(item ? {
      code: item.code || '', name: item.name || '', type: item.type || 'Percentage',
      value: item.value || 0, minOrder: item.minOrder || 0, maxDiscount: item.maxDiscount || 0,
      usageLimit: item.usageLimit || 0, startDate: item.startDate?.substring(0, 10) || '',
      endDate: item.endDate?.substring(0, 10) || '', description: item.description || '', isActive: item.isActive !== false,
    } : { code: '', name: '', type: 'Percentage', value: 0, minOrder: 0, maxDiscount: 0, usageLimit: 0, startDate: '', endDate: '', description: '', isActive: true });
    setShowForm(true);
  }

  async function save() {
    if (!fd.code || !fd.name) { toast.error('Nhập đủ thông tin bắt buộc'); return; }
    setSaving(true);
    try {
      if (editing) await promotionApi.update(editing._id, fd);
      else await promotionApi.create(fd);
      toast.success(editing ? 'Đã cập nhật!' : 'Đã tạo khuyến mãi!');
      setShowForm(false); load();
    } catch (e: any) { toast.error(e.response?.data?.message || 'Có lỗi xảy ra'); }
    setSaving(false);
  }

  async function toggleActive(item: any) {
    try {
      await promotionApi.update(item._id, { isActive: !item.isActive });
      toast.success(item.isActive ? 'Đã tắt' : 'Đã bật');
      load();
    } catch { toast.error('Có lỗi xảy ra'); }
  }

  async function doDelete() {
    if (!deleteItem) return;
    try { await promotionApi.delete(deleteItem._id); toast.success('Đã xóa!'); setShowDelete(false); load(); }
    catch { toast.error('Có lỗi xảy ra'); }
  }

  function discountLabel(p: any) {
    if (p.type === 'Percentage') return `${p.value}%`;
    if (p.type === 'Fixed') return `${fmtN(p.value)}đ`;
    if (p.type === 'FreeShipping') return 'Miễn ship';
    return `Mua ${p.value}`;
  }

  return (
    <div>
      <div className="page-header">
        <div><h4>🎁 Quản lý khuyến mãi</h4>
          <ol className="breadcrumb"><li><Link to="/admin">Dashboard</Link></li><li className="active">Khuyến mãi</li></ol>
        </div>
        <button className="btn btn-gold" onClick={() => openForm()}>➕ Thêm khuyến mãi</button>
      </div>

      <div className="stats-row">
        <div className="stat-box"><div className="sb-icon bg-info">🎁</div><div><div className="sb-num">{stats.total}</div><div className="sb-label">Tổng cộng</div></div></div>
        <div className="stat-box"><div className="sb-icon bg-success">✅</div><div><div className="sb-num">{stats.active}</div><div className="sb-label">Đang hoạt động</div></div></div>
        <div className="stat-box"><div className="sb-icon bg-danger">⏰</div><div><div className="sb-num">{stats.expired}</div><div className="sb-label">Hết hạn</div></div></div>
        <div className="stat-box"><div className="sb-icon bg-gold">🎫</div><div><div className="sb-num">{stats.totalUsed}</div><div className="sb-label">Lượt dùng</div></div></div>
      </div>

      <div className="card">
        <div className="card-header">
          <div className="filter-row">
            <div className="search-box">
              <input className="form-control" value={search} onChange={e => setSearch(e.target.value)} placeholder="Tìm mã khuyến mãi..." onKeyDown={e => e.key === 'Enter' && load()} />
              <button className="btn btn-gold btn-sm" onClick={load}>🔍</button>
            </div>
          </div>
        </div>
        <div className="card-body p-0">
          <table className="adm-table">
            <thead><tr><th>#</th><th>Mã</th><th>Tên</th><th>Loại</th><th>Giá trị</th><th>Đơn tối thiểu</th><th>Đã dùng</th><th>Thời hạn</th><th>Trạng thái</th><th>Thao tác</th></tr></thead>
            <tbody>
              {items.map((p, i) => (
                <tr key={p._id}>
                  <td>{i + 1}</td>
                  <td><strong style={{ fontFamily: 'monospace', letterSpacing: 1 }}>{p.code}</strong></td>
                  <td>{p.name}</td>
                  <td>{TYPES.find(t => t.value === p.type)?.label || p.type}</td>
                  <td className="fw-bold">{discountLabel(p)}</td>
                  <td>{p.minOrder ? `${fmtN(p.minOrder)}đ` : '-'}</td>
                  <td>{p.usedCount || 0}/{p.usageLimit || '∞'}</td>
                  <td><div className="sub-txt">{fmtD(p.startDate)} - {fmtD(p.endDate)}</div></td>
                  <td>
                    {isExpired(p) ? <span className="os-badge os-cancelled">Hết hạn</span> :
                     isActive(p) ? <span className="os-badge os-completed">Đang chạy</span> :
                     <span className="os-badge os-pending">Tạm tắt</span>}
                    <label className="toggle-switch" style={{ marginLeft: 8 }}><input type="checkbox" checked={p.isActive} onChange={() => toggleActive(p)} /><span className="toggle-slider"></span></label>
                  </td>
                  <td><div className="act-g">
                    <button className="ab ab-edit" onClick={() => openForm(p)}>✏️</button>
                    <button className="ab ab-del" onClick={() => { setDeleteItem(p); setShowDelete(true); }}>🗑️</button>
                  </div></td>
                </tr>
              ))}
              {!items.length && !loading && <tr><td colSpan={10} className="empty">Không có khuyến mãi nào</td></tr>}
              {loading && <tr><td colSpan={10} className="empty">Đang tải...</td></tr>}
            </tbody>
          </table>
        </div>
      </div>

      {showForm && (
        <div className="mo" onClick={() => setShowForm(false)}>
          <div className="md md-lg" onClick={e => e.stopPropagation()}>
            <div className="mh bg-g"><h5>{editing ? '✏️ Sửa' : '➕ Thêm'} khuyến mãi</h5><button className="mx" onClick={() => setShowForm(false)}>&times;</button></div>
            <div className="mb-modal">
              <div className="row">
                <div className="adm-col-6"><div className="fg"><label>Mã khuyến mãi <span className="req">*</span></label><input className="form-control" value={fd.code} onChange={e => setFd({ ...fd, code: e.target.value.toUpperCase() })} style={{ fontFamily: 'monospace', letterSpacing: 2 }} /></div></div>
                <div className="adm-col-6"><div className="fg"><label>Tên <span className="req">*</span></label><input className="form-control" value={fd.name} onChange={e => setFd({ ...fd, name: e.target.value })} /></div></div>
              </div>
              <div className="row">
                <div className="adm-col-6"><div className="fg"><label>Loại</label>
                  <select className="form-control" value={fd.type} onChange={e => setFd({ ...fd, type: e.target.value })}>
                    {TYPES.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
                  </select>
                </div></div>
                <div className="adm-col-6"><div className="fg"><label>Giá trị {fd.type === 'Percentage' ? '(%)' : fd.type === 'Fixed' ? '(VNĐ)' : ''}</label><input type="number" className="form-control" value={fd.value} onChange={e => setFd({ ...fd, value: +e.target.value })} /></div></div>
              </div>
              <div className="row">
                <div className="adm-col-6"><div className="fg"><label>Đơn tối thiểu (VNĐ)</label><input type="number" className="form-control" value={fd.minOrder} onChange={e => setFd({ ...fd, minOrder: +e.target.value })} /></div></div>
                <div className="adm-col-6"><div className="fg"><label>Giảm tối đa (VNĐ)</label><input type="number" className="form-control" value={fd.maxDiscount} onChange={e => setFd({ ...fd, maxDiscount: +e.target.value })} /></div></div>
              </div>
              <div className="row">
                <div className="adm-col-4"><div className="fg"><label>Giới hạn sử dụng</label><input type="number" className="form-control" value={fd.usageLimit} onChange={e => setFd({ ...fd, usageLimit: +e.target.value })} placeholder="0 = không giới hạn" /></div></div>
                <div className="adm-col-4"><div className="fg"><label>Ngày bắt đầu</label><input type="date" className="form-control" value={fd.startDate} onChange={e => setFd({ ...fd, startDate: e.target.value })} /></div></div>
                <div className="adm-col-4"><div className="fg"><label>Ngày kết thúc</label><input type="date" className="form-control" value={fd.endDate} onChange={e => setFd({ ...fd, endDate: e.target.value })} /></div></div>
              </div>
              <div className="fg"><label>Mô tả</label><textarea className="form-control" rows={2} value={fd.description} onChange={e => setFd({ ...fd, description: e.target.value })} /></div>
              <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
                <input type="checkbox" checked={fd.isActive} onChange={e => setFd({ ...fd, isActive: e.target.checked })} /> Kích hoạt
              </label>
            </div>
            <div className="mf"><button className="btn btn-sec" onClick={() => setShowForm(false)}>Hủy</button><button className="btn btn-gold" onClick={save} disabled={saving}>{saving ? 'Đang lưu...' : '💾 Lưu'}</button></div>
          </div>
        </div>
      )}

      {showDelete && (
        <div className="mo" onClick={() => setShowDelete(false)}>
          <div className="md" onClick={e => e.stopPropagation()}>
            <div className="mh bg-r"><h5>🗑️ Xóa khuyến mãi</h5><button className="mx" onClick={() => setShowDelete(false)}>&times;</button></div>
            <div className="mb-modal"><p>Bạn có chắc muốn xóa <strong>{deleteItem?.code}</strong>?</p></div>
            <div className="mf"><button className="btn btn-sec" onClick={() => setShowDelete(false)}>Hủy</button><button className="btn btn-danger" onClick={doDelete}>🗑️ Xác nhận xóa</button></div>
          </div>
        </div>
      )}
    </div>
  );
}

// ume-frontend/src/app/pages/admin/admin-promotions/admin-promotions.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api.service';

@Component({
  selector: 'app-admin-promotions',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="page-header">
      <h2><i class="fas fa-percentage"></i> Quản lý khuyến mãi</h2>
      <button class="btn btn-gold" (click)="showForm = true; resetForm()"><i class="fas fa-plus"></i> Thêm khuyến mãi</button>
    </div>

    <!-- Table -->
    <div class="card">
      <div class="card-body p-0">
        <div class="table-responsive">
          <table class="adm-table">
            <thead>
              <tr>
                <th>Mã</th>
                <th>Tên</th>
                <th>Loại</th>
                <th>Giá trị</th>
                <th>Đã dùng</th>
                <th>Thời gian</th>
                <th>Trạng thái</th>
                <th>Thao tác</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let promo of promotions">
                <td><strong class="text-gold">{{ promo.code }}</strong></td>
                <td>{{ promo.name }}</td>
                <td>{{ getTypeName(promo.type) }}</td>
                <td>
                  <span *ngIf="promo.type === 'Percentage'">{{ promo.value }}%</span>
                  <span *ngIf="promo.type === 'FixedAmount'">{{ promo.value | number:'1.0-0' }}đ</span>
                  <span *ngIf="promo.type === 'FreeShipping'">Miễn ship</span>
                  <span *ngIf="promo.type === 'BuyXGetY'">Mua X tặng Y</span>
                  <br>
                  <small class="text-muted" *ngIf="promo.minOrderAmount">Tối thiểu: {{ promo.minOrderAmount | number:'1.0-0' }}đ</small>
                </td>
                <td>{{ promo.usedCount }}<span *ngIf="promo.usageLimit > 0">/{{ promo.usageLimit }}</span></td>
                <td>
                  {{ promo.startDate | date:'dd/MM/yyyy' }}<br>
                  <small class="text-muted">→ {{ promo.endDate | date:'dd/MM/yyyy' }}</small>
                </td>
                <td>
                  <span [class]="'st-badge ' + (promo.isActive ? 'st-active' : 'st-inactive')">
                    {{ promo.isActive ? 'Hoạt động' : 'Tắt' }}
                  </span>
                  <span *ngIf="isExpired(promo)" class="st-badge st-expired">Hết hạn</span>
                </td>
                <td>
                  <button class="btn-icon btn-edit" (click)="editPromo(promo)"><i class="fas fa-edit"></i></button>
                  <button class="btn-icon btn-danger" (click)="deletePromo(promo)"><i class="fas fa-trash"></i></button>
                </td>
              </tr>
              <tr *ngIf="promotions.length === 0">
                <td colspan="8" class="text-center py-4 text-muted">Chưa có khuyến mãi nào</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Pagination -->
    <div class="pagination" *ngIf="pagination.pages > 1">
      <button [disabled]="pagination.page <= 1" (click)="goPage(pagination.page - 1)">«</button>
      <button *ngFor="let p of getPages()" [class.active]="p === pagination.page" (click)="goPage(p)">{{ p }}</button>
      <button [disabled]="pagination.page >= pagination.pages" (click)="goPage(pagination.page + 1)">»</button>
    </div>

    <!-- Modal Form -->
    <div class="modal-overlay" *ngIf="showForm" (click)="showForm = false">
      <div class="modal-box" (click)="$event.stopPropagation()">
        <div class="modal-header">
          <h3>{{ editingId ? 'Sửa' : 'Thêm' }} khuyến mãi</h3>
          <button class="btn-close" (click)="showForm = false">&times;</button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label>Mã khuyến mãi *</label>
            <input type="text" [(ngModel)]="form.code" class="form-control" placeholder="VD: SALE20">
          </div>
          <div class="form-group">
            <label>Tên *</label>
            <input type="text" [(ngModel)]="form.name" class="form-control" placeholder="Giảm 20% đơn hàng">
          </div>
          <div class="form-group">
            <label>Mô tả</label>
            <textarea [(ngModel)]="form.description" class="form-control" rows="2"></textarea>
          </div>
          <div class="form-row">
            <div class="form-group">
              <label>Loại *</label>
              <select [(ngModel)]="form.type" class="form-control">
                <option value="Percentage">Phần trăm (%)</option>
                <option value="FixedAmount">Số tiền cố định</option>
                <option value="FreeShipping">Miễn phí ship</option>
                <option value="BuyXGetY">Mua X tặng Y</option>
              </select>
            </div>
            <div class="form-group">
              <label>Giá trị *</label>
              <input type="number" [(ngModel)]="form.value" class="form-control" [placeholder]="form.type === 'Percentage' ? 'VD: 20' : 'VD: 50000'">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group">
              <label>Đơn tối thiểu</label>
              <input type="number" [(ngModel)]="form.minOrderAmount" class="form-control" placeholder="0">
            </div>
            <div class="form-group">
              <label>Giảm tối đa</label>
              <input type="number" [(ngModel)]="form.maxDiscountAmount" class="form-control" placeholder="0 = không giới hạn">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group">
              <label>Giới hạn sử dụng</label>
              <input type="number" [(ngModel)]="form.usageLimit" class="form-control" placeholder="0 = không giới hạn">
            </div>
            <div class="form-group">
              <label>Mỗi user</label>
              <input type="number" [(ngModel)]="form.perUserLimit" class="form-control" placeholder="1">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group">
              <label>Ngày bắt đầu *</label>
              <input type="date" [(ngModel)]="form.startDate" class="form-control">
            </div>
            <div class="form-group">
              <label>Ngày kết thúc *</label>
              <input type="date" [(ngModel)]="form.endDate" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <label>
              <input type="checkbox" [(ngModel)]="form.isActive"> Hoạt động
            </label>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-outline" (click)="showForm = false">Hủy</button>
          <button class="btn btn-gold" (click)="savePromo()">{{ editingId ? 'Cập nhật' : 'Tạo mới' }}</button>
        </div>
      </div>
    </div>
  `,
  styles: [`
    :host { display: block; }
    .page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; }
    .page-header h2 { font-weight: 600; font-size: 1.4rem; color: #1a1a1a; margin: 0; }
    .page-header h2 i { color: #D4AF37; margin-right: 8px; }
    .card { border: none; border-radius: 12px; box-shadow: 0 2px 12px rgba(0,0,0,.08); background: #fff; margin-bottom: 16px; }
    .card-body { padding: 16px; }
    .p-0 { padding: 0 !important; }
    .table-responsive { overflow-x: auto; }
    .adm-table { width: 100%; border-collapse: collapse; }
    .adm-table th, .adm-table td { padding: 10px 14px; border-bottom: 1px solid #f0f0f0; font-size: .85rem; }
    .adm-table thead th { background: #f8f9fa; font-weight: 600; white-space: nowrap; }
    .adm-table tbody tr:hover { background: rgba(212,175,55,.05); }
    .text-gold { color: #D4AF37; }
    .text-muted { color: #6c757d; }
    .text-center { text-align: center; }
    .py-4 { padding: 30px 0; }
    .st-badge { padding: 3px 10px; border-radius: 4px; font-size: .73rem; font-weight: 500; color: #fff; display: inline-block; margin: 2px 0; }
    .st-active { background: #28a745; }
    .st-inactive { background: #6c757d; }
    .st-expired { background: #dc3545; }
    .btn { padding: 8px 16px; border: none; border-radius: 6px; cursor: pointer; font-size: .85rem; }
    .btn-gold { background: #D4AF37; color: #fff; }
    .btn-gold:hover { background: #B8960C; }
    .btn-outline { background: #f8f9fa; border: 1px solid #dee2e6; color: #333; }
    .btn-icon { border: none; padding: 6px 10px; border-radius: 4px; cursor: pointer; font-size: .8rem; margin-right: 4px; }
    .btn-edit { background: #17a2b8; color: #fff; }
    .btn-edit:hover { background: #138496; }
    .btn-danger { background: #dc3545; color: #fff; }
    .btn-danger:hover { background: #c82333; }
    .modal-overlay { position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,.5); z-index: 2000; display: flex; align-items: center; justify-content: center; }
    .modal-box { background: #fff; border-radius: 12px; width: 580px; max-width: 95vw; max-height: 90vh; overflow-y: auto; }
    .modal-header { display: flex; justify-content: space-between; align-items: center; padding: 16px 20px; border-bottom: 1px solid #f0f0f0; }
    .modal-header h3 { margin: 0; font-size: 1.1rem; font-weight: 600; }
    .btn-close { background: none; border: none; font-size: 1.5rem; cursor: pointer; color: #6c757d; }
    .modal-body { padding: 20px; }
    .modal-footer { padding: 12px 20px; border-top: 1px solid #f0f0f0; display: flex; justify-content: flex-end; gap: 8px; }
    .form-group { margin-bottom: 12px; }
    .form-group label { display: block; font-size: .85rem; font-weight: 500; margin-bottom: 4px; color: #333; }
    .form-control { width: 100%; padding: 8px 12px; border: 1px solid #dee2e6; border-radius: 6px; font-size: .85rem; box-sizing: border-box; }
    .form-control:focus { outline: none; border-color: #D4AF37; }
    .form-row { display: flex; gap: 12px; }
    .form-row .form-group { flex: 1; }
    .pagination { display: flex; justify-content: center; gap: 4px; margin-top: 16px; }
    .pagination button { padding: 6px 12px; border: 1px solid #dee2e6; background: #fff; border-radius: 4px; cursor: pointer; font-size: .85rem; }
    .pagination button.active { background: #D4AF37; color: #fff; border-color: #D4AF37; }
    .pagination button:disabled { opacity: .5; cursor: not-allowed; }
  `]
})
export class AdminPromotionsComponent implements OnInit {
  promotions: any[] = [];
  pagination = { page: 1, limit: 20, total: 0, pages: 0 };
  showForm = false;
  editingId = '';
  form: any = {};

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    this.loadPromotions();
  }

  resetForm(): void {
    this.editingId = '';
    this.form = {
      code: '', name: '', description: '', type: 'Percentage', value: 0,
      minOrderAmount: 0, maxDiscountAmount: 0, usageLimit: 0, perUserLimit: 1,
      startDate: '', endDate: '', isActive: true
    };
  }

  loadPromotions(): void {
    this.api.get('/promotions', { page: this.pagination.page, limit: this.pagination.limit }).subscribe({
      next: (res: any) => {
        if (res.success) {
          this.promotions = res.data?.promotions || [];
          if (res.data?.pagination) this.pagination = { ...this.pagination, ...res.data.pagination };
        }
      },
      error: () => {}
    });
  }

  editPromo(promo: any): void {
    this.editingId = promo._id;
    this.form = {
      code: promo.code, name: promo.name, description: promo.description || '',
      type: promo.type, value: promo.value,
      minOrderAmount: promo.minOrderAmount || 0,
      maxDiscountAmount: promo.maxDiscountAmount || 0,
      usageLimit: promo.usageLimit || 0,
      perUserLimit: promo.perUserLimit || 1,
      startDate: promo.startDate?.substring(0, 10) || '',
      endDate: promo.endDate?.substring(0, 10) || '',
      isActive: promo.isActive
    };
    this.showForm = true;
  }

  savePromo(): void {
    if (!this.form.code || !this.form.name || !this.form.startDate || !this.form.endDate) {
      alert('Vui lòng điền đầy đủ thông tin bắt buộc');
      return;
    }
    const data = { ...this.form };
    const obs = this.editingId
      ? this.api.put(`/promotions/${this.editingId}`, data)
      : this.api.post('/promotions', data);

    obs.subscribe({
      next: (res: any) => {
        if (res.success) {
          this.showForm = false;
          this.loadPromotions();
        } else {
          alert(res.message || 'Lỗi');
        }
      },
      error: (err: any) => alert(err.error?.message || 'Lỗi server')
    });
  }

  deletePromo(promo: any): void {
    if (!confirm(`Xóa khuyến mãi "${promo.name}"?`)) return;
    this.api.delete(`/promotions/${promo._id}`).subscribe({
      next: () => this.loadPromotions(),
      error: () => alert('Lỗi khi xóa')
    });
  }

  isExpired(promo: any): boolean {
    return new Date(promo.endDate) < new Date();
  }

  getTypeName(type: string): string {
    const m: any = { Percentage: 'Phần trăm', FixedAmount: 'Cố định', FreeShipping: 'Free ship', BuyXGetY: 'Mua X tặng Y' };
    return m[type] || type;
  }

  goPage(p: number): void {
    this.pagination.page = p;
    this.loadPromotions();
  }

  getPages(): number[] {
    const pages = [];
    for (let i = 1; i <= this.pagination.pages; i++) pages.push(i);
    return pages;
  }
}
