// ume-frontend/src/app/pages/my-appointments/my-appointments.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-my-appointments',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './my-appointments.component.html',
  styleUrl: './my-appointments.component.scss'
})
export class MyAppointmentsComponent implements OnInit {
  appointments: any[] = [];
  loading = false;
  selectedStatus = '';
  cancelReason = '';
  cancellingId: string | null = null;

  // Success modal
  showSuccessModal = false;
  successMessage = '';

  // Review
  showReviewModal = false;
  reviewingAppointment: any = null;
  reviewRating = 5;
  reviewComment = '';
  reviewSubmitting = false;
  reviewedMap: { [key: string]: boolean } = {};
  hoverRating = 0;

  statuses = [
    { value: '', label: 'Tất cả' },
    { value: 'Pending', label: 'Chờ xác nhận' },
    { value: 'Confirmed', label: 'Đã xác nhận' },
    { value: 'InProgress', label: 'Đang thực hiện' },
    { value: 'Completed', label: 'Hoàn thành' },
    { value: 'Cancelled', label: 'Đã hủy' }
  ];

  constructor(
    private apiService: ApiService,
    private toastr: ToastrService
  ) {}

  ngOnInit(): void {
    this.loadAppointments();
  }

  loadAppointments(): void {
    this.loading = true;
    const params: any = {};
    if (this.selectedStatus) params.status = this.selectedStatus;

    this.apiService.getMyAppointments(params).subscribe({
      next: (res: any) => {
        this.appointments = res.data?.appointments || res.data?.items || [];
        this.loading = false;
        // Check which completed appointments already have reviews
        this.appointments.forEach(apt => {
          if (apt.status === 'Completed') {
            this.checkReviewed(apt._id);
          }
        });
      },
      error: () => { this.loading = false; }
    });
  }

  checkReviewed(appointmentId: string): void {
    this.apiService.get(`/reviews/check/${appointmentId}`).subscribe({
      next: (res: any) => {
        this.reviewedMap[appointmentId] = res.data?.reviewed || false;
      },
      error: () => {}
    });
  }

  filterByStatus(status: string): void {
    this.selectedStatus = status;
    this.loadAppointments();
  }

  showCancelDialog(id: string): void {
    this.cancellingId = id;
    this.cancelReason = '';
  }

  closeCancelDialog(): void {
    this.cancellingId = null;
  }

  confirmCancel(): void {
    if (!this.cancellingId) return;
    this.apiService.cancelAppointment(this.cancellingId, { cancelReason: this.cancelReason }).subscribe({
      next: () => {
        this.cancellingId = null;
        this.successMessage = 'Đã hủy lịch hẹn thành công!';
        this.showSuccessModal = true;
        this.loadAppointments();
      },
      error: (err: any) => {
        this.toastr.error(err.error?.message || 'Hủy lịch hẹn thất bại', 'Lỗi');
      }
    });
  }

  // Review methods
  openReviewModal(apt: any): void {
    this.reviewingAppointment = apt;
    this.reviewRating = 5;
    this.reviewComment = '';
    this.hoverRating = 0;
    this.showReviewModal = true;
  }

  closeReviewModal(): void {
    this.showReviewModal = false;
    this.reviewingAppointment = null;
  }

  setRating(star: number): void {
    this.reviewRating = star;
  }

  setHoverRating(star: number): void {
    this.hoverRating = star;
  }

  resetHover(): void {
    this.hoverRating = 0;
  }

  getStarClass(star: number): string {
    const active = this.hoverRating || this.reviewRating;
    return star <= active ? 'star active' : 'star';
  }

  getRatingLabel(): string {
    const active = this.hoverRating || this.reviewRating;
    const labels: { [key: number]: string } = {
      1: 'Rất không hài lòng',
      2: 'Không hài lòng',
      3: 'Bình thường',
      4: 'Hài lòng',
      5: 'Rất hài lòng'
    };
    return labels[active] || '';
  }

  submitReview(): void {
    if (!this.reviewingAppointment) return;
    this.reviewSubmitting = true;

    const formData = new FormData();
    formData.append('appointmentId', this.reviewingAppointment._id);
    formData.append('rating', this.reviewRating.toString());
    formData.append('comment', this.reviewComment);

    // Attach the first service from the appointment
    if (this.reviewingAppointment.services?.length > 0) {
      const svc = this.reviewingAppointment.services[0];
      const serviceId = svc.service?._id || svc.service;
      if (serviceId) formData.append('serviceId', serviceId);
    }

    this.apiService.createReview(formData).subscribe({
      next: () => {
        this.toastr.success('Cảm ơn bạn đã đánh giá!', 'Thành công');
        this.reviewedMap[this.reviewingAppointment._id] = true;
        this.closeReviewModal();
        this.reviewSubmitting = false;
      },
      error: (err: any) => {
        this.reviewSubmitting = false;
        this.toastr.error(err.error?.message || 'Gửi đánh giá thất bại', 'Lỗi');
      }
    });
  }

  getStatusLabel(status: string): string {
    const map: any = {
      Pending: 'Chờ xác nhận',
      Confirmed: 'Đã xác nhận',
      InProgress: 'Đang thực hiện',
      Completed: 'Hoàn thành',
      Cancelled: 'Đã hủy'
    };
    return map[status] || status;
  }

  getStatusClass(status: string): string {
    const map: any = {
      Pending: 'pending',
      Confirmed: 'confirmed',
      InProgress: 'in-progress',
      Completed: 'completed',
      Cancelled: 'cancelled'
    };
    return map[status] || '';
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString('vi-VN', {
      year: 'numeric', month: '2-digit', day: '2-digit'
    });
  }
}

<div class="my-appointments-page">
  <div class="page-header">
    <div class="container">
      <h1><i class="fas fa-calendar-alt"></i> Lịch hẹn của tôi</h1>
    </div>
  </div>

  <div class="container">
    <!-- Status Filter -->
    <div class="status-tabs">
      <button *ngFor="let s of statuses"
              [class.active]="selectedStatus === s.value"
              (click)="filterByStatus(s.value)">
        {{ s.label }}
      </button>
    </div>

    <div class="loading-spinner" *ngIf="loading">
      <i class="fas fa-spinner fa-spin"></i> Đang tải...
    </div>

    <div class="appointments-list" *ngIf="!loading">
      <div class="appointment-card" *ngFor="let apt of appointments">
        <div class="card-header">
          <div class="apt-code">
            <i class="fas fa-hashtag"></i> {{ apt.appointmentCode }}
          </div>
          <span class="status-badge" [ngClass]="getStatusClass(apt.status)">
            {{ getStatusLabel(apt.status) }}
          </span>
        </div>

        <div class="card-body">
          <div class="info-row">
            <i class="fas fa-calendar"></i>
            <span>{{ formatDate(apt.appointmentDate) }} lúc {{ apt.startTime }}</span>
          </div>
          <div class="info-row" *ngIf="apt.staff">
            <i class="fas fa-user"></i>
            <span>{{ apt.staff.nickName || apt.staff.fullName }}</span>
          </div>
          <div class="info-row" *ngIf="apt.pet">
            <i class="fas fa-paw"></i>
            <span>{{ apt.pet.name }}</span>
          </div>
          <div class="services-list">
            <span class="service-tag" *ngFor="let s of apt.services">
              {{ s.serviceName || s.service?.name }}
            </span>
          </div>
        </div>

        <div class="card-footer">
          <span class="total-amount">{{ formatPrice(apt.finalAmount || apt.totalAmount) }}</span>
          <div class="footer-actions">
            <button class="btn-review" *ngIf="apt.status === 'Completed' && !reviewedMap[apt._id]"
                    (click)="openReviewModal(apt)">
              <i class="fas fa-star"></i> Đánh giá
            </button>
            <span class="reviewed-badge" *ngIf="apt.status === 'Completed' && reviewedMap[apt._id]">
              <i class="fas fa-check-circle"></i> Đã đánh giá
            </span>
            <button class="btn-cancel" *ngIf="apt.status === 'Pending'"
                    (click)="showCancelDialog(apt._id)">
              <i class="fas fa-times"></i> Hủy lịch
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="empty-state" *ngIf="!loading && appointments.length === 0">
      <i class="fas fa-calendar-times"></i>
      <p>Bạn chưa có lịch hẹn nào</p>
    </div>

    <!-- Cancel Dialog -->
    <div class="modal-overlay" *ngIf="cancellingId" (click)="closeCancelDialog()">
      <div class="modal-content" (click)="$event.stopPropagation()">
        <h3>Hủy lịch hẹn</h3>
        <p>Bạn có chắc muốn hủy lịch hẹn này?</p>
        <div class="form-group">
          <label>Lý do hủy</label>
          <textarea [(ngModel)]="cancelReason" placeholder="Nhập lý do hủy..." rows="3"></textarea>
        </div>
        <div class="modal-actions">
          <button class="btn-secondary" (click)="closeCancelDialog()">Đóng</button>
          <button class="btn-danger" (click)="confirmCancel()">Xác nhận hủy</button>
        </div>
      </div>
    </div>

    <!-- Review Modal -->
    <div class="modal-overlay" *ngIf="showReviewModal" (click)="closeReviewModal()">
      <div class="review-modal" (click)="$event.stopPropagation()">
        <button class="modal-close" (click)="closeReviewModal()">
          <i class="fas fa-times"></i>
        </button>

        <div class="review-modal-header">
          <div class="review-icon">
            <i class="fas fa-star"></i>
          </div>
          <h3>Đánh giá dịch vụ</h3>
          <p class="review-apt-code">{{ reviewingAppointment?.appointmentCode }}</p>
          <div class="review-services" *ngIf="reviewingAppointment?.services?.length">
            <span *ngFor="let s of reviewingAppointment.services" class="service-tag">
              {{ s.serviceName || s.service?.name }}
            </span>
          </div>
        </div>

        <div class="review-modal-body">
          <div class="rating-section">
            <label>Mức độ hài lòng</label>
            <div class="stars-input" (mouseleave)="resetHover()">
              <span *ngFor="let star of [1,2,3,4,5]"
                    [class]="getStarClass(star)"
                    (click)="setRating(star)"
                    (mouseenter)="setHoverRating(star)">
                ★
              </span>
            </div>
            <span class="rating-label" [ngClass]="'rating-' + (hoverRating || reviewRating)">
              {{ getRatingLabel() }}
            </span>
          </div>

          <div class="comment-section">
            <label>Nhận xét của bạn</label>
            <textarea [(ngModel)]="reviewComment"
                      placeholder="Chia sẻ trải nghiệm của bạn về dịch vụ..."
                      rows="4"></textarea>
          </div>
        </div>

        <div class="review-modal-footer">
          <button class="btn-secondary" (click)="closeReviewModal()">Hủy</button>
          <button class="btn-submit-review" (click)="submitReview()" [disabled]="reviewSubmitting">
            <i class="fas fa-paper-plane" *ngIf="!reviewSubmitting"></i>
            <i class="fas fa-spinner fa-spin" *ngIf="reviewSubmitting"></i>
            {{ reviewSubmitting ? 'Đang gửi...' : 'Gửi đánh giá' }}
          </button>
        </div>
      </div>
    </div>

    <!-- Success Modal -->
    <div class="success-overlay" *ngIf="showSuccessModal" (click)="showSuccessModal = false">
      <div class="success-modal" (click)="$event.stopPropagation()">
        <div class="success-icon">
          <i class="fas fa-check-circle"></i>
        </div>
        <h2>{{ successMessage }}</h2>
        <p class="success-msg">Thao tác đã được thực hiện thành công</p>
        <button class="btn-success-close" (click)="showSuccessModal = false">
          <i class="fas fa-thumbs-up"></i> Đã hiểu
        </button>
      </div>
    </div>
  </div>
</div>

// ume-react/src/pages/my-appointments/MyAppointments.tsx
import { useState, useEffect } from 'react';
import { appointmentApi, reviewApi } from '../../services/api';
import api from '../../services/api';
import toast from 'react-hot-toast';
import './MyAppointments.scss';

const formatPrice = (p: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(p);
const formatDate = (d: string) => new Date(d).toLocaleDateString('vi-VN', { year: 'numeric', month: '2-digit', day: '2-digit' });

const statuses = [
  { value: '', label: 'Tất cả' }, { value: 'Pending', label: 'Chờ xác nhận' },
  { value: 'Confirmed', label: 'Đã xác nhận' }, { value: 'InProgress', label: 'Đang thực hiện' },
  { value: 'Completed', label: 'Hoàn thành' }, { value: 'Cancelled', label: 'Đã hủy' },
];
const statusLabels: any = { Pending: 'Chờ xác nhận', Confirmed: 'Đã xác nhận', InProgress: 'Đang thực hiện', Completed: 'Hoàn thành', Cancelled: 'Đã hủy' };
const ratingLabels: any = { 1: 'Rất không hài lòng', 2: 'Không hài lòng', 3: 'Bình thường', 4: 'Hài lòng', 5: 'Rất hài lòng' };

export default function MyAppointments() {
  const [appointments, setAppointments] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedStatus, setSelectedStatus] = useState('');
  const [cancellingId, setCancellingId] = useState<string | null>(null);
  const [cancelReason, setCancelReason] = useState('');

  // Review
  const [showReview, setShowReview] = useState(false);
  const [reviewApt, setReviewApt] = useState<any>(null);
  const [reviewRating, setReviewRating] = useState(5);
  const [reviewComment, setReviewComment] = useState('');
  const [reviewSubmitting, setReviewSubmitting] = useState(false);
  const [hoverRating, setHoverRating] = useState(0);
  const [reviewedMap, setReviewedMap] = useState<Record<string, boolean>>({});

  useEffect(() => { loadAppointments(); }, []);

  const loadAppointments = async (status?: string) => {
    setLoading(true);
    try {
      const params: any = {};
      const s = status ?? selectedStatus;
      if (s) params.status = s;
      const r = await appointmentApi.getMyAppointments(params);
      const list = r.data?.data?.appointments || r.data?.data?.items || [];
      setAppointments(list);
      list.forEach((a: any) => { if (a.status === 'Completed') checkReviewed(a._id); });
    } catch {} finally { setLoading(false); }
  };

  const checkReviewed = async (id: string) => {
    try {
      const r = await api.get(`/reviews/check/${id}`);
      setReviewedMap(m => ({ ...m, [id]: r.data?.data?.reviewed || false }));
    } catch {}
  };

  const filterByStatus = (s: string) => { setSelectedStatus(s); loadAppointments(s); };

  const confirmCancel = async () => {
    if (!cancellingId) return;
    try {
      await appointmentApi.cancel(cancellingId, { cancelReason });
      toast.success('Đã hủy lịch hẹn thành công');
      setCancellingId(null);
      loadAppointments();
    } catch (err: any) { toast.error(err.response?.data?.message || 'Hủy thất bại'); }
  };

  const openReview = (apt: any) => {
    setReviewApt(apt); setReviewRating(5); setReviewComment(''); setHoverRating(0); setShowReview(true);
  };

  const submitReview = async () => {
    if (!reviewApt) return;
    setReviewSubmitting(true);
    try {
      const fd = new FormData();
      fd.append('appointmentId', reviewApt._id);
      fd.append('rating', reviewRating.toString());
      fd.append('comment', reviewComment);
      if (reviewApt.services?.length > 0) {
        const sid = reviewApt.services[0].service?._id || reviewApt.services[0].service;
        if (sid) fd.append('serviceId', sid);
      }
      await reviewApi.create(fd);
      toast.success('Cảm ơn bạn đã đánh giá!');
      setReviewedMap(m => ({ ...m, [reviewApt._id]: true }));
      setShowReview(false);
    } catch (err: any) { toast.error(err.response?.data?.message || 'Gửi đánh giá thất bại'); }
    finally { setReviewSubmitting(false); }
  };

  const activeRating = hoverRating || reviewRating;

  return (
    <div className="my-appointments-page">
      <div className="page-header"><div className="container"><h1>📅 Lịch hẹn của tôi</h1></div></div>
      <div className="container">
        <div className="status-tabs">
          {statuses.map(s => (
            <button key={s.value} className={selectedStatus === s.value ? 'active' : ''} onClick={() => filterByStatus(s.value)}>{s.label}</button>
          ))}
        </div>

        {loading && <div className="loading-center">⏳ Đang tải...</div>}
        {!loading && appointments.length === 0 && <div className="empty-state">📅<p>Bạn chưa có lịch hẹn nào</p></div>}

        <div className="appointments-list">
          {appointments.map(apt => (
            <div key={apt._id} className="appointment-card">
              <div className="card-header">
                <div className="apt-code"># {apt.appointmentCode}</div>
                <span className={`status-badge ${apt.status?.toLowerCase()}`}>{statusLabels[apt.status] || apt.status}</span>
              </div>
              <div className="card-body">
                <div className="info-row">📅 {formatDate(apt.appointmentDate)} lúc {apt.startTime}</div>
                {apt.staff && <div className="info-row">👤 {apt.staff.nickName || apt.staff.fullName}</div>}
                {apt.pet && <div className="info-row">🐾 {apt.pet.name}</div>}
                <div className="services-tags">
                  {(apt.services || []).map((s: any, i: number) => <span key={i} className="service-tag">{s.serviceName || s.service?.name}</span>)}
                </div>
              </div>
              <div className="card-footer">
                <span className="total-amount">{formatPrice(apt.finalAmount || apt.totalAmount)}</span>
                <div className="footer-actions">
                  {apt.status === 'Completed' && !reviewedMap[apt._id] && <button className="btn-review" onClick={() => openReview(apt)}>⭐ Đánh giá</button>}
                  {apt.status === 'Completed' && reviewedMap[apt._id] && <span className="reviewed-badge">✅ Đã đánh giá</span>}
                  {apt.status === 'Pending' && <button className="btn-cancel" onClick={() => { setCancellingId(apt._id); setCancelReason(''); }}>❌ Hủy lịch</button>}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Cancel Modal */}
        {cancellingId && (
          <div className="modal-overlay" onClick={() => setCancellingId(null)}>
            <div className="modal-content" onClick={e => e.stopPropagation()}>
              <h3>Hủy lịch hẹn</h3><p>Bạn có chắc muốn hủy lịch hẹn này?</p>
              <textarea value={cancelReason} onChange={e => setCancelReason(e.target.value)} placeholder="Lý do hủy..." rows={3} />
              <div className="modal-actions"><button className="btn-secondary" onClick={() => setCancellingId(null)}>Đóng</button><button className="btn-danger" onClick={confirmCancel}>Xác nhận hủy</button></div>
            </div>
          </div>
        )}

        {/* Review Modal */}
        {showReview && (
          <div className="modal-overlay" onClick={() => setShowReview(false)}>
            <div className="review-modal" onClick={e => e.stopPropagation()}>
              <button className="close-btn" onClick={() => setShowReview(false)}>×</button>
              <h3>⭐ Đánh giá dịch vụ</h3>
              {reviewApt && <p className="review-code">{reviewApt.appointmentCode}</p>}
              {reviewApt?.services?.length > 0 && <div className="review-services">{reviewApt.services.map((s: any, i: number) => <span key={i} className="service-tag">{s.serviceName || s.service?.name}</span>)}</div>}
              <div className="stars-input" onMouseLeave={() => setHoverRating(0)}>
                {[1,2,3,4,5].map(s => <span key={s} className={s <= activeRating ? 'star active' : 'star'} onClick={() => setReviewRating(s)} onMouseEnter={() => setHoverRating(s)}>★</span>)}
              </div>
              <div className="rating-label">{ratingLabels[activeRating]}</div>
              <textarea value={reviewComment} onChange={e => setReviewComment(e.target.value)} placeholder="Chia sẻ trải nghiệm..." rows={4} />
              <div className="review-actions"><button className="btn-secondary" onClick={() => setShowReview(false)}>Hủy</button><button className="btn-submit" onClick={submitReview} disabled={reviewSubmitting}>{reviewSubmitting ? '⏳ Đang gửi...' : '📩 Gửi đánh giá'}</button></div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
