// ume-react/src/pages/register/Register.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import toast from 'react-hot-toast';
import './Register.scss';

export default function Register() {
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [acceptTerms, setAcceptTerms] = useState(false);
  const [loading, setLoading] = useState(false);
  const { register } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!fullName || !email || !password || !confirmPassword) {
      toast.error('Vui lòng nhập đầy đủ thông tin');
      return;
    }
    if (password.length < 6) {
      toast.error('Mật khẩu phải có ít nhất 6 ký tự');
      return;
    }
    if (password !== confirmPassword) {
      toast.error('Mật khẩu xác nhận không khớp');
      return;
    }
    if (!acceptTerms) {
      toast.error('Vui lòng đồng ý với điều khoản sử dụng');
      return;
    }

    setLoading(true);
    try {
      await register({ fullName, email, password, phoneNumber: phoneNumber || undefined });
      toast.success('Đăng ký thành công! Chào mừng bạn đến với PetCare.');
      navigate('/');
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Đăng ký thất bại. Vui lòng thử lại.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="register-page">
      <div className="paw-decorations">
        {[1,2,3,4,5].map(i => <span key={i} className={`paw paw-${i}`}>🐾</span>)}
      </div>

      <div className="register-container">
        <div className="register-illustration">
          <div className="illustration-content">
            <div className="illustration-emoji">🐾</div>
            <h2>Tham gia PetCare</h2>
            <p>Tạo tài khoản miễn phí để trải nghiệm dịch vụ chăm sóc thú cưng tốt nhất!</p>
            <div className="illustration-benefits">
              <div className="benefit"><span className="benefit-icon">🎁</span><div><h4>Ưu đãi thành viên</h4><p>Giảm 10% cho đơn hàng đầu tiên</p></div></div>
              <div className="benefit"><span className="benefit-icon">📅</span><div><h4>Đặt lịch dễ dàng</h4><p>Quản lý lịch hẹn tiện lợi</p></div></div>
              <div className="benefit"><span className="benefit-icon">💝</span><div><h4>Tích điểm thưởng</h4><p>Nhận điểm thưởng mỗi lần sử dụng</p></div></div>
            </div>
            <div className="illustration-pets">
              <span>🐶</span><span>🐱</span><span>🐰</span><span>🦜</span><span>🐹</span>
            </div>
          </div>
        </div>

        <div className="register-form-section">
          <div className="form-wrapper">
            <div className="form-header">
              <Link to="/" className="form-logo">🐾 PetCare</Link>
              <h1>Đăng ký tài khoản</h1>
              <p>Điền thông tin để tạo tài khoản mới</p>
            </div>

            <form onSubmit={handleSubmit} className="register-form">
              <div className="form-group">
                <label htmlFor="fullName">👤 Họ và tên *</label>
                <input type="text" id="fullName" value={fullName} onChange={e => setFullName(e.target.value)} placeholder="Nhập họ và tên" required />
              </div>

              <div className="form-group">
                <label htmlFor="email">📧 Email *</label>
                <input type="email" id="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Nhập email của bạn" required autoComplete="email" />
              </div>

              <div className="form-group">
                <label htmlFor="phone">📞 Số điện thoại</label>
                <input type="tel" id="phone" value={phoneNumber} onChange={e => setPhoneNumber(e.target.value)} placeholder="Nhập số điện thoại (không bắt buộc)" />
              </div>

              <div className="form-group">
                <label htmlFor="password">🔒 Mật khẩu *</label>
                <div className="password-input">
                  <input type={showPassword ? 'text' : 'password'} id="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Ít nhất 6 ký tự" required />
                  <button type="button" className="toggle-password" onClick={() => setShowPassword(!showPassword)}>
                    {showPassword ? '🙈' : '👁️'}
                  </button>
                </div>
              </div>

              <div className="form-group">
                <label htmlFor="confirmPassword">🔒 Xác nhận mật khẩu *</label>
                <div className="password-input">
                  <input type={showConfirmPassword ? 'text' : 'password'} id="confirmPassword" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} placeholder="Nhập lại mật khẩu" required />
                  <button type="button" className="toggle-password" onClick={() => setShowConfirmPassword(!showConfirmPassword)}>
                    {showConfirmPassword ? '🙈' : '👁️'}
                  </button>
                </div>
              </div>

              <div className="terms-check">
                <label>
                  <input type="checkbox" checked={acceptTerms} onChange={e => setAcceptTerms(e.target.checked)} />
                  Tôi đồng ý với <a href="#">Điều khoản sử dụng</a> và <a href="#">Chính sách bảo mật</a>
                </label>
              </div>

              <button type="submit" className="submit-btn" disabled={loading}>
                {loading ? '⏳ Đang xử lý...' : '✨ Đăng ký'}
              </button>
            </form>

            <div className="form-footer">
              <p>Đã có tài khoản? <Link to="/login">Đăng nhập</Link></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ume-frontend/src/app/pages/register/register.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink, Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss'
})
export class RegisterComponent {
  fullName = '';
  email = '';
  phoneNumber = '';
  password = '';
  confirmPassword = '';
  showPassword = false;
  showConfirmPassword = false;
  acceptTerms = false;
  loading = false;

  constructor(
    private authService: AuthService,
    private router: Router,
    private toastr: ToastrService
  ) {}

  togglePassword(): void {
    this.showPassword = !this.showPassword;
  }

  toggleConfirmPassword(): void {
    this.showConfirmPassword = !this.showConfirmPassword;
  }

  register(): void {
    if (!this.fullName || !this.email || !this.password || !this.confirmPassword) {
      this.toastr.warning('Vui lòng nhập đầy đủ thông tin');
      return;
    }

    if (this.password.length < 6) {
      this.toastr.warning('Mật khẩu phải có ít nhất 6 ký tự');
      return;
    }

    if (this.password !== this.confirmPassword) {
      this.toastr.warning('Mật khẩu xác nhận không khớp');
      return;
    }

    if (!this.acceptTerms) {
      this.toastr.warning('Vui lòng đồng ý với điều khoản sử dụng');
      return;
    }

    this.loading = true;
    this.authService.register({
      fullName: this.fullName,
      email: this.email,
      password: this.password,
      phoneNumber: this.phoneNumber || undefined
    }).subscribe({
      next: () => {
        this.toastr.success('Đăng ký thành công! Chào mừng bạn đến với PetCare.');
        this.router.navigate(['/']);
      },
      error: (err) => {
        this.loading = false;
        this.toastr.error(err.error?.message || 'Đăng ký thất bại. Vui lòng thử lại.');
      }
    });
  }
}

<div class="register-page">
  <!-- Decorative paw prints -->
  <div class="paw-decorations">
    <span class="paw paw-1">🐾</span>
    <span class="paw paw-2">🐾</span>
    <span class="paw paw-3">🐾</span>
    <span class="paw paw-4">🐾</span>
    <span class="paw paw-5">🐾</span>
  </div>

  <div class="register-container">
    <!-- Left - Illustration -->
    <div class="register-illustration">
      <div class="illustration-content">
        <div class="illustration-emoji">🐾</div>
        <h2>Tham gia PetCare</h2>
        <p>Tạo tài khoản miễn phí để trải nghiệm dịch vụ chăm sóc thú cưng tốt nhất!</p>
        <div class="illustration-benefits">
          <div class="benefit">
            <div class="benefit-icon">🎁</div>
            <div>
              <h4>Ưu đãi thành viên</h4>
              <p>Giảm 10% cho đơn hàng đầu tiên</p>
            </div>
          </div>
          <div class="benefit">
            <div class="benefit-icon">📅</div>
            <div>
              <h4>Đặt lịch dễ dàng</h4>
              <p>Quản lý lịch hẹn tiện lợi</p>
            </div>
          </div>
          <div class="benefit">
            <div class="benefit-icon">💝</div>
            <div>
              <h4>Tích điểm thưởng</h4>
              <p>Nhận điểm thưởng mỗi lần sử dụng</p>
            </div>
          </div>
        </div>
        <div class="illustration-pets">
          <span>🐶</span>
          <span>🐱</span>
          <span>🐰</span>
          <span>🦜</span>
          <span>🐹</span>
        </div>
      </div>
    </div>

    <!-- Right - Form -->
    <div class="register-form-section">
      <div class="form-wrapper">
        <div class="form-header">
          <a routerLink="/" class="form-logo">🐾 PetCare</a>
          <h1>Tạo tài khoản</h1>
          <p>Đăng ký để bắt đầu trải nghiệm</p>
        </div>

        <!-- Register Form -->
        <form (ngSubmit)="register()" class="register-form">
          <div class="form-group">
            <label for="fullName">
              <i class="fas fa-user"></i> Họ và tên <span class="required">*</span>
            </label>
            <input
              type="text"
              id="fullName"
              [(ngModel)]="fullName"
              name="fullName"
              placeholder="Nhập họ và tên đầy đủ"
              required
              autocomplete="name"
            >
          </div>

          <div class="form-group">
            <label for="email">
              <i class="fas fa-envelope"></i> Email <span class="required">*</span>
            </label>
            <input
              type="email"
              id="email"
              [(ngModel)]="email"
              name="email"
              placeholder="Nhập email của bạn"
              required
              autocomplete="email"
            >
          </div>

          <div class="form-group">
            <label for="phoneNumber">
              <i class="fas fa-phone"></i> Số điện thoại
            </label>
            <input
              type="tel"
              id="phoneNumber"
              [(ngModel)]="phoneNumber"
              name="phoneNumber"
              placeholder="Nhập số điện thoại (tùy chọn)"
              autocomplete="tel"
            >
          </div>

          <div class="form-row">
            <div class="form-group">
              <label for="password">
                <i class="fas fa-lock"></i> Mật khẩu <span class="required">*</span>
              </label>
              <div class="password-input">
                <input
                  [type]="showPassword ? 'text' : 'password'"
                  id="password"
                  [(ngModel)]="password"
                  name="password"
                  placeholder="Tối thiểu 6 ký tự"
                  required
                  autocomplete="new-password"
                >
                <button type="button" class="toggle-password" (click)="togglePassword()">
                  <i [class]="showPassword ? 'fas fa-eye-slash' : 'fas fa-eye'"></i>
                </button>
              </div>
            </div>

            <div class="form-group">
              <label for="confirmPassword">
                <i class="fas fa-lock"></i> Xác nhận <span class="required">*</span>
              </label>
              <div class="password-input">
                <input
                  [type]="showConfirmPassword ? 'text' : 'password'"
                  id="confirmPassword"
                  [(ngModel)]="confirmPassword"
                  name="confirmPassword"
                  placeholder="Nhập lại mật khẩu"
                  required
                  autocomplete="new-password"
                >
                <button type="button" class="toggle-password" (click)="toggleConfirmPassword()">
                  <i [class]="showConfirmPassword ? 'fas fa-eye-slash' : 'fas fa-eye'"></i>
                </button>
              </div>
            </div>
          </div>

          <div class="password-match-hint" *ngIf="confirmPassword && password !== confirmPassword">
            <i class="fas fa-exclamation-circle"></i> Mật khẩu xác nhận không khớp
          </div>

          <div class="password-strength" *ngIf="password">
            <div class="strength-bar">
              <div class="strength-fill"
                [style.width.%]="password.length >= 12 ? 100 : password.length >= 8 ? 66 : password.length >= 6 ? 33 : 15"
                [class.weak]="password.length < 6"
                [class.medium]="password.length >= 6 && password.length < 8"
                [class.strong]="password.length >= 8 && password.length < 12"
                [class.very-strong]="password.length >= 12"
              ></div>
            </div>
            <span class="strength-text"
              [class.weak]="password.length < 6"
              [class.medium]="password.length >= 6 && password.length < 8"
              [class.strong]="password.length >= 8 && password.length < 12"
              [class.very-strong]="password.length >= 12"
            >
              {{ password.length < 6 ? 'Yếu' : password.length < 8 ? 'Trung bình' : password.length < 12 ? 'Mạnh' : 'Rất mạnh' }}
            </span>
          </div>

          <div class="terms-checkbox">
            <label>
              <input type="checkbox" [(ngModel)]="acceptTerms" name="acceptTerms">
              <span>Tôi đồng ý với <a href="#" (click)="$event.preventDefault()">Điều khoản sử dụng</a> và <a href="#" (click)="$event.preventDefault()">Chính sách bảo mật</a></span>
            </label>
          </div>

          <button type="submit" class="submit-btn" [disabled]="loading">
            <span *ngIf="!loading">
              <i class="fas fa-user-plus"></i> Đăng ký
            </span>
            <span *ngIf="loading" class="spinner">
              <i class="fas fa-spinner fa-spin"></i> Đang xử lý...
            </span>
          </button>
        </form>

        <div class="form-footer">
          <p>Đã có tài khoản? <a routerLink="/login">Đăng nhập</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
