// ume-react/src/pages/pet-detail/PetDetail.tsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { petApi } from '../../services/api';
import { getImageUrl } from '../../services/api';
import { useCart } from '../../contexts/CartContext';
import { useAuth } from '../../contexts/AuthContext';
import toast from 'react-hot-toast';
import './PetDetail.scss';

const formatPrice = (price: number) => {
  if (!price) return 'Miễn phí';
  return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
};

const typeNames: Record<string, string> = { Dog: 'Chó', Cat: 'Mèo', Bird: 'Chim', Fish: 'Cá', Hamster: 'Hamster', Rabbit: 'Thỏ', Other: 'Khác' };
const genderNames: Record<string, string> = { Male: 'Đực', Female: 'Cái', Unknown: 'Chưa rõ' };
const listingLabels: Record<string, string> = { Sale: 'Đang bán', Adoption: 'Nhận nuôi' };

export default function PetDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { addPetToCart, items } = useCart();
  const { user, isLoggedIn } = useAuth();

  const [pet, setPet] = useState<any>(null);
  const [similarPets, setSimilarPets] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [isOwner, setIsOwner] = useState(false);

  useEffect(() => {
    if (id) loadPet(id);
  }, [id]);

  const loadPet = async (petId: string) => {
    setLoading(true);
    try {
      const res = await petApi.getById(petId);
      const p = res.data?.data || res.data;
      setPet(p);
      setIsOwner(!!isLoggedIn && p?.owner?._id === user?._id);
      loadSimilarPets(p);
    } catch {
      toast.error('Không tìm thấy thú cưng');
      navigate('/pets');
    } finally {
      setLoading(false);
    }
  };

  const loadSimilarPets = async (currentPet: any) => {
    if (!currentPet) return;
    try {
      const res = await petApi.getAll({ type: currentPet.type, limit: 4 });
      const all = res.data?.data?.pets || res.data?.data || [];
      setSimilarPets(all.filter((p: any) => p._id !== currentPet._id).slice(0, 4));
    } catch {}
  };

  const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(typeof window !== 'undefined' ? window.location.href : '')}`;

  const getAgeLabel = (p: any) => {
    if (!p?.age) return 'N/A';
    const unit = p.ageUnit === 'years' ? 'tuổi' : 'tháng';
    return `${p.age} ${unit}`;
  };

  const getPetCode = () => {
    if (!pet) return '';
    if (pet.code) return pet.code;
    const d = new Date(pet.createdAt);
    const y = d.getFullYear().toString().slice(-2);
    const m = (d.getMonth() + 1).toString().padStart(2, '0');
    const day = d.getDate().toString().padStart(2, '0');
    const idSlice = pet._id?.slice(-4) || '0000';
    return `PET${y}${m}${day}${idSlice}`;
  };

  const isPetInCart = () => items.some(i => i.product._id === pet?._id && i.itemType === 'pet');

  const handleAddToCart = () => {
    if (!isLoggedIn) { toast('Vui lòng đăng nhập', { icon: '⚠️' }); navigate('/login'); return; }
    addPetToCart(pet);
    toast.success(`Đã thêm ${pet.name} vào giỏ hàng!`);
  };

  if (loading) return (
    <div className="loading-state"><div className="spinner"></div><p>Đang tải thông tin thú cưng...</p></div>
  );

  if (!pet) return null;

  return (
    <div className="pet-detail-page">
      <div className="container">
        <div className="pet-detail-content">
          {/* Left: Image + QR */}
          <div className="pet-image-section">
            <div className="main-image">
              <img src={getImageUrl(pet.imageUrl)} alt={pet.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/default-pet.svg'; }} />
            </div>
            <div className="qr-section">
              <p>📱 Quét mã QR để chia sẻ</p>
              <img src={qrCodeUrl} alt="QR Code" className="qr-image" />
            </div>
          </div>

          {/* Right: Info */}
          <div className="pet-info-section">
            <h2 className="pet-name">🐾 {pet.name}</h2>
            <p className="pet-code">Mã: {getPetCode()}</p>

            {pet.listingType === 'Adoption' && !isOwner && (
              <div className="adoption-banner">❤️ Thú cưng cần tìm nhà yêu thương</div>
            )}
            {isOwner && (
              <div className="owner-banner">✓ Đây là thú cưng của bạn</div>
            )}

            {/* Price */}
            {pet.listingType === 'Sale' && !isOwner && (
              <div className="price-section">
                <span className="price">{formatPrice(pet.listingPrice)}</span>
                {pet.originalPrice && pet.originalPrice > pet.listingPrice && (
                  <span className="original-price">{formatPrice(pet.originalPrice)}</span>
                )}
              </div>
            )}
            {pet.listingType === 'Adoption' && !isOwner && (
              <div className="price-section adoption">
                <span className="price">{pet.listingPrice ? formatPrice(pet.listingPrice) : 'Miễn phí'}</span>
                {pet.listingPrice > 0 && <span className="note">Phí hỗ trợ chăm sóc</span>}
              </div>
            )}

            {/* Tags */}
            <div className="pet-tags">
              {pet.isFeatured && <span className="tag featured">⭐ Nổi bật</span>}
              {pet.vaccinated && <span className="tag vaccinated">✓ Đã tiêm phòng</span>}
              {pet.neutered && <span className="tag neutered">✓ Đã triệt sản</span>}
              {pet.microchipId && <span className="tag microchip">✓ Có microchip</span>}
            </div>

            {/* Details Table */}
            <div className="details-table">
              <div className="detail-row"><span className="label">Loài</span><span className="value">{typeNames[pet.type] || pet.type}</span></div>
              <div className="detail-row"><span className="label">Giống</span><span className="value">{pet.breed || 'N/A'}</span></div>
              <div className="detail-row"><span className="label">Giới tính</span><span className="value">{genderNames[pet.gender] || pet.gender}</span></div>
              <div className="detail-row"><span className="label">Tuổi</span><span className="value">{getAgeLabel(pet)}</span></div>
              {pet.color && <div className="detail-row"><span className="label">Màu sắc</span><span className="value">{pet.color}</span></div>}
              {pet.weight && <div className="detail-row"><span className="label">Cân nặng</span><span className="value">{pet.weight.toFixed(2)} {pet.weightUnit || 'kg'}</span></div>}
              {pet.healthNotes && <div className="detail-row"><span className="label">Sức khỏe</span><span className="value">{pet.healthNotes}</span></div>}
              {pet.origin && <div className="detail-row"><span className="label">Xuất xứ</span><span className="value">{pet.origin}</span></div>}
            </div>

            {/* Vaccination */}
            {pet.vaccinated && pet.vaccinationDetails && (
              <div className="vaccination-section">
                <h4>💉 Chi tiết tiêm phòng</h4>
                <p>{pet.vaccinationDetails}</p>
              </div>
            )}

            {/* Actions */}
            {pet.listingType === 'Sale' && !isOwner && (
              <div className="action-buttons">
                {!isPetInCart() ? (
                  <button className="btn-primary" onClick={handleAddToCart}>🛒 Thêm vào giỏ hàng</button>
                ) : (
                  <button className="btn-in-cart" disabled>✓ Đã trong giỏ hàng</button>
                )}
                <button className="btn-secondary">📞 Hoặc liên hệ: 0901 234 567</button>
              </div>
            )}
            {pet.listingType === 'Adoption' && !isOwner && (
              <div className="action-buttons">
                <button className="btn-adopt">❤️ Liên hệ nhận nuôi: 0901 234 567</button>
              </div>
            )}

            <div className="view-count">👁️ {pet.viewCount || 0} lượt xem</div>
          </div>
        </div>

        {/* Description */}
        {(pet.description || pet.listingDescription) && (
          <div className="description-section">
            <h3>📋 Mô tả chi tiết</h3>
            <p>{pet.listingDescription || pet.description}</p>
          </div>
        )}

        {/* Similar Pets */}
        {similarPets.length > 0 && (
          <div className="similar-section">
            <h3>🐾 Thú cưng tương tự</h3>
            <div className="similar-grid">
              {similarPets.map(p => (
                <div className="similar-card" key={p._id} onClick={() => navigate(`/pets/${p._id}`)}>
                  <div className="similar-image">
                    <img src={getImageUrl(p.imageUrl)} alt={p.name} onError={e => { (e.target as HTMLImageElement).src = '/assets/images/default-pet.svg'; }} />
                    {p.listingType !== 'None' && (
                      <span className={`listing-badge ${p.listingType === 'Adoption' ? 'adoption' : 'sale'}`}>
                        {listingLabels[p.listingType]}
                      </span>
                    )}
                  </div>
                  <div className="similar-info">
                    <h4>{p.name}</h4>
                    <p>{typeNames[p.type] || p.type} • {p.breed}</p>
                    {p.listingType === 'Sale' && <span className="price">{formatPrice(p.listingPrice)}</span>}
                    {p.listingType === 'Adoption' && <span className="price free">Miễn phí</span>}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ume-frontend/src/app/pages/pet-detail/pet-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { CartService } from '../../services/cart.service';
import { AuthService } from '../../services/auth.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-pet-detail',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './pet-detail.component.html',
  styleUrl: './pet-detail.component.scss'
})
export class PetDetailComponent implements OnInit {
  pet: any = null;
  similarPets: any[] = [];
  loading = true;
  qrCodeUrl = '';
  isOwner = false;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private apiService: ApiService,
    private cartService: CartService,
    public authService: AuthService,
    private toastr: ToastrService
  ) {}

  getImg(path: string): string {
    return this.apiService.getImageUrl(path, 'assets/images/default-pet.svg');
  }

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.loadPet(params['id']);
    });
  }

  loadPet(id: string): void {
    this.loading = true;
    this.apiService.getPet(id).subscribe({
      next: (res: any) => {
        this.pet = res.data || res;
        this.isOwner = this.authService.isLoggedIn && this.pet?.owner?._id === this.authService.currentUser?._id;
        this.loading = false;
        this.generateQRCode();
        this.loadSimilarPets();
      },
      error: () => {
        this.loading = false;
        this.toastr.error('Không tìm thấy thú cưng');
        this.router.navigate(['/pets']);
      }
    });
  }

  loadSimilarPets(): void {
    if (!this.pet) return;
    // Don't show similar pets for customers viewing their own pet
    if (this.isOwner && !this.authService.isAdminOrStaff) return;
    this.apiService.getPets({ type: this.pet.type, limit: 4 }).subscribe({
      next: (res: any) => {
        const all = res.data?.pets || res.data || [];
        this.similarPets = all.filter((p: any) => p._id !== this.pet._id).slice(0, 4);
      }
    });
  }

  generateQRCode(): void {
    const url = window.location.href;
    this.qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(url)}`;
  }

  addToCart(): void {
    if (!this.authService.isLoggedIn) {
      this.toastr.warning('Vui lòng đăng nhập');
      this.router.navigate(['/login']);
      return;
    }
    this.cartService.addPetToCart(this.pet);
    this.toastr.success(`Đã thêm ${this.pet.name} vào giỏ hàng!`);
  }

  isPetInCart(): boolean {
    return this.cartService.items.some(i => i.product._id === this.pet?._id && i.itemType === 'pet');
  }

  viewPetDetail(petId: string): void {
    this.router.navigate(['/pets', petId]);
  }

  getTypeName(type: string): string {
    const m: any = { Dog: 'Chó', Cat: 'Mèo', Bird: 'Chim', Fish: 'Cá', Hamster: 'Hamster', Rabbit: 'Thỏ', Other: 'Khác' };
    return m[type] || type;
  }

  getGenderName(g: string): string {
    const m: any = { Male: 'Đực', Female: 'Cái', Unknown: 'Chưa rõ' };
    return m[g] || g;
  }

  getAgeLabel(pet: any): string {
    if (!pet?.age) return 'N/A';
    const unit = pet.ageUnit === 'years' ? 'tuổi' : 'tháng';
    return `${pet.age} ${unit}`;
  }

  formatPrice(price: number): string {
    if (!price) return 'Miễn phí';
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
  }

  getPetCode(): string {
    if (!this.pet) return '';
    if (this.pet.code) return this.pet.code;
    const date = new Date(this.pet.createdAt);
    const y = date.getFullYear().toString().slice(-2);
    const m = (date.getMonth() + 1).toString().padStart(2, '0');
    const d = date.getDate().toString().padStart(2, '0');
    const id = this.pet._id?.slice(-4) || '0000';
    return `PET${y}${m}${d}${id}`;
  }

  getListingTypeLabel(type: string): string {
    const m: any = { Sale: 'Đang bán', Adoption: 'Nhận nuôi', None: '' };
    return m[type] || '';
  }
}

<div class="pet-detail-page" *ngIf="!loading && pet">
  <!-- Main Content -->
  <div class="container">
    <div class="pet-detail-content">
      <!-- Left: Image + QR -->
      <div class="pet-image-section">
        <div class="main-image">
          <img [src]="getImg(pet.imageUrl)" [alt]="pet.name"
               onerror="this.src='assets/images/default-pet.svg'">
        </div>
        <!-- QR Code -->
        <div class="qr-section">
          <p><i class="fas fa-qrcode"></i> Quét mã QR để chia sẻ</p>
          <img [src]="qrCodeUrl" alt="QR Code" class="qr-image">
        </div>
      </div>

      <!-- Right: Info -->
      <div class="pet-info-section">
        <!-- Name & Code -->
        <h2 class="pet-name"><i class="fas fa-paw"></i> {{ pet.name }}</h2>
        <p class="pet-code">Mã: {{ getPetCode() }}</p>

        <!-- Adoption Banner -->
        <div class="adoption-banner" *ngIf="pet.listingType === 'Adoption' && !isOwner">
          <i class="fas fa-heart"></i> Thú cưng cần tìm nhà yêu thương
        </div>

        <!-- Owner Banner -->
        <div class="adoption-banner" *ngIf="isOwner" style="background:#e8f5e9;color:#2e7d32;border-color:#c8e6c9">
          <i class="fas fa-user-check"></i> Đây là thú cưng của bạn
        </div>

        <!-- Price Section -->
        <div class="price-section" *ngIf="pet.listingType === 'Sale' && !isOwner">
          <span class="price">{{ formatPrice(pet.listingPrice) }}</span>
          <span class="original-price" *ngIf="pet.originalPrice && pet.originalPrice > pet.listingPrice">
            {{ formatPrice(pet.originalPrice) }}
          </span>
        </div>
        <div class="price-section adoption" *ngIf="pet.listingType === 'Adoption' && !isOwner">
          <span class="price">{{ pet.listingPrice ? formatPrice(pet.listingPrice) : 'Miễn phí' }}</span>
          <span class="price-note" *ngIf="pet.listingPrice">Phí hỗ trợ chăm sóc</span>
        </div>

        <!-- Tags -->
        <div class="pet-tags">
          <span class="tag featured" *ngIf="pet.isFeatured">⭐ Nổi bật</span>
          <span class="tag vaccinated" *ngIf="pet.vaccinated"><i class="fas fa-check"></i> Đã tiêm phòng</span>
          <span class="tag neutered" *ngIf="pet.neutered"><i class="fas fa-check"></i> Đã triệt sản</span>
          <span class="tag microchip" *ngIf="pet.microchipId"><i class="fas fa-check"></i> Có microchip</span>
        </div>

        <!-- Details Table -->
        <div class="details-table">
          <div class="detail-row">
            <span class="label">Loài</span>
            <span class="value">{{ getTypeName(pet.type) }}</span>
          </div>
          <div class="detail-row">
            <span class="label">Giống</span>
            <span class="value">{{ pet.breed || 'N/A' }}</span>
          </div>
          <div class="detail-row">
            <span class="label">Giới tính</span>
            <span class="value">{{ getGenderName(pet.gender) }}</span>
          </div>
          <div class="detail-row">
            <span class="label">Tuổi</span>
            <span class="value">{{ getAgeLabel(pet) }}</span>
          </div>
          <div class="detail-row" *ngIf="pet.color">
            <span class="label">Màu sắc</span>
            <span class="value">{{ pet.color }}</span>
          </div>
          <div class="detail-row" *ngIf="pet.weight">
            <span class="label">Cân nặng</span>
            <span class="value">{{ pet.weight | number:'1.2-2' }} {{ pet.weightUnit || 'kg' }}</span>
          </div>
          <div class="detail-row" *ngIf="pet.healthNotes">
            <span class="label">Tình trạng sức khỏe</span>
            <span class="value">{{ pet.healthNotes }}</span>
          </div>
          <div class="detail-row" *ngIf="pet.origin">
            <span class="label">Xuất xứ</span>
            <span class="value">{{ pet.origin }}</span>
          </div>
        </div>

        <!-- Vaccination Details -->
        <div class="vaccination-section" *ngIf="pet.vaccinated && pet.vaccinationDetails">
          <h4><i class="fas fa-syringe"></i> Chi tiết tiêm phòng</h4>
          <p>{{ pet.vaccinationDetails }}</p>
        </div>

        <!-- Action Buttons -->
        <div class="action-buttons" *ngIf="pet.listingType === 'Sale' && !isOwner">
          <button class="btn-primary" (click)="addToCart()" *ngIf="!isPetInCart()">
            <i class="fas fa-cart-plus"></i> Thêm vào giỏ hàng
          </button>
          <button class="btn-in-cart" *ngIf="isPetInCart()" disabled>
            <i class="fas fa-check"></i> Đã trong giỏ hàng
          </button>
          <button class="btn-secondary">
            <i class="fas fa-phone"></i> Hoặc liên hệ: 0901 234 567
          </button>
        </div>

        <div class="action-buttons" *ngIf="pet.listingType === 'Adoption' && !isOwner">
          <button class="btn-adopt">
            <i class="fas fa-heart"></i> Liên hệ nhận nuôi: 0901 234 567
          </button>
        </div>

        <!-- View Count -->
        <div class="view-count">
          <i class="fas fa-eye"></i> {{ pet.viewCount || 0 }} lượt xem
        </div>
      </div>
    </div>

    <!-- Description -->
    <div class="description-section" *ngIf="pet.description || pet.listingDescription">
      <h3><i class="fas fa-clipboard"></i> Mô tả chi tiết</h3>
      <p>{{ pet.listingDescription || pet.description }}</p>
    </div>

    <!-- Similar Pets -->
    <div class="similar-section" *ngIf="similarPets.length > 0">
      <h3><i class="fas fa-paw"></i> Thú cưng tương tự</h3>
      <div class="similar-grid">
        <div class="similar-card" *ngFor="let p of similarPets" (click)="viewPetDetail(p._id)">
          <div class="similar-image">
            <img [src]="getImg(p.imageUrl)" [alt]="p.name"
                 onerror="this.src='assets/images/default-pet.svg'">
            <span class="listing-badge" *ngIf="p.listingType !== 'None'"
                  [class.adoption]="p.listingType === 'Adoption'"
                  [class.sale]="p.listingType === 'Sale'">
              {{ getListingTypeLabel(p.listingType) }}
            </span>
          </div>
          <div class="similar-info">
            <h4>{{ p.name }}</h4>
            <p>{{ getTypeName(p.type) }} • {{ p.breed }}</p>
            <span class="price" *ngIf="p.listingType === 'Sale'">{{ formatPrice(p.listingPrice) }}</span>
            <span class="price free" *ngIf="p.listingType === 'Adoption'">Miễn phí</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Loading -->
<div class="loading-state" *ngIf="loading">
  <div class="spinner"></div>
  <p>Đang tải thông tin thú cưng...</p>
</div>
